### ISSUE TITLE
Is there a way to cause a weapon switch on immune?

### ISSUE THREAD

**Issue by Innova133** [blizzhackers/kolbot#103]
I just got my javazon to hell. I am using stab for lightning immune, and it works ok...but it would work better if it did a weapon switch first. Is there a way to make d2bot switch weapons when using the alternate attach for immunes?

Ie, when using:

`Config.AttackSkill[5] = 10;`

It would also cause it to switch weapons.

**Comment by alinweak** [comment]
i wish switch weapon when cast energy shield by sor ，because I have a rune staff with + 3 energy shield. but bot has no casting skill

**Comment by mf022** [comment]
> when using:
> 
> `Config.AttackSkill[5] = 10;`
> 
> It would also cause it to switch weapons.

you should add an extra line before line 47 <https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/common/Attacks/Amazon.js#L46-L48>
```
			me.weaponswitch;
```

**Comment by mf022** [comment]
> i wish switch weapon when cast energy shield by sor ，because I have a rune staff with + 3 energy shield. but bot has no casting skill

during the default precast, bot is calculating the best slot of energy shield is <https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/common/Precast.js#L30-L68> and he cast it if you have at least 1 point in energy shield skill, according to lines <https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/common/Precast.js#L151-L153>.
