### ISSUE TITLE
What function opens the quest panel?

### ISSUE THREAD

**Issue by Goldenbell-123** [blizzhackers/kolbot#104]
Thank you.

**Comment by mf022** [comment]
bot only check the quest, *me.getQuest( int act, int quest );* - <https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/sdk/commandRef.htm#L862>

or d2bs can check if the quest panel is open - <https://github.com/blizzhackers/kolbot/blob/master/d2bs/api.html#L1190> - *getUIFlag(18)*
