### ISSUE TITLE
External Device

### ISSUE THREAD

**Issue by Daladlad** [blizzhackers/kolbot#105]
I can't seems to access Limedrop from an external device after putting my external IP in the server file.
Is this still a feature that is going to come later?

**Comment by Fa-b** [comment]
If by external IP you mean your public IP it is wrong. In server.js put your DHCP LAN IP and your router will have to be configured to forward the tcp port to your hosting device. Be sure to configure your local firewall to allow requests on that port too.
Be aware that http is unsecure/not encrypted.
