### ISSUE TITLE
Add Global Realm down handler to toolsthread.js

### ISSUE THREAD

**Issue by casualBotter** [blizzhackers/kolbot#108]
I noticed that toolsthread doesn't have a handler for the Realm going down in xx minutes global message for when there is maintenance on the servers. I don't know how to write this myself for I'm not sure where to find each of the modes that are passed into this.gameEvent if someone cam help me with that I'll write it otherwise something simple like when it gets that msg reads the minutes then shuts down for hour + minutes read then restarts since maintenance usually last an hour

**Comment by laztheripper** [comment]
`		case 0x0f: // "Realm going down in %Param1 minutes."
			D2Bot.printToConsole(getLocaleString(3651).replace("%d", param1) + " Stopping...");
			this.togglePause();
			Town.goToTown();
			delay(rand(5,60) * 1000);
			D2Bot.stop();
			
			break;`
