### ISSUE TITLE
follower script [distance]

### ISSUE THREAD

**Issue by fabio1999ita** [blizzhackers/kolbot#109]
hi, there is a way to set a distance between leader and follower? because follower try always to go to leader and sometimes they dead

**Comment by Fa-b** [comment]
you can play with that, take Wakka.js as a reference, it keeps a distance ([here](https://github.com/blizzhackers/kolbot/blob/744947891dd968e9a8e3d32b2009f524594b196f/d2bs/kolbot/libs/bots/Wakka.js#L168)).
[this](https://github.com/blizzhackers/kolbot/blob/744947891dd968e9a8e3d32b2009f524594b196f/d2bs/kolbot/libs/bots/Follower.js#L621) is where you want to make your modifications not to come too close to the leader.
