### ISSUE TITLE
Pickit Toggle

### ISSUE THREAD

**Issue by xWickedx420** [blizzhackers/kolbot#112]
Anyway we can turn pickit on/off in game?

**Comment by Sylvm** [comment]
Hello, in your config file (ex: Sorceress.Laiya.js) you have to comment the line with file.nip `Config.PickitFiles.push("kolton.nip"); ` 
in 
**//**` Config.PickitFiles.push("kolton.nip");`

**Comment by laztheripper** [comment]
This is correct, comment out the pickit files in the char config and reload (alt+home, "reload", enter)
