### ISSUE TITLE
when bot is paused

### ISSUE THREAD

**Issue by fabio1999ita** [blizzhackers/kolbot#113]
the bot in game when is in pause quit whit leader_Config.QuitList_ and quit if _Config.MaxGameTime_ is expired

**Comment by Fa-b** [comment]
because the MaxGameTime is handled within D2BS, set it to 0 to deactivate it fully.
Config.QuitList is managed by ToolsThread.js together with other things like Chicken and Numpad mule force or end keypress.

Imo this default behaviour is not a bug, but you can change it by guarding from quitting using the running flag of `default.dbj`. As an example how you can do that for the QuitList [here](https://github.com/blizzhackers/kolbot/blob/744947891dd968e9a8e3d32b2009f524594b196f/d2bs/kolbot/tools/ToolsThread.js#L474):
```js
case 0x03: // "%Name1(%Name2) left our world. Diablo's minions weaken."
	var script = getScript("default.dbj");
	if (script && script.running &&
			((typeof Config.QuitList === "string" && Config.QuitList.toLowerCase() === "any") ||
			(Config.QuitList instanceof Array && Config.QuitList.indexOf(name1) > -1))) {
		print(name1 + (mode === 0 ? " timed out" : " left"));

		if (typeof Config.QuitListDelay !== "undefined" && typeof quitListDelayTime === "undefined" && Config.QuitListDelay.length > 0) {
			Config.QuitListDelay.sort(function(a, b){return a-b});
			quitListDelayTime = getTickCount() + rand(Config.QuitListDelay[0] * 1e3, Config.QuitListDelay[1] * 1e3);
		} else {
			quitListDelayTime = getTickCount();
		}

		quitFlag = true;
	}
```

This should disable QuitList while while paused.

**Comment by fabio1999ita** [comment]
i had fix it whit my code:
`if (script) {
				if (script.running) {
					if (i === 0) { // default.dbj
						me.maxgametime = 0;
						print("ÿc1Pausing.");
					}

					// don't pause townchicken during clone walk
					if (scripts[i] !== "tools/townchicken.js" || !cloneWalked) {
						script.pause();
					}
				} else {
					if (i === 0) { // default.dbj
						me.maxgametime = Config.MaxGameTime * 1000;
						print("ÿc2Resuming.");
					}

					script.resume();
				}
			}`
it works pretty good but the problem of my code is that: the maxvalue is set to 0 but the countdown doesn't stop, so when i resume if maxtime > countdown the char quit but this is not a problem

anyway i will try your code this night

**Comment by Fa-b** [comment]
well, maxgametime is the maximum ingame time, it doesn't matter if it's paused or not it's still ingame so not really something that needs fixing.. I'm sure though, you could easily account for it by storing the tickCount and adding the diff on resume:

On top of the file add a property:
```js
function main() {
	var i, mercHP, ironGolem, tick, merc, suspendTick,
[..]
```
Then in your pause key handler
```js
if (script) {
	if (script.running) {
		if (i === 0) { // default.dbj
			suspendTick = getTickCount();
			me.maxgametime = 0;
			print("ÿc1Pausing.");
		}

		// don't pause townchicken during clone walk
		if (scripts[i] !== "tools/townchicken.js" || !cloneWalked) {
			script.pause();
		}
	} else {
		if (i === 0) { // default.dbj
			me.maxgametime = (getTickCount() - suspendTick) + Config.MaxGameTime * 1000;
			print("ÿc2Resuming.");
		}
			script.resume();
	}
}
```
This should behave the same as suspending the counter in d2bs.

**Comment by fabio1999ita** [comment]
this should be put in the official version, I remember once this was there
