### ISSUE TITLE
(newbie)have some questions - hammerdin without enigma

### ISSUE THREAD

**Issue by ploneche** [blizzhackers/kolbot#115]
reckon many of guys don't have enigma yet. 

cuz it's after only few days from new start. 

so.. my paladin has some problems to arrive Durance of hate and CS.

i've searched here and 

found some answers that mentioning 

"Config.cleartype = 0;" 

and

set 'notele' to "false" 

but.. it ain't work on mine. 

i've downloaded programs by SVN.

so i think it would be latest version of it.

i can't recognize what's the problem. 

what am i missing??? 

is the "Config.~~ = 0;" - line
should be inserted within "Diablo" or "Mephisto" Script??

beg your help please.

**Comment by fabio1999ita** [comment]
notele need be true if you haven't teleport, anyway bot whitout teleport doesn't work as well
