### ISSUE TITLE
Bot sells equipped gear

### ISSUE THREAD

**Issue by batdourden** [blizzhackers/kolbot#116]
Kolbot diablo 2 bot keeps selling equipped gear

**Comment by fabio1999ita** [comment]
it is not true

**Comment by gtoilet** [comment]
never seen that happen
get a video and well go from there
your using the newer/newest version
19.3.3.100 version +   ?

**Comment by batdourden** [comment]
Keeps happening while I’m gone. I just came back and it had sold my perfect shako and monarch spirit. I am on the newest version currently

**Comment by batdourden** [comment]
![image](https://user-images.githubusercontent.com/66945969/85072635-67e53f80-b187-11ea-89b4-a226fd199245.png)

dont know if you can see this but i tried to see if i could download an update through SVN and this popped up. if you cant see image it says "error unable to connect to  repository at URL"

**Comment by xWickedx420** [comment]
you have the wrong repo. use this one https://github.com/blizzhackers/kolbot

**Comment by batdourden** [comment]
awesome, thank you that one did work! I'll keep an eye on it and see if it tries to sell anything again. hopefully you wont hear back from me

**Comment by batdourden** [comment]
well it didnt fix the issue. now as soon as i open the game it tries to though one of my gear into the cube with a ral rune and then crashes. tried to get a recording but im not that good with a computer and the recorder i have wont work on d2 for some reason.

**Comment by Fa-b** [comment]
> 1 Ral Rune + 1 Flawed Gem (any kind) + Armor -> Fully Repaired and Recharged Armor

maybe? Check your character config if cupe repairing is enabled..

**Comment by batdourden** [comment]
i did check that, turned everything off but is was still doing it. i ended up just unloading and redownloading the program and everything seems to be working right now

**Comment by Fa-b** [comment]
good to hear it's working now. Please close your issues once they are solved.
