### ISSUE TITLE
Source code for LimeDrop

### ISSUE THREAD

**Issue by hutber** [blizzhackers/kolbot#117]
I am after making some wholesale changes to LimeDrop but can only find the compiled version inside the repo.

Is it possible to get access to the API so I can create a new frontend platform for it?

Thanks guys :smiley:

**Comment by Fa-b** [comment]
Almost all the available API is in D2Bot.js. I'm also working on improving limedrop, you might wanna check the dev branch in my fork.
Are you in discord? Would make communication easier.

**Comment by hutber** [comment]
ye I'm on there too, username is "hutber#4947"
