### ISSUE TITLE
Selling items only once inventory is full

### ISSUE THREAD

**Issue by Taluah** [blizzhackers/kolbot#118]
Is there a way to set the bot up to sell items only once the inventory is full? I'd like to avoid the vendor trips for 1 or 2 items.

Thanks!

**Comment by Fa-b** [comment]
Be aware that the bot goes to vendor formultiple things, not onoly to identify and sell items..

I guess you could probably guard some of the chore tasks to only go ID and sell stuff if the available inventory space exceeds a predefined percentage somewhere [here](https://github.com/blizzhackers/kolbot/blob/744947891dd968e9a8e3d32b2009f524594b196f/d2bs/kolbot/libs/common/Town.js#L79):
```js
this.repair(repair);
this.reviveMerc();
this.heal();
this.fillTome(518);

if (Config.FieldID) {
	this.fillTome(519);
}

this.clearScrolls();
this.buyPotions();
this.buyKeys();
this.shopItems();

// identify, sell and stash items only if inventory space is filled by more than 60%
// could cause issues if too many slots are locked and the bot is unable to pick items and tries to make space
if (Storage.Inventory.UsedSpacePercent() > 60) {
	this.identify();
	this.clearInventory();
	this.stash(true);
}

Item.autoEquip();
this.gamble();
Cubing.doCubing();
Runewords.makeRunewords();
```

Not sure what the outcome of this reordering would be. You may find it is not working as expected as it might start stashing or dropping unid items, so care must be taken when playing with this...

**Comment by Taluah** [comment]
> Be aware that the bot goes to vendor formultiple things, not onoly to identify and sell items..
> 
> I guess you could probably guard some of the chore tasks to only go ID and sell stuff if the available inventory space exceeds a predefined percentage somewhere [here](https://github.com/blizzhackers/kolbot/blob/744947891dd968e9a8e3d32b2009f524594b196f/d2bs/kolbot/libs/common/Town.js#L79):
> 
> ```js
> this.repair(repair);
> this.reviveMerc();
> this.heal();
> this.fillTome(518);
> 
> if (Config.FieldID) {
> 	this.fillTome(519);
> }
> 
> this.clearScrolls();
> this.buyPotions();
> this.buyKeys();
> this.shopItems();
> 
> // identify, sell and stash items only if inventory space is filled by more than 60%
> // could cause issues if too many slots are locked and the bot is unable to pick items and tries to make space
> if (Storage.Inventory.UsedSpacePercent() > 60) {
> 	this.identify();
> 	this.clearInventory();
> 	this.stash(true);
> }
> 
> Item.autoEquip();
> this.gamble();
> Cubing.doCubing();
> Runewords.makeRunewords();
> ```
> 
> Not sure what the outcome of this reordering would be. You may find it is not working as expected as it might start stashing or dropping unid items, so care must be taken when playing with this...

While I greatly reply you taking the time to respond to my request... I think the chances of me breaking it are far greater than the opportunity to optimize lol. I think I'll leave it.
