### ISSUE TITLE
Shutingdown bot

### ISSUE THREAD

**Issue by BartoszJedynak** [blizzhackers/kolbot#119]
Hi, is the way to add function when bot see "The realm is going down in x minutes" bot shutingdown for prevent ban ip and cd-keys?
thx

**Comment by LAeRacing** [comment]
yes 💯 

In **ToolsThread.js** after the last "break;" in the "this.gameEvent" section.
This will stop any bots in game when they see the realm is going down message.

`case 0x0f: // "Realm going down in %Param1 minutes."
            D2Bot.printToConsole(getLocaleString(3651).replace("%d", param1) + " Stopping...");
            D2Bot.stop();
               break;`

**Comment by BartoszJedynak** [comment]
thx

**Comment by Fa-b** [comment]
answered
