### ISSUE TITLE
River of Flame/Chaos Issue

### ISSUE THREAD

**Issue by xWickedx420** [blizzhackers/kolbot#120]
Paladin Bot without Enigma. Bot runs fine most of the time. Throws error line 460 in Diablo.js when this happens.  Bot will take river waypoint. Start walking to chaos. Anything in its way, it will attack in kill the first time. Second time something is on its way it will throw the 460 error instead of even attempting to attack or clear. Anyway we can fix this?

Also Storm Casters get stuck behind the wall sometimes. The bot will literally sit there for hours (even with enigma) and try to attack this storm caster.  Spamming no valid positions for storm caster.

**Comment by Fa-b** [comment]
Sorry, the bot is not really optimized for walking to destinations. I guess the first issue is something that could be improved in Pather.js.
The second issue is well known and afaik Stormcaster's should be skipped after a preset count of attempts but I could be wrong.. definately smt. that should be improved too.

**Comment by xWickedx420** [comment]
That’s actually a good idea. I’ve seen it happen on sorc and paladin bot, if you don’t have a max game time set it can literally get stuck for hours on end.

**Comment by tunz347** [comment]
If you never want your hammerdin to stuck at Storm Caster's change your clear type to 0xF = skip normal or 0x7 = champions/bosses, or simply skip imune to lightning. I never had it happend on a Blizzard Sorceress.
