### ISSUE TITLE
[REQUEST] autohide console????

### ISSUE THREAD

**Issue by CanadianJeff** [blizzhackers/kolbot#121]
starting a game with just D2BotMap.dbj to use it for map hack online pointless to keep showing console each time join a game

**Comment by sersh** [comment]
press home

**Comment by CanadianJeff** [comment]
doing that 200x gets stupid it should be hidden and home to show it

**Comment by 5noop** [comment]
What the console says ? It should only show when there is an error or warning.

**Comment by xWickedx420** [comment]
it does show, but because there is no attack order set. anyway to hide that for manual play?

**Comment by 5noop** [comment]
Then you can either set any attack skill > -1 in your config or simply remove this line:
https://github.com/blizzhackers/kolbot/blob/3682102a1f9dc4b3da75e08841996b9ddae9f34e/d2bs/kolbot/libs/common/Attack.js#L23

**Comment by xWickedx420** [comment]
Does that affect all of our bots then? Also how do we toggle pickit in-game?

**Comment by CanadianJeff** [comment]
Snoop that worked marking this as solved and closed feel free to reopen
