### ISSUE TITLE
MFHelper unit area error

### ISSUE THREAD

**Issue by joemonstar** [blizzhackers/kolbot#124]
I started fresh with a new checkout of 20.6.7.100, rebuilt all files, and using mfhelper to clear a few bosses and cows before diablo/baal. This works great in 19.3.3. Now the follower throws a strict warning for unit.area and stands in town ignoring boss kill commands. It does go into cows when summoned though. 
![Capture](https://user-images.githubusercontent.com/67278583/85300787-a111fe00-b46c-11ea-8416-8e59e165a35c.PNG)

**Comment by fabio1999ita** [comment]
it is possible that you have disabled some lines in your character configuration
like: //Config.something

so check all char config, if you don't find nothing download a fresh char config and setup it by 0

**Comment by joemonstar** [comment]
Thank you sir! I've tried latest kolbot version with both old char config files, and creating new config files and setup from scratch. I haven't disabled any lines. I didn't modify misc.js either.

**Comment by Fa-b** [comment]
Looks like misconfiguration, either your follower is not partied with the specified leader or the specified leader name does not match the actual character name ingame.

**Comment by fabio1999ita** [comment]
@joemonstar if you hadn't solved it can you post config? of leader and mf, say me also name of char leader and mfhelper

**Comment by 5noop** [comment]
This pr https://github.com/blizzhackers/kolbot/pull/126 should fix it.
