### ISSUE TITLE
Reconnecting issue

### ISSUE THREAD

**Issue by KKzLEO** [blizzhackers/kolbot#125]
Hi,

My wifi is unstable and will have a down time(1s) then the bot will restart the profile.
But after reconnecting to bnet successfully, the bot will hit the leave button and back to home screen instead of entering the account and password.

The log shows `login time out`

How do I set the profile or config to avoid this issue?

Thanks!

**Comment by fabio1999ita** [comment]
try to add time in this settings
![image](https://user-images.githubusercontent.com/27001568/85931488-07f84280-b8c5-11ea-80e1-b77498d22f38.png)

**Comment by KKzLEO** [comment]
Thank for ur reply. I solved the wifi downtime issue so close this.
