### ISSUE TITLE
Clearing path kills cow king?

### ISSUE THREAD

**Issue by arrickd** [blizzhackers/kolbot#127]
I believe this line in combination with cows will kill the king 

Config.ClearPath = 0x7; // Monster spectype to kill while traveling. 0xF = skip normal, 0x7 = champions/bosses, 0 = all

**Comment by Fa-b** [comment]
This is true since the cow script does not really avoid killing the king but rather attempts to avoid the area where he is.

**Comment by daniel-arrick** [comment]
Hmm ok. Seems like the king should be a valid target when explicitly set. Ty

**Comment by schmitch** [comment]
btw. it's better to set `{ClearType: 0}` instead of `true`  on the cow level and not use ClearPath at all.
