### ISSUE TITLE
Adding `Antishake`, `Full Light Radius` and `Showing Shrines images on the automap`

### ISSUE THREAD

**Issue by Ognyan1987** [blizzhackers/kolbot#130]
How can  _Antishake_ , _Full light radius_  , _Item Sockets_ , _Ethereal Items_ and _Showing Shrines_ image on the automap  be added to Kolbot's  D2BotMap and  to all starters?

- Antishake - prevents screen shaking when u kill Andariel , duriel , diablo or whatever causes shcreenshake

- Full Lights radius - makes u able to see every dark corner/place  arround u , same as u have +200 to light radius from items

- Showing Shrines image on the automap - makes able to see what are the shrines on the automap

- Item Sockets - when items is on the ground  or u move the cursor over it while you got it in the inventory it shows how much sockets  **[1]** , **[2]** . **[3]** , **ect...**  does it has , if it has any!  -> Example:   **Shako[1]** , **Monarch[4]**

- Ethereal Items -  if the items on the ground or u move the cursor over it while you got it in the inventory shows if  is Ethereal by having **[E]** at the end of the items name ~ Example:   **Shako[E]**

Example with both sockets and Ethereal  :  **Shako[1][E]**

**Comment by Nishimura-Katsuo** [comment]
Antishake wouldn't be hard to add to patch.json:

{"Name":"antishake","Version":"1.14d","Module":14,"Offset":486720,"Data":"kA=="}

This isn't tested. I only just converted it over from a personal project. Let me know if it works.

**Comment by jaenster** [comment]
> 
> 
> Antishake wouldn't be hard to add to patch.json:
> 
> {"Name":"antishake","Version":"1.14d","Module":14,"Offset":486720,"Data":"kA=="}
> 
> This isn't tested. I only just converted it over from a personal project. Let me know if it works.

That is wrong, use this

```json
{"Name": "noshake", "Version":"1.14d","Module":14,"Offset":486720, "Data": "ww=="}
```

**Comment by gtoilet** [comment]
{"Name":"rdblock","Version":"1.14d","Module":14,"Offset":301776,"Data":"ww=="}
is in the base code
should be removed and replaced with above?

**Comment by Nishimura-Katsuo** [comment]
oh my mistake, I got my op code mixed up, yeah use this one lol

**Comment by Nishimura-Katsuo** [comment]
> {"Name":"rdblock","Version":"1.14d","Module":14,"Offset":301776,"Data":"ww=="}
> is in the base code
> should be removed and replaced with above?
> asking because of the data:ww==

no just add this as another line under everything you already have

**Comment by Ognyan1987** [comment]
up
