### ISSUE TITLE
vanilla kolbot wont automule correctly

### ISSUE THREAD

**Issue by maelstrm30** [blizzhackers/kolbot#131]
Forced to use an updated kolbot client, i dl'd
https://github.com/kolton/d2bot-with-kolbot
only using notepad++ and only editting the top user section of automule.js
my bot will start automule pick up items on the ground but when the inventory is full
it goes to stash picks an item to move over but wont place the item in the stash.  it then drops the item and tries to pick move things from the ground then tries to move them to the stash and fails.
i get this looping message in the profile manager
MainLoopException: unit.description is undefined (mulelogger.js #41)
Looking at line 41 in mulelogger
desc = unit.description.split("\n");

**Comment by noah-** [comment]
what is vanilla vs updated?

**Comment by maelstrm30** [comment]
Vanilla means no serious edits, just dl , unzip, add keys, add automule (no out of bounds edits), i did add my pickits, and i started a fresh char config for the paladin.  but again no edits to any scripts or parts of scripts.
Again, its mules.  but once inventory is full it wont transfer to stash and i get the above error.
MainLoopException: unit.description is undefined (mulelogger.js #41)
spammed hundred times ?

**Comment by koichisue** [comment]
I know it's a bit late.. but I ran into the same problem today and what I figured out was:
If an unique or set item has many attributes and you put something like a rainbow facet in it, the list becomes too long and  Diablo2 won't show the description.
That's when the mulelogger fails, to avoid this add some request before using the property:

` if (unit.description) { `
before 
`desc = unit.description.split("\n");`

and

`
} else {
desc = ["unable to get description"];
}
`
before
`return desc;`


Hope this helps people with the same problem and got here from google.
