### ISSUE TITLE
Regular Crashes

### ISSUE THREAD

**Issue by undixon** [blizzhackers/kolbot#132]
Hello. I have an issue with **regular** crashes, but most often on one of the characters:

I'm currently running two bots, light sorc on key1 and hammer on key2, both run solo on different games.
Also got key3, which is currently used only for automule but i'm planning to use it also for new character soon.

The problem is, on both characters i'm having regular crashes, sometimes at equal intervals that are 30 or 60 min, sometimes the time is longer, but the xx:XX is always the same (XX), for example - crash time 12:23, next crash 12:53, next crash 13:23, then it can be nothing for an hour or two, and again 15:23, 16:23, 16:53 and so on.. Ofc. it's not always xx:x3, i think it depends at what time i start the profiles, but you know what i mean. Most often it's on sorceress, dunno why, she's having like 20 crashes within 100 runs, and hammer is having only a half of it, which is like 10 per 100 runs. Crashes occur in all locations and all scripts randomly, when char is normally fighting, and even in towns, while just moving, gambling, buying potions or selling items.. Sometimes it's ''Window has unexpectedly exited'' and sometimes ''D2BS is not responding'', but the time intervals are the same so i dunno what's causing both of them. What's important - most often only one of the characters are crashing in the moment, but it happened a few times that they crashed in the exact same time with only few seconds difference. (also, one time i saw sorc crash at xx:48 with ''Window has unexpectedly exited'' and hammer crashed like 5 seconds later, also at xx:48 but with ''d2bs is not responding'')

Both Sorc and Pala are running exact same scripts in exact same order and anything else. This problem is bothering me since this ladder started, which is already over a month. Last year when i was playing it was the same but it wasn't really a big problem because i played only for like 3 or 4 weeks at the end of ladder. Since then, i refreshed my hardware, installed fresh Win 10 (i had 8.1), got rid of any apps and stuff that are not neccesary and now i have clean laptop with only d2, kolbot (ofc latest version, downloaded with svn), webbrowser, notepad++, avast and ccleaner which im using from time to time. Also all neccesary things like netframework, c++ and other stuff are installed and updated, together with the drivers and so on.

What is also very important to add here - few days ago the amount of crashes was actually few times bigger than it is now (i had like 15-20 crashes within only 40 runs on sorc, and half of that on hammer) , and what decreased them are changes i did with my wireless network card : i turned off dhcp, set my ipv4 to static, changed ipv4 DNS's and changed DNS's of ipv6 (which i eventually turned off and currently i'm using only ipv4, but nothing changed with that turn off yet so i think i'll turn it back on when i'll be home). With this changes the amount of crashes is much smaller but as i said above - still regular, which gives me no peace and forces me to do something with it, because it's simply not possible (in my point of view) that every crashes are at exactly the same minutes within different hours. 
What's also weird - i thought, since crashes occur like every 30-60-90 or more minutes, maybe it's like the connection is dropping on all devices within this network, also on this laptop.. (so i set the ipv4 to static etc.) but it doesn't seem to be the problem, everything is working fine on ps4, tv and all smartphones, no connection drops at all.

I really don't know what i else i can try to do, so please, help me.

**Comment by Sylvm** [comment]
Hello, can you show the config of your Sorceress.<name>.js and D2BotLead.dbj.
I suspect D2BotLead config to be too tight or maybe you can tell us, do you reach a specific area or a specific script after 30 min ?
Have you modified some scripts ?
