### ISSUE TITLE
Attack before FieldId

### ISSUE THREAD

**Issue by arrickd** [blizzhackers/kolbot#134]
Is there a way to get the bot to clear the area before using Config.FieldID=true ?

The bot will id items while in the middle of a mob which is dangerous.

**Comment by luisfilipepena** [comment]
The safest is set `Config.FieldID = false;` so the bot will go to town for ID.

**Comment by arrickd** [comment]
well yeah but the point is to use field id

**Comment by DarkHorseDre** [comment]
> Is there a way to get the bot to clear the area before using Config.FieldID=true ?

find where pickit checks fieldid before id'ing then use secure position (change the params as appropriate: x, y, 16 yards, 5000 milliseconds):
```js
Attack.securePosition(me.x, me.y, 16, 5000, true);
```
