### ISSUE TITLE
Specifying the priority of crafting

### ISSUE THREAD

**Issue by hunzhang** [blizzhackers/kolbot#136]
When inventory has all the ingredients that meet multiple formula simultaneously , how to specify the priority of crafting ?
e.g. When someone would like to craft blood rings prior to blood boots.
Sorry if there were existing solutions.

**Comment by fabio1999ita** [comment]
there isn't settings for priority, maybe priority is setted by line order of conf file of char

**Comment by hunzhang** [comment]
> there isn't settings for priority, maybe priority is setted by line order of conf file of char

I tried altering the line sequence in the char's conf file, seemed not working. But I will keep watching. Thank you for suggestions.

**Comment by laztheripper** [comment]
To give a chance to all recipes in config to be completed at least on occasion, crafting priority is shuffled every game.
