### ISSUE TITLE
promiscuous battleorder script

### ISSUE THREAD

**Issue by mixkor** [blizzhackers/kolbot#137]
BattleOrders and BoBarbHelper must be merged.

Give BO and Get BO need Config.BattleOrders.failtimer = sec

Composition, Battle Orders.Waiting is not very useful. Delete it or review the merger.

And other unit have to precast while waiting at Waypoint.

///
precast.js

In MFHelper, I wish Baba could sense the identity of a party member and come up next to him and give him a battle order.
(ex paty.getState(32)

**Comment by alinweak** [comment]
i wish switch weapon  when cast energy shield by sor ，because I have a rune staff with + 3 energy shield. but bot has no casting skill

**Comment by DarkHorseDre** [comment]
Not sure a toon can detect the state of another toon

Maybe better to have bogetters check their state and issue a request once bo/shout expires?
then bobabber would read that command, go to getter and BO+Shout them
