### ISSUE TITLE
Way for BaalHelpers to rely on LocalChat?

### ISSUE THREAD

**Issue by notenoughdamage** [blizzhackers/kolbot#141]
Hey all!

I've got my BaalAssistant working just fine, but I can't only get it to take Baal commands through B.Net chat. Diablo's helper scripts seem to do it through local chat, but if I do get my Baal Leader to say the command, the Helper doesn't do anything in Act 5 without it being in B.Net chat, which I would not prefer.

Any suggestions? Thanks!

**Comment by noah-** [comment]
what mode of localchat are you using and is it enabled for all the profiles?

**Comment by notenoughdamage** [comment]
> what mode of localchat are you using and is it enabled for all the profiles?

This is what it looks like on my end, and I enabled it for all the profiles.

Config.LocalChat.Enabled = true; // enable the LocalChat system
	Config.LocalChat.Toggle = false; // optional, set to KEY value to toggle through modes 0, 1, 2
	Config.LocalChat.Mode = 1; // 0 = disabled, 1 = chat from 'say' (recommended), 2 = all chat (for manual play)

**Comment by fabio1999ita** [comment]
is leader set correctly?

**Comment by notenoughdamage** [comment]
Yep! They can use LocalChat just fine for other commands. For BaalHelper specifically, however, if I disabled the game chat that announced hot tp, safe tp, Baal, etc etc, the Helpers don't seem to go?

**Comment by mf022** [comment]
> For BaalHelper specifically, however, if I disabled the game chat that announced hot tp, safe tp, Baal, etc etc, the Helpers don't seem to go?

If leader + all helpers are on the same PC, LocalChat should work in mode 1 or 2.
You should have all the expressions in the running script. and LocalChat will communicate between local d2 windows.
