### ISSUE TITLE
Char Viewer to add Stash and Inventory Viewer

### ISSUE THREAD

**Issue by franva** [blizzhackers/kolbot#142]
Appreciate for the great job for this project.

May I request a feature which I saw in other bot a couple of years ago?

The feature is basically a Stash and Inventory Viewer.

With this feature, when users click a Char in Char Viewer, we are not only able to see what items this char has, but also it's inventory and Stash spaces with items and their positions, so basically it's same as opening the game and viewing your inventory and stash.

The benefits of having this feature is, users will be able to know how many spaces(grids) their existing mule chars have and thus they are manually put items into those available slots rather than keeping creating new chars while leaving many mule chars half stored, it is such a waste.

**Comment by Sylvm** [comment]
Hi, there is already, press "-" and you will have it in the char viewer tab. 
Pressing "6" will output to the char activity default tab.

**Comment by franva** [comment]
@Sylvm  thanks for reply. 

Sorry , I didn't mean the text logging for what the char has. The text logging gives you an idea what items you have on that char, but you have no idea how much space do you have in your Stash and Inventory.

![image](https://user-images.githubusercontent.com/5151146/88469026-5e41bb00-cf2f-11ea-8b60-6eeb1b040428.png)
I'd like something like this.

**Comment by Sylvm** [comment]
I will need more knowledge of the code. I have been learning for a while but I'm not sure how I can pull that off. 
Is someone willing to teach me a little more about the "GameAction", "Misc.logItem()", "D2Bot.printToItemLog" and '"sendCopyData" can't find the code of this one :(.

**Comment by franva** [comment]
@Sylvm  I'm learning as well. The syntax looks like JavaScript, but there are some files with extension name .dbj which still look like javascript, does anyone know what is the language of .dbj?

**Comment by mf022** [comment]
> does anyone know what is the language of .dbj?

most of the files from <https://github.com/blizzhackers/kolbot/tree/master/d2bs/kolbot> are written in Javascript (*.js, *.dbj,*.dbl, and also pickit *.nip), but there can be some differences regarding the level of coding.

**Comment by mf022** [comment]
> "GameAction",

it is used the starter script for [limedrop](https://github.com/blizzhackers/documentation/tree/master/limedrop#limedrop-guide).



> "Misc.logItem()"

logItem function from Misc.js [lines 1363-1593](https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/common/Misc.js#L1363-L1593).



> "D2Bot.printToItemLog"

it's a command for D2Bot.exe, found on on previous Misc.js line 1590



> "sendCopyData"

communication between windows.
