### ISSUE TITLE
New Functionality: Add key to skip the current task

### ISSUE THREAD

**Issue by franva** [blizzhackers/kolbot#146]
Say when 2 bots plays in 1 room, the bot A has reached to act3, but the bot B is still doing ACT2 task.

I would like to request a function which is triggered by a key press to skip the current task.

**Comment by fabio1999ita** [comment]
you can add it, like by text in chat

**Comment by franva** [comment]
you mean just type: next in the chat?

**Comment by mayphilc** [comment]
This was a feature in Etal that I'd love to see in kolbot

**Comment by Ognyan1987** [comment]
> This was a feature in Etal that I'd love to see in kolbot

yeah etal uses `Pgup` , `Pgdown` keyboard buttons and with them u can tell  your bot which script to start while he is ingame

**Comment by mf022** [comment]
> Say when 2 bots plays in 1 room, the bot A has reached to act3, but the bot B is still doing ACT2 task.
> 
> I would like to request a function which is triggered by a key press to skip the current task.

maybe there are other things that could be implemented to syncronize a MF team.
pressing a key .. it looks like you wanna play manually.



> This was a feature in Etal that I'd love to see in kolbot

d2nt was written in other way, and that's why you could change the area scripts.

kolbot's boss/area scripts are functions.
