### ISSUE TITLE
Tcp/ip sonic

### ISSUE THREAD

**Issue by ShootterDev** [blizzhackers/kolbot#149]
Would try Sonic in TCP/IP but don't found anything about it... 
Don't know if its here to post something like?

Did someone try in Solo or TCP/IP game? cause i don't found any help about it... yes im ban on ladder for 1.8M sec so i have time to spend on edit some script to be perf in next ladder :p

So if you have any info about it try to share :)

**Comment by mf022** [comment]
- set the *Host TCP/IP Game* in the mode of a cloned profile. 
- maybe you should edit a new starter script D2BotsonicTCP.dbj, after you'll make a comparison between the default and the [TCP Host starter file](https://raw.githubusercontent.com/blizzhackers/documentation/master/kolbot/custom-scripts/D2BotTcpIpHost.dbj).
