### ISSUE TITLE
Bot keeping wrong item

### ISSUE THREAD

**Issue by arrickd** [blizzhackers/kolbot#150]
My bot keeps a lot of 40 ed jewels and others single stat jewels when it shouldn't.

For instance the bot kept a jewel with 64 defense and no other mods.

The line reference is:
**[Name] == Jewel && [Quality] == Magic # [plusdefense] >= 64 && [itemreqpercent] >= -15**

**Comment by Sylvm** [comment]
Looks like a simple mistake :
`[itemreqpercent] >= -15`
Should be
`[itemreqpercent] <= -15`
'> -15' means 0 is a correct condition.

**Comment by arrickd** [comment]
> Looks like a simple mistake :
> `[itemreqpercent] >= -15`
> Should be
> `[itemreqpercent] <= -15`
> '> -15' means 0 is a correct condition.

That mistake is on almost 200 lines of my pickit! thank you!
