### ISSUE TITLE
Rerolled runeword although it shouldnt

### ISSUE THREAD

**Issue by Roycinger** [blizzhackers/kolbot#153]
Hi,
I had a Call to Arms runeword flail in my stash.

In my char's config I set:
`Config.Runewords.push([Runeword.CallToArms, "Flail", Roll.NonEth]);`
`Config.KeepRunewords.push("[type] == weapon || [type] == armor");`

From my understanding this should keep all runewords made in a weapon or armor.
Then I found this in my d2bs console:
Rerolling runeword: Call to Arms Flail

So I had a look and kolbot unsocketed the flail (not creating a new CTA).

Shouldnt the Config.KeepRunewords line prevent kolbot from rerolling?

**Comment by DarkHorseDre** [comment]
hmm.. not sure - try including a line for stats like in the example lines in config - yes this means you prolly need a line for weps and a line for armour..

**Comment by mf022** [comment]
> `Config.KeepRunewords.push("[type] == weapon || [type] == armor");`
> 
> From my understanding this should keep all runewords made in a weapon or armor.

that line should be there only for rerolling, if you set conditions for keeping it. 
anyway you added extra quotes, maybe that was the wrong part.
```
Config.KeepRunewords.push([type] == sword || [type] == flail # plusskillbattlecommand] >= 3 && [plusskillbattleorders] >=3");
```
