### ISSUE TITLE
Mule refresh

### ISSUE THREAD

**Issue by Archon-** [blizzhackers/kolbot#154]
Sometimes my mules got expired because not trading that often. Is there any mechanism to refresh them? Did anyone came with any solution? If not I may write some simple 'Entry Script' that simply itterate through all mules on selected realm and refresh them when they are expired or closed to.

**Comment by paul-arnold** [comment]
D2BotMuleLog.dbj

**Comment by Archon-** [comment]
Ahh didn't know that one. Thx @paul-arnold Closing then.
