### ISSUE TITLE
Autoequip Tier Question

### ISSUE THREAD

**Issue by Blacknight909** [blizzhackers/kolbot#155]
Is there a way to make the autoequip feature use the below in the autoequip pickit?

This is from the Sonic autoequip. How can I use this part to make the bot upgrade tier items as it levels? 

**[tier] == ((item.getStatEx(39) + item.getStatEx(41) + item.getStatEx(43)) * 100) + /*defense*/(item.getStatEx(31) * 10)**

If i try to use I always get item.getstatex is not a function.

Any help greatly appreciated, thanks in advance.

**Comment by trickyzerg17** [comment]
I fixed this issue a while ago, so my memory is a little vague.

The basic problem here is that NTItemParser converts lines from pickit files to lower case (which makes sense I think) … but JavaScript is case sensitive.

So, one option is to make NTItemParser fix the capitalization before it determines the tier for an item.

As an example, you want something along the lines of 

			case "tier":
				try {
					let the_string = p_section[i].split("==")[1]; // scuppy17

					// replace every instance of getstatex with getStatEx
					the_string = the_string.replace(/getstatex/g, "getStatEx");
					
					// build a function
					p_result[2][keyword.charAt(0).toUpperCase() + keyword.slice(1)] = (new Function('return function(item) { return ' + the_string + ';}')).call(null); 
				} catch(e) {
					Misc.errorReport("ÿc1Pickit Tier ("+keyword+") error! Line # ÿc2" + info.line + " ÿc1Entry: ÿc0" + info.string + " (" + info.file + ") Error message: " + e.message);
				}
				break;

around line 615 in NTItemParser (maybe not exactly this line, I have various other custom things in my current version of the code).

If I remember correctly, Sonic is doing something along the same lines.

**Comment by Blacknight909** [comment]
Tried this and still couldn't get to work. Thanks for trying.
