### ISSUE TITLE
Error message: missing ; before statement Trigger 

### ISSUE THREAD

**Issue by Gir3lla** [blizzhackers/kolbot#156]
Where is the error?

[Type] == Circlet && [Quality] == magic # [normaldamagereduction] == 25] && [maxmana] >= 100
[Type] == Circlet && [Quality] == magic # [normaldamagereduction] == 25] && [Sockets] == 3
[Name] == pavise && [Quality] == unique # [EnhancedDefense] >= 180 && [fireresist] >= 20 && [magicdamagereduction] == 18 [normaldamagereduction] == 16

**Comment by Nos24** [comment]
Remove "]" after 25

**Comment by Gir3lla** [comment]
[Name] == pavise && [Quality] == unique # [EnhancedDefense] >= 180 && [fireresist] >= 20 && [magicdamagereduction] == 18 [normaldamagereduction] == 16

The error is: Error message: identifier starts immediately after numeric literal Trigger item: Pavese

**Comment by Sylvm** [comment]
[magicdamagereduction] == 18 **&&** [normaldamagereduction] == 16

**Comment by Gir3lla** [comment]
Ty <3 al lot!
