### ISSUE TITLE
Necromancer bot keep crashing

### ISSUE THREAD

**Issue by franva** [blizzhackers/kolbot#157]
![image](https://user-images.githubusercontent.com/5151146/91553817-597a8780-e971-11ea-863d-39955d98d5de.png)

Starting from today, my necromancer bot keeps crashing once it entered game rooms.

I tried to re-start my computer, but no luck.

Do we have any log files which logging crashing information?

Could anyone help please?

**Comment by Sylvm** [comment]
Hello, 

Why do you have no script executing ?

Can you tell us the last changes you have made to scripts or char config (your necro) ?

**Comment by franva** [comment]
hi @Sylvm 
what do you mean: "no script executing" ?

a week ago I uncommented a cubing code in necro profile, but it didn't cause crashing.
The crashing started yesterday, and then today so far so good.

Do we have any log files which logging crashing events?

I have checked ScriptErrorLog.txt and profile-<datetime>.txt log, none of those files recording crashing profile events.
Probably the crashing events are missed, not recorded.

**Comment by Sylvm** [comment]
To see the logs of your character you have to go to "d2bs/logs/d2bs-<profilename>-<date>.log"

I said you have no script executing based on this line : "Crash Info: Script: No entry Area: Harrogath"
The script is a bot script like d2bs/kolbot/libs/bots/Andariel.js for example. 

The problem is gone ?

**Comment by franva** [comment]
thanks for the explanation.

The problem is gone after I changed my Invite mode to accept only for the bot which uses D2Follower.

So I guess that's the cause and fix.

Cheers :)

**Comment by Sylvm** [comment]
My pleasure.

**Comment by franva** [comment]
hi @Sylvm could you please comment on this issue? 
https://github.com/blizzhackers/kolbot/issues/159

thanks
