### ISSUE TITLE
No gold picked up in manual play with BotMap

### ISSUE THREAD

**Issue by SirAlexTheGreat** [blizzhackers/kolbot#158]
I have tried everything now, I must be missing something..

Config:
Config.PickitFiles.push("LadderReset.nip");
//Config.PickitFiles.push("LLD.nip");
Config.PickRange = 100; // Pick radius
Config.FastPick = false; // Check and pick items between attacks
Config.ManualPlayPick = true; // If set to true and D2BotMap entry script is used, will enable picking in manual play.

pickit:
[name] == gold # [gold] >= 1

Entry script is BotMap. It picks up potons and items (Using LadderReset as indicated in the onscreen text) but doesnt pick up any gold, I have experimented with different gold values, turning useraddon on and off (what does this actually do?)

Im at my wits end..
Can someone help me?

**Comment by Sylvm** [comment]
I've done some experimental testing, it looks like gold is excluded.
The Pickit function that is called is `Pickit.fastPick();` 
If you want to enable the picking of gold you have to delete `&& item.itemType !== 4` from line 614 : 
`if (item && (item.mode === 3 || item.mode === 5) && (Town.ignoredItemTypes.indexOf(item.itemType) === -1 || (item.itemType >= 76 && item.itemType <= 78)) **_&& item.itemType !== 4_** && getDistance(me, item) <= Config.PickRange) {` 
from the file Pickit.js (D2BD>kolbot>libs>common).
