### ISSUE TITLE
Is it possible to use Javascript fetch api in the code

### ISSUE THREAD

**Issue by franva** [blizzhackers/kolbot#159]
I would like to trigger my AWS lambda function once an event happens.

I am thinking of using fetch api in the kolbot.

Is it possible to do so?

**Comment by Sylvm** [comment]
I think it is possible, I haven't tested myself but I guess you refer to something like d2bs%2Fkolbot%2Ftools%2FTownChicken.js

**Comment by franva** [comment]
hi @Sylvm  I wanted to call a web api endpoint from the Kolbot using [fetch api](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) directly like this:

```
const url = "https://www.netlify.app/.netlify/functions/alertme?dc=diablowalkstheearth";
	
		fetch(url, {
			method: "GET",
			headers: {
			  "Content-Type": "application/json;charset=utf-8",
			},
			referrerPolicy: "no-referrer",
		})
		.then(response =>D2Bot.printToConsole("DC Monitor has been notified"))
		.catch(err => D2Bot.printToConsole("Failed to notify DC Monitor " + JSON.stringify(err)));)
```

I have tried but it error out.

Then I tried the old fashion which uses [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest)

```
	var xhttp = new XMLHttpRequest();
	xhttp.responseType = "text";
	xhttp.onreadystatechange = function() {
		
		const status = xhttp.status;
		if (status === 0 || xhttp.readyState === XMLHttpRequest.DONE && (status >= 200 && status < 400)) { //XMLHttpRequest.DONE === 4
		   // Typical action to be performed when the document is ready:
		   D2Bot.printToConsole("DC Monitor has been notified");
		   D2Bot.printToConsole(xhttp.responseText);
		} else {
			D2Bot.printToConsole("Failed to notify DC Monitor subscribers");
			D2Bot.printToConsole("Error: " + xhttp.responseText); // can also use xhttp.response
		}
	};
	xhttp.open("GET", url);
	xhttp.send();
``` 

again it error out without error information.

**Comment by Sylvm** [comment]
Did you solve your problem ?
Using the fetch command : 
Have you tried to check the response ? 
Do you ever get a Response.ok ?

From the link you gave the issue is not answered.

**Comment by franva** [comment]
@Sylvm no luck. I found a few of approaches , e.g. HTTP class in the modules folder, jQuery.ajax(), XmlHttprequest and Fetch, none of them work. The moment the program hits the line of the http request code, it errors out.

**Comment by ross-weir** [comment]
> @Sylvm no luck. I found a few of approaches , e.g. HTTP class in the modules folder, jQuery.ajax(), XmlHttprequest and Fetch, none of them work. The moment the program hits the line of the http request code, it errors out.

They don't exist, the D2BS engine hasn't implemented them. The closest you will get is using the JS HTTP class which is a wrapper around raw C sockets exposed by D2BS.

**Comment by franva** [comment]
@ross-weir it's highly appreciated if you could provide a link to that API 😁

**Comment by ross-weir** [comment]
It's just the one you mentioned in your comment: https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/modules/HTTP.js

**Comment by franva** [comment]
thanks @ross-weir  I had tried it, but no luck. I will give it another try.
