### ISSUE TITLE
Missing 

### ISSUE THREAD

**Issue by franva** [blizzhackers/kolbot#161]
![image](https://user-images.githubusercontent.com/5151146/91918997-ea51ba00-ed07-11ea-810b-21cd8f3bdc63.png)

my script crashed and saw this error pop-up asking to view my exceptions.log file.

Searched and cannot find it.

Is this a bug?

**Comment by Sylvm** [comment]
This file is in < Folder path >\D2BS\logs\

**Comment by franva** [comment]
Thanks @Sylvm the logs under >\D2BS\logs are normal bot logs , not the crashing logs.

**Comment by DarkHorseDre** [comment]
\kolbot\logs\exceptions.log
