### ISSUE TITLE
Kolbot stable release , no -3dfx glide support yet

### ISSUE THREAD

**Issue by Ognyan1987** [blizzhackers/kolbot#170]
The Latest Kolbot stable release does not support  glide wrapper -3dfx yet  , game crashes some seconds after u load it throught the manager or before  u create or enter a game! 

-3dfx glide actually makes the game graphic much more smooth like a minor remaster , u can use the Ingame Perspective settings and much more  , which settings  by default without the  -3dfx glide do not work  at all

You can even Stream your D2 window or make video over it without the need to cut it so the video recording to catch it like it is required to be done now !

**Comment by Ognyan1987** [comment]
Bump

**Comment by mf022** [comment]
@noah can you check this
same issue https://d2bot.discourse.group/t/d2bot-running-on-linux-in-wine/1227
