### ISSUE TITLE
window has unexpectedly exited....starting profile 

### ISSUE THREAD

**Issue by axalstash** [blizzhackers/kolbot#171]
been using kolbot for a while now and not haven issues with other profiles, but when i made one for my hdin to follow another one i get this proble... widow has unexpectedly exited....starting profile ........ but only when i use d2botfollow.dbj ... if i put back on leader script it runs just fine.... any ideas

**Comment by axalstash** [comment]
nvm guys lol i figured it out moments after i posted lol....
this is what i  had   
 var JoinSettings = {
	"light": ["ele"]
        "neco": ["hdinner"]

and this is the fix lol
var JoinSettings = {
	"light": ["ele"],
        "neco": ["hdinner"]

**Comment by casualBotter** [comment]
You have probably messed up the syntax in your d2botfollow file. Undo all the changes you've made or ger a fresh copy of that file and try again make sure the syntax is all correct

**Comment by gtoilet** [comment]
you didnt have the ,
to enable the 2nd join setting
