### ISSUE TITLE
no attack script???

### ISSUE THREAD

**Issue by axalstash** [blizzhackers/kolbot#174]
this might sound weird but is there a spot where i can set a char not to attack monsters.... i just want it to open chest ...
i tried to just turn attacks off but char just teles around a lot.... took 5 min just to get through the pit....

**Comment by gtoilet** [comment]
did you try -1 on attack configs
that -1 disables attacking

**Comment by axalstash** [comment]
well when i first did it i just put  // in front of attacks .... which made bot tele alot but did clear hole area just took 5 min for pit

when i did -1 instead bot didnt clear area just teled through it / an like in crypt it walked in opened things in pick distance and then left ...did not clear the whole thing

**Comment by axalstash** [comment]
> well when i first did it i just put // in front of attacks .... which made bot tele alot but did clear hole area just took 5 min for pit
> 
like tower lvl 1 bot opened stuff on the way to lvl 2 ...didnt clear whole floor

**Comment by DarkHorseDre** [comment]
> set a char not to attack monsters.... i just want it to open chest 

this is what chestmania does

but it seems youre saying two things at once - what do you specifically want the bot to do?

**Comment by axalstash** [comment]
> > set a char not to attack monsters.... i just want it to open chest
> 
> this is what chestmania does
> 
> but it seems youre saying two things at once - what do you specifically want the bot to do?

i want it to open all chest, dead bodyies, everything lol from act1 to act 5 ....

**Comment by DarkHorseDre** [comment]
ok so I said chestmania does this - have you tried looking into that at all?

set config.openchests 2; to expand the amount of items it opens - you can edit the list in misc.js

**Comment by axalstash** [comment]
> ok so I said chestmania does this - have you tried looking into that at all?
> 
> set config.openchests 2; to expand the amount of items it opens - you can edit the list in misc.js

ill look into it ... i thought it only opened up the gold chests/high itemlvl ones

**Comment by axalstash** [comment]
yes that is kinda what i want but it dose not open everything in the area. it opens tihng on the way to the "gold" chest then moves on

**Comment by mf022** [comment]
if you set in character config:
```
	Config.OpenChests = 2; // Open chests. Controls key buying.
```
according to line 17 from ChestMania <https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/bots/ChestMania.js#L17>, the bot should execute Misc.openChestInArea function, but it has in line 990 <https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/common/Misc.js#L990> the execution of Misc.openChests with 20th range.
