### ISSUE TITLE
ChestMania not working right!!

### ISSUE THREAD

**Issue by Sune10** [blizzhackers/kolbot#175]
I wonder why my sorc just open chest on act 1. I think it might be because i moved some lines in the Boss/area scripts from one act to another but it doesn´t make any sense to me. I attach my config char file to get some support about this because it is working fine with my hammerdin but not with my sorc so i guess is becuase i moved lines in the soso one.
[Sorceress.Coconutsune.txt](https://github.com/blizzhackers/kolbot/files/5341652/Sorceress.Coconutsune.txt)

	Scripts.ChestMania = true; // Open chests in configured areas. See sdk/areas.txt
		Config.ChestMania.**Act1 = [13, 14, 15, 16, 18, 19, 21, 22, 23, 24, 25]**;// List of act 1 areas to open chests in
		Config.ChestMania.**Act2 = [55, 59, 65, 66, 67, 68, 69, 70, 71, 72]**; // List of act 2 areas to open chests in
		Config.ChestMania.**Act3 = [79, 80, 81, 92, 93, 84, 85, 90]**; // List of act 3 areas to open chests in
		Config.ChestMania.**Act4 = [];** // List of act 4 areas to open chests in
		Config.ChestMania.**Act5 = [115, 116, 119, 125, 126, 127]**; // List of act 5 areas to open chests in
	Scripts.ClearAnyArea = false; // Clear any area. Uses Config.ClearType to determine which type of monsters to kill.
		Config.ClearAnyArea.AreaList = []; // List of area ids to clear. See sdk/areas.txt

**Comment by Ulryx** [comment]
May want to start by either adding 107 back into the zone id for act 4, or commenting it out. If you don't want to run it, don't leave it blank, comment it out.

Here is mine if you want to paste it in and see if it works:

`Scripts.ChestMania = true; // Open chests in configured areas. See sdk/areas.txt
		//Config.ChestMania.Act1 = [13, 14, 15, 16, 18, 19]; // List of act 1 areas to open chests in
		//Config.ChestMania.Act2 = [55, 59, 65, 66, 67, 68, 69, 70, 71, 72]; // List of act 2 areas to open chests in
		Config.ChestMania.Act3 = [79, 80, 81, 92, 93, 84, 85, 90]; // List of act 3 areas to open chests in
		//Config.ChestMania.Act4 = [107]; // List of act 4 areas to open chests in
		//Config.ChestMania.Act5 = [115, 116, 119, 125, 126, 127]; // List of act 5 areas to open chests in`

**Comment by Sune10** [comment]
> May want to start by either adding 107 back into the zone id for act 4, or commenting it out. If you don't want to run it, don't leave it blank, comment it out.
> 
> Here is mine if you want to paste it in and see if it works:
> 
> > Scripts.ChestMania = true; // Open chests in configured areas. See sdk/areas.txt
> > //Config.ChestMania.Act1 = [13, 14, 15, 16, 18, 19]; // List of act 1 areas to open chests in
> > //Config.ChestMania.Act2 = [55, 59, 65, 66, 67, 68, 69, 70, 71, 72]; // List of act 2 areas to open chests in
> > Config.ChestMania.Act3 = [79, 80, 81, 92, 93, 84, 85, 90]; // List of act 3 areas to open chests in
> > //Config.ChestMania.Act4 = [107]; // List of act 4 areas to open chests in
> > //Config.ChestMania.Act5 = [115, 116, 119, 125, 126, 127]; // List of act 5 areas to open chests in

Thanks for your answer. What i mean is that i want to run every single chest but this char only gets the act 1 ones while i want all of them from act 1 to act 5. Instead my pala do open every act chests so i dont know where is the problem here.

**Comment by mf022** [comment]
> Scripts.ChestMania = true; // Open chests in configured areas. See sdk/areas.txt
> 	Config.ChestMania.**Act1 = [13, 14, 15, 16, 18, 19, 21, 22, 23, 24, 25]**;// List of act 1 areas to open chests in
> 	Config.ChestMania.**Act2 = [55, 59, 65, 66, 67, 68, 69, 70, 71, 72]**; // List of act 2 areas to open chests in
> 	Config.ChestMania.**Act3 = [79, 80, 81, 92, 93, 84, 85, 90]**; // List of act 3 areas to open chests in
> 	Config.ChestMania.**Act4 = [];** // List of act 4 areas to open chests in
> 	Config.ChestMania.**Act5 = [115, 116, 119, 125, 126, 127]**; // List of act 5 areas to open chests in

did you added the double * only to bold the text here, or these are also in your char config?
