### ISSUE TITLE
AutoEquip stashing instead of selling nonupgrades

### ISSUE THREAD

**Issue by Ulryx** [blizzhackers/kolbot#178]
I've used a few forks where the auto equip seemed to simply vendor things that weren't upgrades instead of stashing them. 

Is there something I'm missing to have it handle this? It seems as if it's using the autoequip as a straight pickit instead of an equip template also.

**Comment by Kesom** [comment]
Refering to #147 
Kolbot treats items with tier >= 100 as valuables. Anything obsolete but higher than 100 gets stashed. Anything below 100 is treated as trash and sold/dropped.
