### ISSUE TITLE
i am getting a looping error help plz 

### ISSUE THREAD

**Issue by xlxprobyxlx** [blizzhackers/kolbot#179]
Was starting just fine! All of a sudden, games crashes. Now, I start my bots profile, and it doesn't open d2 at all. Instead, it displays the error in console indefinitely.

I have done:

reinstalled diablo 2 and on a different key

I'm not sure if this matters, but I didn't delete the old bot folder off my desktop prior to settings up the new one.

Any ideas or solutions to what is going on?

Thanks in advance for the help!

**Comment by Ognyan1987** [comment]
Did your bot ran fine before that ?
Set d2bs manager to compability mode of Windows 7 and to run as admin ?
Make sure your diablo II folder and game.exe is on patch 1.14d!
Remove the compability of the game exe , but only set to run as admin!
Perform a Diablo II maintanance!

**Comment by mf022** [comment]
> Now, I start my bots profile, and it doesn't open d2 at all. Instead, it displays the error in console indefinitely.

on windows 10 you should run d2 only in window mode (-w), otherwise it crashes.
maybe you missed this or other settings
