### ISSUE TITLE
Failed to kill x

### ISSUE THREAD

**Issue by DarkHorseDre** [blizzhackers/kolbot#181]
Hi all,

So I've been getting this issue and not sure why - can be with various bosses but often Andy.

I'm sure Andy is there and not sure why it happens - I started tagging the location of me and her and seems she is alive (why else would she have a location?)!

`14:42:21 (SPtester-3) me.x/y: 22549,9520. target x/y: 22536,9530`
`14:42:21 (SPtester-3)  Error in Andariel (attack.js #306) Failed to kill an evil force`

When I locate those coords they are not far apart - only thing I can tell is there is a pillar in the line of sight.

This is the code in attack.js that is fired when we get this message:
```js
if (target.hp > 0 && target.mode !== 0 && target.mode !== 12) {
  D2Bot.printToConsole("me.x/y: "+me.x + me.y + ". target x/y: " + target.x + target.y, 8); //dhd added
  throw new Error("Failed to kill " + target.name + errorInfo);
}
```
Any ideas?

![image](https://user-images.githubusercontent.com/41862641/97893534-52814400-1d29-11eb-9dd0-8484ca9481f3.png)

**Comment by gtoilet** [comment]
is it when she teles there or durring the fight?
if its right when she teles there maby make her tele closer to where andy spawns
if its durring the fight maby make her attack range closer

**Comment by DarkHorseDre** [comment]
yoyoo

no idea - but as she got there and the code says if shes still alive, it must be during fight?

the range is default for the skills (fireball & meteor) - so trying to figure out the root cause to change in the bot (only started recently on this bh code)

**Comment by DarkHorseDre** [comment]
@mf022 hey bro, has this been solved/explained? I don't think I got an answer to this?

**Comment by Amendment** [comment]
You have to go to C:\Users\*You*\Documents\GitHub\kolbot\d2bs\kolbot\libs\common\Config.js and change MaxAttackCount to something more reasonable (9999 maybe), but need to make sure you have other settings correct so you don't stay in an attack forever. I had to bump my # up b/c I've been running Hell Nih with a cold sorc and the demons blocking for him absorb a lot of the untimed attacks.

**Comment by DarkHorseDre** [comment]
> You have to go to C:\Users*You*\Documents\GitHub\kolbot\d2bs\kolbot\libs\common\Config.js and change MaxAttackCount to something more reasonable (9999 maybe), but need to make sure you have other settings correct so you don't stay in an attack forever. I had to bump my # up b/c I've been running Hell Nih with a cold sorc and the demons blocking for him absorb a lot of the untimed attacks.

This is not the issue I reported above.  Your advice relates to when the maximum number of attacks are exceeded, my issue never saw more than a few attacks, if any.

**Comment by theBGuy** [comment]
I assume the Attack skills were set properly? I know I've seen people have an issue with failing to kill when the bot is trying to use a skill it doesn't have. Other than that, do you still have this issue? If so can you provide more information. Log info during the time would be helpful

**Comment by DarkHorseDre** [comment]
@theBGuy yeah I bot does/used to(?) disconnect when skill character doesn't have is cast.

The picture I've tried to paint is of 4 identical bots (their files were copied in SP) and running the same config (shared group config not individual ones) and running same bosses.  This error happens rarely, meaning most runs are successful (So can't be attack config related?) and not about max attacks (as this can happen at the start of the attack).  Also there are no errors in the log except the one posted.

I haven't ran this since around the time of posting, but this looks like the last attack config i had:
```js
	Config.AttackSkill[0] = 47; // Preattack skill.
	Config.AttackSkill[1] = 56; // Primary skill to bosses.
	Config.AttackSkill[2] = 47; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[1] is untimed skill.
	Config.AttackSkill[3] = 56; // Primary skill to others.
	Config.AttackSkill[4] = 47; // Primary untimed skill to others. Keep at -1 if Config.AttackSkill[3] is untimed skill.
	Config.AttackSkill[5] = 64; // Secondary skill if monster is immune to primary.
	Config.AttackSkill[6] = 45; // Secondary untimed skill if monster is immune to primary untimed.

	// Low mana skills - these will be used if main skills can't be cast.
	Config.LowManaSkill[0] = -1; // Timed low mana skill.
	Config.LowManaSkill[1] = 45; // Untimed low mana skill.
```

like i said, this works nearly all the time - i note that meteor is primary skill for others - that a problem?

I also have cold and fire immunes skipped, but don't think this works (then at least):
```js
	Config.SkipImmune = ["fire and cold"];
```

**Comment by theBGuy** [comment]
change your attack.kill to match this, I just started up a single player bot and having it run andy non stop to see if I can replicate the issue but would appreciate if you could as well. What I changed will print to console once everytime you start to attack andy

```
let once = false;

		while (attackCount < Config.MaxAttackCount && this.checkMonster(target) && this.skipCheck(target)) {
			Misc.townCheck();

			if (!target || !copyUnit(target).x) { // Check if unit got invalidated, happens if necro raises a skeleton from the boss's corpse.
				target = getUnit(1, -1, -1, gid);

				if (!target) {
					break;
				}
			}

			if (Config.Dodge && me.hp * 100 / me.hpmax <= Config.DodgeHP) {
				this.deploy(target, Config.DodgeRange, 5, 9);
			}

			if (Config.MFSwitchPercent && target.hp / 128 * 100 < Config.MFSwitchPercent) {
				this.weaponSwitch(this.getPrimarySlot() ^ 1);
			}

			if (attackCount > 0 && attackCount % 15 === 0 && Skill.getRange(Config.AttackSkill[1]) < 4) {
				Packet.flash(me.gid);
			}

			result = ClassAttack.doAttack(target, attackCount % 15 === 0);

			if (result === 0) {
				if (retry++ > 3) {
					errorInfo = " (doAttack failed)";

					break;
				}

				Packet.flash(me.gid);
			} else if (result === 2) {
				errorInfo = " (No valid attack skills)";

				break;
			} else {
				retry = 0;
			}

			if (!once && target.classid === sdk.monsters.Andariel) {
				D2Bot.printToConsole("Attacking andy, last attack was: " + (result === 1 ? "sucessful " : "Failure ") + "andy is " + (target.dead ? "dead " : "alive ") + "current distance: " + target.distance);
				once = true;
			}

			attackCount += 1;
		}
```

**Comment by theBGuy** [comment]
Please let me know if you see the issue, I've run 1000 runs single player without seeing it once

**Comment by theBGuy** [comment]
Please let me know if you see the issue, I've run 1000 runs single player without seeing it once

**Comment by theBGuy** [comment]
This should be fixed now
