### ISSUE TITLE
PickIt special affixes

### ISSUE THREAD

**Issue by TrazhCant** [blizzhackers/kolbot#183]
Is it possible to check for "Prevent Monster Heal" ([itempreventheal]) or "Slain Monsters Rest In Peace" ([itemrestinpeace])? I have scoured Google and all documentation here (which is fantastic, btw), but I was unable to determine how these might be checked. The vast majority of item stats are quantified in whole numbers, but these 2 stats either exist or they don't on a given item, so I'm not sure what value to have pickit check for them (i.e. most other item stats are checked with </>/= a number). Would they possibly be checked with true/false values instead of numbers? Like [itemrestinpeace] == true ?  or something?  Thanks in advance.

**Comment by DarkHorseDre** [comment]
I'm not sure but dont see other attributes having true/false values.

Did you try `>=1`?

**Comment by TrazhCant** [comment]
I haven't.  I'll try that with Hwanin's belt and post back the result.  If that works, I'll assume the same should be true for Nature's Peace (Slain Monsters Rest in Peace).

**Comment by DarkHorseDre** [comment]
cool - but why do you want to use those attributes?  NP for example can be found using other stats

**Comment by TrazhCant** [comment]
> cool - but why do you want to use those attributes? NP for example can be found using other stats

True and I used the other stats on NP to search for it.  It's simply for a matter of preference, and doesn't prevent monster heal roll on rares?  I just want to know how to use these attributes if I choose.

I tested [itempreventheal] >= 1 and dropped a Hwanin's belt and it did not pick it up.  So that doesn't seem to work.

**Comment by DarkHorseDre** [comment]
> I just want to know how to use these attributes if I choose.

ah fair enough

ok so this may be one of the few aliases that need special attention - not sure if it is usable or if something needs to be done.. hitup the blizzhackers kolbot discord group if you dont get anything here (also, the original/stable git has more views for issues  https://github.com/kolton/d2bot-with-kolbot/issues)

**Comment by TrazhCant** [comment]
Will do, appreciate the input! :)

**Comment by DarkHorseDre** [comment]
np

As for rares - I dont think so, but you can check the affix list on Arreat summit for rares and magic

**Comment by TrazhCant** [comment]
> As for rares - I dont think so, but you can check the affix list on Arreat summit for rares and magic

Affix "Vileness" (suffix) can appear on rare melee weapons.  Prevents monster heal.

**Comment by DarkHorseDre** [comment]
Well I was talking about restinpeace, but I dont need to know :)
Was just letting you know you can check them on arreat
