### ISSUE TITLE
drop from invertory // drop from stash ...

### ISSUE THREAD

**Issue by sunproc88** [blizzhackers/kolbot#184]
Hello,

i did this 1-2 years ago
my secren looked like this photo below
but I forgot how it's done.
can anyone help me to do it again ?

https://i.ibb.co/1Jx1NcC/Screenshot-3.png

**Comment by laztheripper** [comment]
http://jobs.harrogath.com/images-jobs/Manual.js

Welcome back

**Comment by sunproc88** [comment]
thank you so much for sending this file to me
that is helping me alot
i hope you are gonna do better works
goodluck have fun :D
________________________________
Gönderen: LAZ <notifications@github.com>
Gönderildi: 12 Kasım 2020 Perşembe 00:32
Kime: blizzhackers/kolbot <kolbot@noreply.github.com>
Bilgi: sunproc88 <wxrot103@hotmail.com>; Author <author@noreply.github.com>
Konu: Re: [blizzhackers/kolbot] drop from invertory // drop from stash ... (#184)


http://jobs.harrogath.com/images-jobs/Manual.js

Welcome back
