### ISSUE TITLE
How to click hostile button?

### ISSUE THREAD

**Issue by thaiboxer** [blizzhackers/kolbot#185]
If I find in game people from my blacklist I want bot to click hostile button near them. Is it possible and how? Thank you.

**Comment by mf022** [comment]
you can check the Anti-hostile options from the char config <https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/config/_BaseConfigFile.js#L593-L598> and also the lines <https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/config/_BaseConfigFile.js#L558-L559>

additional info:
- <https://d2bot.discourse.group/t/hostile-shitlist-on-join/654>
- <https://d2bot.discourse.group/t/anti-hostile-help-please/1266>
