### ISSUE TITLE
Adding a game description

### ISSUE THREAD

**Issue by Rakkah** [blizzhackers/kolbot#189]
In which file can I add a function to add game description for my games?

**Comment by mf022** [comment]
If you want to add the description of the game (optional) when you create a game, like you could do it manually in d2 window, kolbot doesn't have this feature implemented.

according to the d2nt file [controlInfo.ntl](https://github.com/Project-Etal/D2Etal/blob/master/D2Etal/scripts/libs/controlInfo.ntl#L153), the coordinates should be (4, 427, 243, 300, 12) , but [kolbot's OOG.js](https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/OOG.js) doesn't have it.
