### ISSUE TITLE
I'm trying to setup a cbaal leech profile

### ISSUE THREAD

**Issue by LunaTonks** [blizzhackers/kolbot#191]
No idea what I did wrong.  Wanted to set it up on sorc since if she dies it won't be a big deal before moving to sin.  I login in and sit stagnant.  If I manually join game, then I won't join party or anything. 

I do leave when the leader leaves... So I got something right.  I don't want to pick anything up RN or attack, just leech.  But I do wanna change the pickit options later on.

**Comment by Snoopy187** [comment]
which cbaal script are you using? for chaos Wakka is the script u want to use to leech. They still stand back while other characters kill monsters or u can use diablohelper if u choose to participate in killing the monsters. For baal use the Scripts.BaalAssistant and set helper to false

**Comment by LunaTonks** [comment]
I'm using baal assistant but in the sorceress.charactername script

**Comment by Snoopy187** [comment]
make sure Config.BaalAssistant.Helper is set to false and you can turn off teleport if you'd like in the panther.js file (Warning: if you turn if off in this script it will turn off teleport for all characters)

**Comment by LunaTonks** [comment]
> make sure Config.BaalAssistant.Helper is set to false and you can turn off teleport if you'd like in the panther.js file (Warning: if you turn if off in this script it will turn off teleport for all characters)

I'll leave teleport on then because my assassin isn't using enigma or CTA right now.  Config.BaalAssistant.Helper is false. 

Can I post a pastebin?

**Comment by Snoopy187** [comment]
post a copy of your char.config

**Comment by LunaTonks** [comment]
> post a copy of your char.config

Here is a pastebin of the whole thing
https://pastebin.com/gyvegjs4

**Comment by Snoopy187** [comment]
first issue i see: 
Config.Leader = "PallyOne"; // Leader's ingame character name. Leave blank to try auto-detection (works in AutoBaal, Wakka, MFHelper)
 config leader must be left blank unless you're following someone specifically in game. should read:
Config.Leader = ""; // Leader's ingame character name. Leave blank to try auto-detection (works in AutoBaal, Wakka, MFHelper)
and leave quitlist blank as well.
2nd part: 	Scripts.BaalAssistant = false;
set to true

**Comment by LunaTonks** [comment]
> first issue i see:
> Config.Leader = "PallyOne"; // Leader's ingame character name. Leave blank to try auto-detection (works in AutoBaal, Wakka, MFHelper)
> config leader must be left blank unless you're following someone specifically in game. should read:
> Config.Leader = ""; // Leader's ingame character name. Leave blank to try auto-detection (works in AutoBaal, Wakka, MFHelper)
> and leave quitlist blank as well.
> 2nd part: Scripts.BaalAssistant = false;
> set to true

Fixed both.  I set that as the leader b/c that's the games I want to join but I'm assuming it means leader that I follow in game.

**Comment by Snoopy187** [comment]
which entry script are you using to start the chars? use pubjoin if ur joining public games and set your filters to include the games you want. Use channel if ur in a channel and they're announcing games and set your filters for this as well.

party settings issue:
Config.PublicMode = 0; // 1 = invite and accept, 2 = accept only, 3 = invite only, 0 = disable.

must be changed to either 1 or 2.

**Comment by LunaTonks** [comment]
Where in the BotFollow do I put

> which entry script are you using to start the chars? use pubjoin if ur joining public games and set your filters to include the games you want. Use channel if ur in a channel and they're announcing games and set your filters for this as well.
> 
> party settings issue:
> Config.PublicMode = 0; // 1 = invite and accept, 2 = accept only, 3 = invite only, 0 = disable.
> 
> must be changed to either 1 or 2.

Ah, I was using BotFollow.  I've changed to PubJoin because he isn't announcing in channel anymore. 

If I want to join a specific game I change this to var IncludeFilter = [
	["Game name minus numbers"]

**Comment by Snoopy187** [comment]
> > which entry script are you using to start the chars? use pubjoin if ur joining public games and set your filters to include the games you want. Use channel if ur in a channel and they're announcing games and set your filters for this as well.
> > party settings issue:
> > Config.PublicMode = 0; // 1 = invite and accept, 2 = accept only, 3 = invite only, 0 = disable.
> > must be changed to either 1 or 2.
> 
> Ah, I was using BotFollow. I've changed to PubJoin because he isn't announcing in channel anymore.
> 
> If I want to join a specific game I change this to var IncludeFilter = [
> ["Game name minus numbers"]

yes

**Comment by LunaTonks** [comment]
> > > which entry script are you using to start the chars? use pubjoin if ur joining public games and set your filters to include the games you want. Use channel if ur in a channel and they're announcing games and set your filters for this as well.
> > > party settings issue:
> > > Config.PublicMode = 0; // 1 = invite and accept, 2 = accept only, 3 = invite only, 0 = disable.
> > > must be changed to either 1 or 2.
> > 
> > 
> > Ah, I was using BotFollow. I've changed to PubJoin because he isn't announcing in channel anymore.
> > If I want to join a specific game I change this to var IncludeFilter = [
> > ["Game name minus numbers"]
> 
> yes

If I change the quit list to the chars name I'm following, can i reduce the time delay between games?  RN i just sit in game indefinitely and takes forever to join a game.  Everything else seems to be working.  TYVM for all the help

**Comment by Snoopy187** [comment]
u can reduce the wakka & baal wait times in the char config if you'd like. 
& u could also try the quitlist option & see how it works

**Comment by LunaTonks** [comment]
> u can reduce the wakka & baal wait times in the char config if you'd like.
> & u could also try the quitlist option & see how it works

I did not have kill baal enabled.
How do I turn off going to a random wp to do BO?  My BO script is set to false

**Comment by Snoopy187** [comment]
https://github.com/kolton/d2bot-with-kolbot/issues/447

try this

**Comment by LunaTonks** [comment]
> [kolton/d2bot-with-kolbot#447](https://github.com/kolton/d2bot-with-kolbot/issues/447)
> 
> try this & enable kill baal

that did not work.  Still trying to go to an a4 wp after diablo.

**Comment by Snoopy187** [comment]
Trying getting the worldstone 2 wp and see what happens

**Comment by LunaTonks** [comment]
> Trying getting the worldstone 2 wp and see what happens

I got river wp and char goes to river to kill diablo.  I vaguely recalled seeing a "Kill diablo before throne" config.  I'm now disabling it.  

Config.BaalAssistant.FastChaos = false; // Kill Diablo before going to Throne

**Comment by LunaTonks** [comment]
> > Trying getting the worldstone 2 wp and see what happens
> 
> I got river wp and char goes to river to kill diablo. I vaguely recalled seeing a "Kill diablo before throne" config. I'm now disabling it.
> 
> Config.BaalAssistant.FastChaos = false; // Kill Diablo before going to Throne

That fixed it.  Now the only problem is jumping in a hot TP and running to the safe TP area.  How do I make it to safe tp only?

**Comment by Snoopy187** [comment]
In BaalAssistant there's a line: Config.BaalAssistant.WaitForSafeTP

Set that to true and it should wait for safe tps before they go in

**Comment by LunaTonks** [comment]
> In BaalAssistant there's a line: Config.BaalAssistant.WaitForSafeTP
> 
> Set that to true and it should wait for safe tps before they go in

I keep getting this error: Error in BaalAssistant (baalassistant.js #457) No safe TP message. (Area: 131, Ping:125, Game: One Cbaals67)

The autodetect leader for baal is different than leader for chaos, but it's the same leader for both.  Is that an issue?

Config.BaalAssistant.WaitForSafeTP = true; // Set to true to wait for a safe TP message (defined in SafeTPMessage)
...
		Config.BaalAssistant.SafeTPMessage = ["Safe TP!"]; // Configure safe TP messages.

**Comment by Snoopy187** [comment]
Bot will only go through the leaders tp.

**Comment by LunaTonks** [comment]
> Bot will only go through the leaders tp.

So that means I have to define leader here?
Config.Leader = "LEADER NAME"; // Leader's ingame character name. Leave blank to try auto-detection (works in AutoBaal, Wakka, MFHelper)

**Comment by Snoopy187** [comment]
If you have a game where you're following and you know the leaders name then yes. If running pub leave blank.
