### ISSUE TITLE
MFHelper: Redundant 2nd BO cast while doing `clearlevel`

### ISSUE THREAD

**Issue by sbombic** [blizzhackers/kolbot#193]
Hi,

Noticed an issue that my 2nd sorc, while doing MFHelper run, sometimes does double BO precast.

https://github.com/blizzhackers/kolbot/blob/b0fe9e923fcfa61ce35f0dbe59d8315a3b4551ed/d2bs/kolbot/libs/bots/MFHelper.js#L213

It looks like the linked line, produces redundant precast, since we just did precast at line #195.

Am I right, or do I miss something?

**Comment by DarkHorseDre** [comment]
Possibly - but it looks as if the extra forced precast is only done when clearing a level (takes longer) and not for kill boss, clear mobs.. depends on how much time can pass between the precasts maybe?

Ultimately I think this is just a cover for the fact that precast doesn't fire automatically but when a boss script calls it explicitly? (so for long runs players can go without BO for a while)
