### ISSUE TITLE
Error 105 and Error 0

### ISSUE THREAD

**Issue by LunaTonks** [blizzhackers/kolbot#194]
Error 105 - File (kolbot\libs\config\druid.eist.js:236) SyntaxError: Missing ] after element list
Error 0 - File (kolbot\libs\common\config.js:66) Error: Failed to load character config

I've looked and every starting " appears to have an ending " and same with [ ].

https://pastebin.com/d42jcraQ

**Comment by internethelper** [comment]
Config.QuitList = [""]; // List of character names to quit with. Example: Config.QuitList = ["MySorc", "MyDin"]; 
Either remove the quotation marks from the brackets or input a name inside of them at the beginning.
Config.Quitlist = []; // or Config.Quitlist = ["yourfavoriteleaderscharactername"]; //
If you still need
