### ISSUE TITLE
Kolbot Error At Waypoint

### ISSUE THREAD

**Issue by Divisi0ns** [blizzhackers/kolbot#198]
I start kolbot, logs in, goes to proper channel, blah blah and games created, goes to waypoint & BOOM "connection was interrupted" closes out d2 takes me back to the battle.net login... I've tried replacing my Paladin script with a new one and it still fucks up.. how can this be fixed?? Help please

**Comment by gtoilet** [comment]
Config.WaypointMenu = true;

you have true?

**Comment by Divisi0ns** [comment]
> 	Config.WaypointMenu = true;
> 
> 
> 
> you have true?


Yes

**Comment by Divisi0ns** [comment]
> 	Config.WaypointMenu = true;
> 
> 
> 
> you have true?


So how do I fix, what else could the issue be?

**Comment by Divisi0ns** [comment]
@gtoilet what else would the issue be? Every time I create a game and go to waypoint it still drops connection interrupted error

**Comment by jaenster** [comment]
Is it in act 5 hell? I had issues with this for some reason.

My fix was load the char (by hand) in act 1, take a waypoint to somewhere, try again.
