### ISSUE TITLE
Multiple Paladin bots

### ISSUE THREAD

**Issue by BurgerNfries** [blizzhackers/kolbot#199]
Hello all,

Hope y'all well and keeping safe.

I've an issue I've been trying to read on and can't seem to find the solution to this....

Basically I want to run two bots as Paladins. Two bots who should use the D2BotLead script (which you can switch to leecher, shopbot, etc)

Now here's the thing : I want one of them to be a 'full-time' mfer (chaos + worldstone ad such), but I'd like the other one to mainly focus on getting keys. 
These modifications should then be in the Paladin.js file, but the same file same seems to be bound both bots and I'm unsure on how to get two 'paladin.js' files, each customized for each both... 

Can anyone help me with this one?  I've been looking aroiund for answers without much success for now..

Thanks for your help in advance

**Comment by internethelper** [comment]
Do you mean how do you create 2 character config files that are paladins?  As in, copy the file and paste it, and name one paladin.onename.js and the other paladin.othername.js and config them separately.  Do you mean something else? I run 2 melee sorcs all the time.

**Comment by BurgerNfries** [comment]
Was exactly that, completely missed that out. Got it to work, thanks a bunch for the fast response !!

> Do you mean how do you create 2 character config files that are paladins? As in, copy the file and paste it, and name one paladin.onename.js and the other paladin.othername.js and config them separately. Do you mean something else? I run 2 melee sorcs all the time.
