### ISSUE TITLE
Not Bo’ing Please Help!

### ISSUE THREAD

**Issue by Divisi0ns** [blizzhackers/kolbot#202]
My character bo's and is constantly switching back and forth from bo to main, she does (bo) it appears but my life doesn't go up, what's the possible issue??

**Comment by internethelper** [comment]
Have you changed the Precast.js file?  Sounds like she is performing Battle Command, which does +1 all skills.  You wouldn't see life go up.  Kolbot > libs > common

**Comment by Divisi0ns** [comment]
I don't recall making any changes to that, except for making true/false edits for the casting of shadow master & cloak of shadows

**Comment by internethelper** [comment]
May have lost a bracket during editing, I've had that happen and it creates a broken loop, or crashes.  I don't see Cloak in there by default so if you added it, I would suggest checking or making renaming the precast file and right click in the folder, SVN Update, and get a fresh copy.  Then you can compare and see if you've inadvertently broken a bracket.  I've done that making my own conditions so I know its possible.

**Comment by Divisi0ns** [comment]
I have not touched any files in the common folder, and yes it mentions cloakofshadows in the assassin config by default, Line 526 I didn't add anything

**Comment by Divisi0ns** [comment]
I renamed the precast thing in Common folder right clicked and there's no svn update option

**Comment by internethelper** [comment]
O you must not be using tortoise svn.  Its super useful.  Hmmm if you haven't edited the precast, what have you edited?  Attack.js?  Sorceress.js in the Attacks folder?  If not check your charconfig file for typos.  Precast is pretty straight forward.

**Comment by Divisi0ns** [comment]
Only thing I've edited was the character config... although my character is using infinity as her main weapon could that be the problem? Is that for merc only? What could be causing the issue in the assassinconfig?

**Comment by mf022** [comment]
If your assassin char has a CTA, there is no matter if the main weapon is Infinity one.
Did you try to rewrite a new upgraded assassin config file?
All your files are upgraded to latest version?
