### ISSUE TITLE
A game already exists with that name

### ISSUE THREAD

**Issue by BurgerNfries** [blizzhackers/kolbot#203]
Title says it all. I get that issue everytime my gold find barb tries to create games. Strangely my other bots don't do that, even if the games are of same lenght.... 

And I really doubt there are other games named : LaGrosseCrissRunsXXX. Any help with that?

Thanks

**Comment by gtoilet** [comment]
entrypoint the goldfinder uses?
is he the only one creating games?

**Comment by BurgerNfries** [comment]
> entrypoint the goldfinder uses?
> is he the only one creating games?

Yes sometimes he’ll be alone sometimes not, does the same.
Sorry for the noob question, entrypoint what are we talking about here?

**Comment by gtoilet** [comment]
d2botlead.dbj

or custom way it makes the game

**Comment by BurgerNfries** [comment]
Hey I think it was just my game name being too long... thanks for the help though!

**Comment by gtoilet** [comment]
also you can have profile game name with some symbols like !@# ... but not really be able to create that game name manually as bot auto tries to copy what you set
