### ISSUE TITLE
Goldfind barb stays stuck

### ISSUE THREAD

**Issue by BurgerNfries** [blizzhackers/kolbot#204]
Hello fellow quarantiners,

Having an issue with my GF barb when he tries to use 'Find Item' on some corpses....

Sometimes he'll just stand there and his animation makes as if he's trying to do something but is unable. He can stand 30 secs around a group of dead corpses just doing nothing and like trying to use the skill... 
My merc is using Tomb Reaver and revives a skeleton from time to time, can it be caused by that? 
Not too sure what to make about that. 
Having some trouble with physical immunes too... I've set him to skip physical immunes but the barb will focus on an enemy which isn't phys immune spamming warcry on him whilst the merc will be attacking the phys immune with him obviously not taking any dmg... and well yeah it takes a while for him to get out of there... Is it possible to skip a precise unit so that won't happen? or anything else? 

Thanks for the help in advance

**Comment by gtoilet** [comment]
ive noticed this also im thinking he gets stuck clicking as if you move him he works like should
i was thinking of trying to add a move +1 if/after casting so many times in one spot
and it also continues to cast when some monsters are around and while getting smacked around

**Comment by SlashTurbo** [comment]
Go to common > attacks > Barbarian and find this part of the script and replace:

CorpseLoop:
					for (j = 0; j < 3; j += 1) {
						Skill.cast(142, 0, corpse);
						delay(100);
						Skill.cast(142, 0, corpse);
						delay(100);
					
					    Pather.moveToUnit(corpse);
					
					
						Skill.cast(142, 0, corpse);
						delay(100);


						tick = getTickCount();

						while (getTickCount() - tick < 50) {
							if (corpse.getState(118)) {
								Pickit.fastPick();

								break CorpseLoop;
							}

							delay(10);
						}
					}
				}
			}
		}
