### ISSUE TITLE
Bot sometimes sits at destination WP and does nothing.  Waits for MaxGameTime.

### ISSUE THREAD

**Issue by elninost0rm** [blizzhackers/kolbot#206]
So I can't figure out why this happens.  On any given run (maybe 5-10% of the time), the bot will end up sitting on a destination WP and will just sit there.  Stops doing anything.  MaxGameTime in the char's file is eventually reached and it quits out.  There is no visible error message.  Also worth noting that you can't pause/unpause the script.  Hitting the button does nothing.  

Any ideas?

**Comment by internethelper** [comment]
Is it happening at the same Act or Script? If you can determine which run this happens in, in your kolbot > logs folder you may see something stick out.  Has some info that the manager doesn't.  If it was every game it'd be an easier diagnosis, intermittent anything is always a bowl of fun!

**Comment by elninost0rm** [comment]
Nope, never usually the same script.  Seems to be totally random.  I will say that it seems to happen most on Mausoleum and Coldworm?  That's where I find it most often sitting, anyway.  Doesn't seem to happen much elsewhere.

Nothing sticking out in the log folder either.  Unfortunately it's not outputting anything to even the console when it hangs, so I have no idea where to start.

**Comment by elninost0rm** [comment]
Closing this.  Turns out I needed to turn on CPU acceleration and shit like that on my VMs.  Sometimes when using a WP, it would briefly freeze up the bot, presumably for longer than allotted in the code, so it would just hang forever afterwards.
