### ISSUE TITLE
Errors and crashes

### ISSUE THREAD

**Issue by BurgerNfries** [blizzhackers/kolbot#207]
Hey guys,

I'm getting all sort of errors and bugs with the bot, maybe you can help with me with that maybe not.
Errors like the char not being able to use a WP or something and having to exit the game before it should (looking at the character I can see the error ''Trying to use waypoint 1, Trying to use waypoint 2, 'Trying to use waypoint 3'' or something similar in the console. On the log it looks somerthing like this :

15:09:06 (Matador)  Error in AncientTunnels (ancienttunnels.js #21) Failed to move to Ancient Tunnels (Area: 44, Ping:62, Game: Allorunzti224)
15:09:22 (Matador)  Error in KurastTemples (kurasttemples.js #23) Failed to move to the temple (Area: 80, Ping:94, Game: Allorunzti224)
15:10:09 (Matador)  Error in Diablo (diablo.js #435) Failed to move to Chaos Sanctuary (Area: 107, Ping:125, Game: Allorunzti224)

It's not only one of the bots, it's pretty much all of them that do that from time to time.

Something also a bit frustrating, I will get to my laptop in the morning to simply see that all the D2 clients has been closed and the D2 Bot manager too, with no error showing and nothing else to see. Sometimes, there will be one or two of the bots left running on 4 and when I'll try to show the log it pops but then crashes and gives me an error I don't have any time to read because it vanishes after 1,5 sec (something like See your error log with a :( face). Not sure what log it is refering too.

Any help with that would be appreicated...
Thanks a bunch

**Comment by internethelper** [comment]
d2bs> kolbot > logs > scripterrorlog for an overview.  kolbot > logs for logs for each run of basically everything that would be printed on your screen.

Lots of variables here.  Are all running Leader?  Any Followers?  Other entry?  I'd start with charconfig files as they are calling the scripts and make sure no typos, conflicting trues or falses (baal and baalassist, for example)
