### ISSUE TITLE
Change to diablo.sealorder

### ISSUE THREAD

**Issue by jonathanstoker** [blizzhackers/kolbot#213]
Ive simply change the order of the config.diablo.sealorder but its still running as usual: Vizier -> Seis -> Infector

**Comment by gtoilet** [comment]
char config is where you changed seal order?
the newest bot version has it implemented already

**Comment by jonathanstoker** [comment]
Ya i changed it for 3 different characters from within their char-config. 
Trying to make: 
1 go Seis first
1 go Vizier first
1 go Infector first

**Comment by jonathanstoker** [comment]
**Example:** 

Char1:
`Scripts.Diablo = true;
Config.Diablo.WalkClear = false; // Disable teleport while clearing to protect leechers
Config.Diablo.Entrance = true; // Start from entrance
Config.Diablo.SealWarning = "Leave the seals alone!";
Config.Diablo.EntranceTP = "Entrance TP up";
Config.Diablo.StarTP = "Star TP up";
Config.Diablo.DiabloMsg = "Diablo";
Config.Diablo.SealOrder = ["vizier", "seis", "infector"];`

Char2:
`Scripts.Diablo = true;
Config.Diablo.WalkClear = false; // Disable teleport while clearing to protect leechers
Config.Diablo.Entrance = true; // Start from entrance
Config.Diablo.SealWarning = "Leave the seals alone!";
Config.Diablo.EntranceTP = "Entrance TP up";
Config.Diablo.StarTP = "Star TP up";
Config.Diablo.DiabloMsg = "Diablo";
Config.Diablo.SealOrder = ["seis", "vizier", "infector"];`

Char3:
`Scripts.Diablo = true;
Config.Diablo.WalkClear = false; // Disable teleport while clearing to protect leechers
Config.Diablo.Entrance = true; // Start from entrance
Config.Diablo.SealWarning = "Leave the seals alone!";
Config.Diablo.EntranceTP = "Entrance TP up";
Config.Diablo.StarTP = "Star TP up";
Config.Diablo.DiabloMsg = "Diablo";
Config.Diablo.SealOrder = ["infector", "seis", "vizier"];`

**Comment by jonathanstoker** [comment]
So i managed to do this.

I created at switch function inside diablo.js of runtype (1:2:3) and than set the diablo.config.runtype from within the char config.

**Comment by jonathanstoker** [comment]
finished
