### ISSUE TITLE
Can't level 5 accounts at same time??

### ISSUE THREAD

**Issue by Xizbox** [blizzhackers/kolbot#214]
Following the guide, I'm supposed to put in profile name as: "SCL-SORC" to play softcore, ladder, sorceress.

If I want to level 5 accounts at the same time, all being sorceress, this is not possible due to dublicate profile names not being allowed. How do I continue ?

**Comment by theBGuy** [comment]
this is an issue in sololeveling not blizzhackers also yes you can't have duplicate profiles so please number then i.e scl-sorc1 and so on
