### ISSUE TITLE
Help, cant get the bot to start.

### ISSUE THREAD

**Issue by ncd16126** [blizzhackers/kolbot#220]
So I'm getting the message "Window has unexpectedly exited... starting profile" when trying to start the bot up. I've done a lot of research and tried many solutions, but still cant seem to get it to work.

My OS: Windows 8

In diablo crash logs im getting ACCESS_VIOLATION (c0000005). Went through and did the DEP exceptions, didnt fix.

I am only running a D2 classic key, never played LOD. Could this issue be purely because I dont have an expansion key associated?'
Any help would be greatly appreciated.

Thanks!

**Comment by gtoilet** [comment]
yes you can only with the current release run bot with lod install only

**Comment by ncd16126** [comment]
I don’t have LOD, I only have classic. Is that why it isn’t working.

**Comment by gtoilet** [comment]
yea the bot has not been fully implemented for a classic only install at this time
