### ISSUE TITLE
kolbot revision 1.14b

### ISSUE THREAD

**Issue by backtoitagain** [blizzhackers/kolbot#221]
greetings,

noticed we are at revision 774. i would need to know what was the revision that worked with 1.14b / 1.14c (lasted a few weeks iirc) patches. could someone tell me please?

thanks in advance
best regards.

**Comment by mf022** [comment]
https://d2bot.discourse.group/t/kol-bot-1-14b/740/2
https://github.com/kolton/d2bot-with-kolbot/issues/1993
