### ISSUE TITLE
Modifying NTItemParser.dbl

### ISSUE THREAD

**Issue by shokkakhan** [blizzhackers/kolbot#225]
Hello there, I am looking to modify NTItemParser.dbl file so that it reports the line an item was picked up using, when it gets sold. The emboldened section near the bottom is the portion responsible for returning the line to pickit, and finally to the console. I have modified Town.js to also report sold items and dropped items to my D2BS console, so that I am able to better configure my PICKIT moving into the future, however it will not list to me the file/line like it does with items marked 'Kept'. I have tried placing the _"rval.line = stringArray[i].file + " #" + stringArray[i].line;"_ segment in the default switch case, but it determines that stringarray[i] has not been declared. If you change the value of the default switch case, it will update D2BS console to whatever you place as the value of _rval.line_, but I cannot figure out how to declare stringarray[i] when the function does return a 1 for _result_ variable

`NTIP.CheckItem = function (item, entryList, verbose) {
	var i, list, identified, num,
		rval = {},
		result = 0;

	if (!entryList) {
		list = NTIP_CheckList;
	} else {
		list = entryList;
	}

	identified = item.getFlag(0x10);

	for (i = 0; i < list.length; i++) {
		try {
			// Get the values in separated variables (its faster)
			const [type, stat, wanted] = list[i];

			if (typeof type === 'function') {
				if (type(item)) {
					if (typeof stat === 'function') {
						if (stat(item)) {
							if (wanted && wanted.MaxQuantity && !isNaN(wanted.MaxQuantity)) {
								num = NTIP.CheckQuantityOwned(type, stat);

								if (num < wanted.MaxQuantity) {
									result = 1;

									break;
								} else {
									if (item.getParent() && item.getParent().name === me.name && item.mode === 0 && num === wanted.MaxQuantity) { // attempt at inv fix for maxquantity
										result = 1;

										break;
									}
								}
							} else {
								result = 1;

								break;
							}
						} else if (!identified && result === 0) {
							result = -1;

							if (verbose) {
								rval.line = stringArray[i].file + " #" + stringArray[i].line;
							}
						}
					} else {
						if (wanted && wanted.MaxQuantity && !isNaN(wanted.MaxQuantity)) {
							num = NTIP.CheckQuantityOwned(type, null);

							if (num < wanted.MaxQuantity) {
								result = 1;

								break;
							} else {
								if (item.getParent() && item.getParent().name === me.name && item.mode === 0 && num === wanted.MaxQuantity) { // attempt at inv fix for maxquantity
									result = 1;

									break;
								}
							}
						} else {
							result = 1;

							break;
						}
					}
				}
			} else if (typeof stat === 'function') {
				if (stat(item)) {
					if (wanted && wanted.MaxQuantity && !isNaN(wanted.MaxQuantity)) {
						num = NTIP.CheckQuantityOwned(null, stat);

						if (num < wanted.MaxQuantity) {
							result = 1;

							break;
						} else {
							if (item.getParent() && item.getParent().name === me.name && item.mode === 0 && num === wanted.MaxQuantity) { // attempt at inv fix for maxquantity
								result = 1;

								break;
							}
						}
					} else {
						result = 1;

						break;
					}
				} else if (!identified && result === 0) {
					result = -1;

					if (verbose) {
						rval.line = stringArray[i].file + " #" + stringArray[i].line;
					}
				}
			}
		} catch (pickError) {
			showConsole();

			if (!entryList) {
				Misc.errorReport("ÿc1Pickit error! Line # ÿc2" + stringArray[i].line + " ÿc1Entry: ÿc0" + stringArray[i].string + " (" + stringArray[i].file + ") Error message: " + pickError.message + " Trigger item: " + item.fname.split("\n").reverse().join(" "));

				NTIP_CheckList.splice(i,1); // Remove the element from the list
			} else {
				Misc.errorReport("ÿc1Pickit error in runeword config!");
			}

			result = 0;
			
		}
	}

!!!!THIS IS THE SECTION RESPONSIBLE FOR REPORTING THE LINE NUMBER TO PICKIT!!!!!

	if (verbose) {
		switch (result) {
		case -1:
			break;
		case 1:
			rval.line = stringArray[i].file + " #" + stringArray[i].line;

			break;
		default:
			rval.line = null;

			break;
		}

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

		rval.result = result;

		return rval;
	}

	return result;
};`

Anybody got any ideas on how to have this function report a line numbers that an item was picked for, and then reporting it to D2BS console?

**Comment by shokkakhan** [comment]
For example:

This IK helm was kept, and at the bottom, the Line number was included.[https://i.imgur.com/5TxVlQu.png](Example)

This helm was dropped, and it does not include the line number.[https://i.imgur.com/iTlhLCB.png](Example)

**Comment by theBGuy** [comment]
I'm not sure you fully understand what you're trying to do. Attempting to backtrack before or after and item is sold to why it was picked in the first place isn't feasible. A unid item for example could match any number of lines so you want to print what could possibly amount to 1000's of lines (for some peoples pickits) every time an item is sold. You'd one, crash d2bot# and two even if you didn't you would run at of memory very quick. I'm closing this out.
