### ISSUE TITLE
Crafting items lvl

### ISSUE THREAD

**Issue by BurgerNfries** [blizzhackers/kolbot#226]
Hello folks,

Is there any way of modifying the ilvl's for the items the bot find for crafting?

4 of my guys do crafting (around 5-6 recipes each) and I hardly get anything. My kolton.nip lines are close to similar when it comes to the 'criterias' for crafted and rare items for example but still taking in account all the limitations, mods and all details regarding crafted items (believe me I've read a bunch on it), but I do find rare items somewhat often opposed to crafted items.

I feel like maybe something's wrong with the ilvl of the items the bot picks for items?
Some items need to be higher level for certain mods to span (+2 skills on a ammy) but on some items it's more benefical if you get them at a certain lower level (gloves for example).
How does the bot work regarding this; does he pick only  >= X ilvl items or does he stores any ilvl items it finds? Any way to modify these?

Another thing; for example I'm trying to craft a GG caster belt. The bots will be looking for a sharksin belt, a jwl, ith rune and a P Amethyst for the recipe. How does it work : will the bot pick each part only ONCE, meaning that if he's already found a sharkskin belt he'll won't pick up another one again as long as he has one in its inventory/hasn't used it for crafting OR will he keep stashing every item he finds to make another recipe? is there any way to change this setting? 

If any of you crafting connoisseur could give me a hand
Thanks in advance

**Comment by BurgerNfries** [comment]
Really so nobody knows about this?

**Comment by mehlichmeyer** [comment]
I can give you the pickit line for amus with ilvl 95+, but i think the crafting system overwrites the pickit anyway, not sure if there is a way to edit the crafting system pickit directly (there must be, but idk where/how). 

As for your second question, you can use config to decide how many sets the mfer will collect before he will join the crafter, take a look at your craft config again, its there with each set you choose to craft. But yes, if you put 1 there, the bot will only collect 1 pamy, 1 ith etc. He will skip the duplicates until he has the desired sets full.

**Comment by mf022** [comment]
in Cubing.js you can find the default levels for crafting recipes - <https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/common/Cubing.js#L205-L348>.
also there you can see the condition for ilvl - <https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/common/Cubing.js#L801-L813>.

Ingredients for the crafting recipes will be auto-picked.
To increase the probability to get the ingredients, maybe you should add runes and flawless gems cubing, like in case of caster belt:
```
Config.Recipes.push([Recipe.Gem, "Flawless Amethyst"]); // make Perfect Amethyst
Config.Recipes.push([Recipe.Rune, "Eth Rune"]); // Upgrade Eth to Ith
```
