### ISSUE TITLE
Small improve on FieldID

### ISSUE THREAD

**Issue by M3RK4B4H** [blizzhackers/kolbot#227]
Guys i have the same problem as other user posted in kolton/kolbot issues here's the link:
https://github.com/kolton/d2bot-with-kolbot/issues/1781

How to fix that and do fieldID when inventoyry is full and not when a item has dropped and needs to be picked.

**Comment by M3RK4B4H** [comment]
it is not possible?

**Comment by M3RK4B4H** [comment]
No one knows how to do that?

**Comment by e-n-g** [comment]
> Guys i have the same problem as other user posted in kolton/kolbot issues here's the link:
> [kolton/d2bot-with-kolbot#1781](https://github.com/kolton/d2bot-with-kolbot/issues/1781)
> 
> How to fix that and do fieldID when inventoyry is full and not when a item has dropped and needs to be picked.

The suggestion posted there (editing Pickit.js) will work.
```js
// Item can fit - pick it up
if (canFit) {
	this.pickItem(pickList[0], status.result, status.line);
	Config.FieldID && Town.fieldID(); // newly added line to force fieldID
}
```
That will force a fieldID after the item is picked up. I tested it on one of my chars that uses fieldID and works as expected, they ID everything right after picking it up. It'd probably be better to only force the fieldID if the available space drops below a certian %, but for a quick fix this is fine.

**Comment by M3RK4B4H** [comment]
> > Guys i have the same problem as other user posted in kolton/kolbot issues here's the link:
> > [kolton/d2bot-with-kolbot#1781](https://github.com/kolton/d2bot-with-kolbot/issues/1781)
> > How to fix that and do fieldID when inventoyry is full and not when a item has dropped and needs to be picked.
> 
> The suggestion posted there (editing Pickit.js) will work.
> 
> ```js
> // Item can fit - pick it up
> if (canFit) {
> 	this.pickItem(pickList[0], status.result, status.line);
> 	Config.FieldID && Town.fieldID(); // newly added line to force fieldID
> }
> ```
> 
> That will force a fieldID after the item is picked up. I tested it on one of my chars that uses fieldID and works as expected, they ID everything right after picking it up. It'd probably be better to only force the fieldID if the available space drops below a certian %, but for a quick fix this is fine.

Oh wow ^^ didn't noticed about it, agree with you it can be better if he does fieldID when inv is almost full because using dropped items announce it will be a bit heavy if the bot spams every identify item ^^ lets see if we can improve that and the bot does it when the inv is almost full.

**Comment by theBGuy** [comment]
I just changed Config.FieldID to work based on inventory filled percentage so you can define how full you want your inventory before it gets called.
