### ISSUE TITLE
How Lower Kurast script dissapeared in the last update?

### ISSUE THREAD

**Issue by M3RK4B4H** [blizzhackers/kolbot#228]
I used that script to open the chests at the beginning of the game with my diablo/baal helper not much time ago maybe at 2019, noticed that the script dissapeared at last update, how?

**Comment by gtoilet** [comment]
you now want ChestMania
and has been for a while now

**Comment by M3RK4B4H** [comment]
> you now want ChestMania
> and has been for a while now

It's ok ill test it just with act3 Lower Kurast.

**Comment by gtoilet** [comment]
yea just set the area id you want to run
and should be the same as your looking for

**Comment by M3RK4B4H** [comment]
Tested ChestMania and it's not the same as the old script Lower Kurast located at act3 scripts where the character just opens the 4 or 8 good chests (depending on map), ChestMania opens alls chests and even i had to locate it before boss scripts at character config to start with lower kurast before going to diablo... how's that? no way to recover the old script?

**Comment by M3RK4B4H** [comment]
> yea just set the area id you want to run
> and should be the same as your looking for

Isn't the same as before :( much way easier with the old script check my post up.

**Comment by gtoilet** [comment]
o so your iso the unique chest thing?
sure it wasnt the kurasttemple.js?
idk if i have ever seen a lower kurast only script i even went back thru the old releases of bot

**Comment by M3RK4B4H** [comment]
> o so your iso the unique chest thing?
> sure it wasnt the kurasttemple.js?
> idk if i have ever seen a lower kurast only script i even went back thru the old releases of bot

No ^^ i mean Lower Kurast script, i used it 2 ladders ago at kolton repository but checked it and its the same now as here. The script was located at act3 before kurast temples :) it go to lower kurast and just open the 3 or 6 chests there depending on the map, nothing more :).
Now ChestMania has to be located before the boss scripts at character config, to starts with it at Lower Kurast as first script, also it does double precast at wp... a bit waste of time just starting, then it open all chests there, also a waste of time, when the old script just opened the 3 or 6 chests located at the small houses ^^ also a big difference here, i have modified some common archives like mics, attack etc to open all kind of stashes or chests, the old script just opens again the same chests and ends, even with that modified stuff, ChestMania opens everything there with the modified stuff ^^ waste of time again.

**Comment by M3RK4B4H** [comment]
no way to revover the old script?

**Comment by mf022** [comment]
> I used that script to open the chests at the beginning of the game with my diablo/baal helper not much time ago maybe at 2019, noticed that the script disappeared at last update, how?

Maybe you had that custom script from other source.

The scripts are the same on the [blizzhackers kolbot repository](https://github.com/blizzhackers/kolbot/tree/master/d2bs/kolbot/libs/bots) with previous [d2bot-with-kolbot](https://github.com/kolton/d2bot-with-kolbot/tree/master/d2bs/kolbot/libs/bots).

Even in old [1.13d branches](https://github.com/blizzhackers/kolbot/tree/patch-113d-core15/d2bs/kolbot/libs/bots), archived in June 2017, I couldn't find the script you have reclaimed.
