### ISSUE TITLE
Getting Error Message While Dropping, something about saving images

### ISSUE THREAD

**Issue by mehlichmeyer** [blizzhackers/kolbot#229]
Sometimes when Im using the dropper I get a popup saying "An error has occured! Please view your exception.log file. D2bot# will close now :(". Excerpt of my exception.log is below. The funny thing is that the bot is not shut down after, and everything is working fine. I just get these popups and sometimes it causes my logs to have a hickup.

Anybody have an idea how I can fix this?

#Exception.log:

12.04.2021 18:52
System.Runtime.InteropServices.ExternalException (0x80004005): Allgemeiner Fehler in GDI+. [General Error in GDI+]
   bei System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   bei System.Drawing.Image.Save(String filename, ImageFormat format)
   bei D2Bot.ItemScreenShot.Take(Item item, Boolean Save)
   bei D2Bot.ItemScreenShot.Take(D2Item d2item, Boolean Save)
   bei D2Bot.Main.HandleMessage(IntPtr hWnd, String message)
   bei D2Bot.Main.<>c__DisplayClass53_0.<WorkThread>b__0()

12.04.2021 18:52
System.Runtime.InteropServices.ExternalException (0x80004005): Allgemeiner Fehler in GDI+. [General Error in GDI+]
   bei System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   bei System.Drawing.Image.Save(String filename, ImageFormat format)
   bei D2Bot.ItemScreenShot.Take(Item item, Boolean Save)
   bei D2Bot.ItemScreenShot.Take(D2Item d2item, Boolean Save)
   bei D2Bot.Main.HandleMessage(IntPtr hWnd, String message)
   bei D2Bot.Main.<>c__DisplayClass53_0.<WorkThread>b__0()

**Comment by mf022** [comment]
maybe you could find a solution on https://appuals.com/solved-how-to-fix-error-0x80004005/ , or on other places.

where is the location of your kolbot folder? the desktop location includes the path to the current PC user, and that could be too long, and it could have different charsets, according to your native language.
maybe you could try to set a folder directly on the root of a drive, like in the [guide](https://github.com/blizzhackers/documentation/blob/master/d2bot/Download.md#download-with-tortoisesvn)




> The funny thing is that the bot is not shut down after, and everything is working fine.

so, is this only a limedrop error? ... maybe related only on D2BotGameAction.dbj or GameAction.js.
idk, the default line <https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/GameAction.js#L12> is set to false.
