### ISSUE TITLE
Best class?

### ISSUE THREAD

**Issue by BurgerNfries** [blizzhackers/kolbot#233]
Hello fellas,

I was just wondering what for you guys is the most used class for a bot.

I'm debating between Hdin and GF Barbs. 
So far, I've a light sors; pros are that it's very fast but with the game limitation per hour that doesn't really matter, she can't run every area like I would like her to (WS1-2 for example).
Hammerdins can do pretty much everything, so that's a big plus.
GF barbs, you won't be doing much of act4 and past but with the $$ he acumulates he actually gambles a lot more than a hdin for example. 

*Im Non-ladder so a lot of stuff I don't have access to. I mainly run for gg rares (circs, rings/ammy, boots, some class spec & weapons), crafting (jewelry, belts & gloves) and lastly close to perf uniques.

Any insight?
Thx a bunch.

**Comment by Ra-Ni** [comment]
umm...I don't think this belongs here @jaenster

**Comment by mf022** [comment]
> umm...I don't think this belongs here

this isn't a kolbot issue, and maybe https://d2bot.discourse.group/ is the proper place.



> I'm debating between Hdin and GF Barbs.

maybe a team, or multiple chars in the same game, clearing different areas, and together on Diablo-Baal, ... depending of your preferences.
the barb can also be set the BO-er in the game, with high level of BO+Shout.
