### ISSUE TITLE
Did someone got a solution for my problem?

### ISSUE THREAD

**Issue by DS1337** [blizzhackers/kolbot#239]
Thread is little bit older and I cant push it up, but did someone got any idea how to fix this problem mby?

https://github.com/kolton/d2bot-with-kolbot/issues/2030

**Comment by mf022** [comment]
Did you upgrade your files according to this repository?

Diablo attack for sorceress - https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/bots/Diablo.js#L281-L307

**Comment by DS1337** [comment]
Yes it is exacly like this in Diablo.js
But she is not moving away to the perfect distance like @ baal and other Bosses...
When Diablo is moving or come to clow, she just stay @ the same spot and not moving away from him...

I think there is a litte bug @ Diablo with a Sorc...

mby need a update for it.

**Comment by mf022** [comment]
> Diablo attack for sorceress - https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/bots/Diablo.js#L281-L307

maybe this part should be rewritten to cast a skill from distance from Diablo position, and not from fixed positions.

**Comment by JPL56** [comment]
In your character config file lines 526, 527, 528
my sorc always will dodge

	Config.Dodge = true; // Move away from monsters that get too close. Don't use with short-ranged attacks like Poison Dagger.
	Config.DodgeRange = 15; // Distance to keep from monsters.
	Config.DodgeHP = 100; // Dodge only if HP percent is less than or equal to Config.DodgeHP. 100 = always dodge.
