### ISSUE TITLE
MuleLogger issue not connecting to profiles

### ISSUE THREAD

**Issue by jeanmroy** [blizzhackers/kolbot#242]
Now, when I try to start the script, It's opening D2, but not connecting to any account and it just ends the job there.
12:46:42 (MuleLog) Done logging mules!

My Kolbot profile is well using the D2BotMuleLog.dbj and has nothing in "Game info". It's pretty empty. I've set the key to use, entry script, profile name, difficulty, relm, mode..

Here is my MuleLogger config file :
LogAccounts: {
/* Format:
"account1/password1/realm": ["charname1", "charname2 etc"],
"account2/password2/realm": ["charnameX", "charnameY etc"],
"account3/password3/realm": ["all"]

		To log a full account, put "account/password/realm": ["all"]

		realm = useast, uswest, europe or asia

		Individual entries are separated with a comma.
	*/

	"nottellingyou/myrealpassword/useast": ["all"],
	"nottellingyou2/myrealpassword/useast": ["all"]
},
LogGame: ["mypermqda", "12q"], // ["gamename", "password"]
LogNames: true, // Put account/character name on the picture
LogItemLevel: true, // Add item level to the picture
LogEquipped: false, // include equipped items
LogMerc: false, // include items merc has equipped (if alive)
SaveScreenShot: false, // Save pictures in jpg format (saved in 'Images' folder)
IngameTime: rand(180, 210), // (180, 210) to avoid RD, increase it to (7230, 7290) for mule perming
I'm not seeing anything wrong...

I also tried with that :
LogAccounts: {
"Logger1": { // mule logger profilename
"nottellingyou/myrealpassword/useast": ["all"]
},
"Logger2": { // mule logger profilename
"nottellingyou2/myrealpassword/useast": ["all"]
}
},

but still doing same issue.

I would really want to make it work !

**Comment by jeanmroy** [comment]
I've made the test by removing everything in the LogAccounts: { }, bracket, and it's reacting the same (Kolbot showing in console : 12:46:42 (MuleLog) Done logging mules!). It means the issue is in that bracket.

Any help ?

**Comment by jeanmroy** [comment]
pls :D I'm sure the answer is real easy.

**Comment by mf022** [comment]
did you check https://github.com/blizzhackers/documentation/blob/master/kolbot/D2BotMuleLog.md/#d2botmulelog ?
