### ISSUE TITLE
restriction of waiting time in lobby

### ISSUE THREAD

**Issue by fabio1999ita** [blizzhackers/kolbot#243]
the bot is unable to recognize that it has been restricted for a few hours and cannot create/enter the game?

![image](https://user-images.githubusercontent.com/27001568/123520926-b343ff00-d6b3-11eb-8a69-d3173fe913af.png)

**Comment by mf022** [comment]
that cant be read.

you should not abuse by kolbot.
<https://github.com/blizzhackers/kolbot#rules>
