### ISSUE TITLE
Druid doing precast after killing Baal xD then he exits game

### ISSUE THREAD

**Issue by M3RK4B4H** [blizzhackers/kolbot#248]
How that? Strangers things happening ^^ I need to modify that and just exit game after killing Baal.

**Comment by mf022** [comment]
I guess that it is not a bug, but it depends of the bo's level and the time required for your bot to kill Baal.
What other settings does your bot have?

**Comment by M3RK4B4H** [comment]
> I guess that it is not a bug, but it depends of the bo's level and the time required for your bot to kill Baal.
> What other settings does your bot have?

You are right, this is fixed.
