### ISSUE TITLE
max mana on large charm is 34 and max hp is 35, so it should probably be 69 there

### ISSUE THREAD

**Issue by eskiq** [blizzhackers/kolbot#251]
https://github.com/blizzhackers/kolbot/blob/0c9f2105b56fe4de4b0a66cd3abc08dabe69ff1b/d2bs/kolbot/pickit/kolton.nip#L687

**Comment by mf022** [comment]
> 
> 
> https://github.com/blizzhackers/kolbot/blob/0c9f2105b56fe4de4b0a66cd3abc08dabe69ff1b/d2bs/kolbot/pickit/kolton.nip#L687

You are right, according to <http://classic.battle.net/diablo2exp/items/magic/mediumcharms.shtml>, or <https://diablo2.diablowiki.net/Charm_Affixes#.2BLife_2> + <https://diablo2.diablowiki.net/Charm_Affixes#.2BMana>

that file was written by @kolton on the 1st release, on 2012.
I have personally used only my customized pickit files.

**Comment by mf022** [comment]
for the moment I corrected the files from pickit repository <https://github.com/blizzhackers/pickits/commit/74f39d3a51e81ecf25de4970891f0005f860f6a0>
