### ISSUE TITLE
Rusher/rushee help! Rusher not working

### ISSUE THREAD

**Issue by the-rad420** [blizzhackers/kolbot#253]
Okay I am stumped here
I'm trying to get my rusher rushee set up

I do all the things. Setting rushee rusher, the correct leader. Changing follow file, party requests etc

I hit start.
They open, join game and party.
My rushee runs to the TP area and waits for tp
My rusher doesn't move and says "waiting for party area info" and about 10 secs later says bye and leaves
I type master. Sometimes he says "xx is now my master" and then do type do andariel but nothing happens.
I just read on a comment saying they have to be on each other's friends list, which I will be trying later tonight when I get home but I can't imagine that being the issue.
Cheers!

**Comment by mf022** [comment]
Did you try to use LocalChat in mode 1 or 2? 
options - <https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/config/_BaseConfigFile.js#L542-L547>

Did you complete the char config with the required info and desired quests? 
options - <https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/config/_BaseConfigFile.js#L169-L179>
