### ISSUE TITLE
My farmers wont go in my game to drop keys

### ISSUE THREAD

**Issue by piar22** [blizzhackers/kolbot#254]

**Comment by mf022** [comment]
did you complete the required info on <https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/TorchSystem.js#L32-L39>?

**Comment by piar22** [comment]
yea i did that, my leachers and my leads are my keyfinder

**Comment by piar22** [comment]
"Smith": { // Farmer profile name
			// Put key finder profiles here. Example - KeyFinderProfiles: ["MF 1", "MF 2"],
			KeyFinderProfiles: ["hammer2", "Sorc2", "Litesorc", "Pal", "Druid", "Druid2", "Litesorc", "SorcNOVA", "Ass"],

			// Put the game name of uber killer here (without numbers). Key finders will join this game to drop keys. Example - FarmGame: "Ubers-",
			FarmGame: "Fatuber-"
		}

**Comment by mf022** [comment]
> FarmGame: "Fatuber-"

Have you tried a shorter name of a game?

**Comment by piar22** [comment]
> > FarmGame: "Fatuber-"
> 
> Have you tried a shorter name of a game?

no ill try that

**Comment by piar22** [comment]
it says got key count request from : (namechar)

**Comment by mf022** [comment]
Did you set LocalChat on mode 1 or 2?

**Comment by piar22** [comment]
> Did you set LocalChat on mode 1 or 2?

no, what is localchat for? but ill try, never use localchat thx

**Comment by mf022** [comment]
> what is LocalChat for?

all chat between bots is made locally, so all profiles opened on the same manager can communicate anything.
mode 2 can be used for follower team, because the chat manually typed phrases are sent also locally.
