### ISSUE TITLE
Gold Find and Gamble Bot

### ISSUE THREAD

**Issue by CraCken1** [blizzhackers/kolbot#258]
Hello Guys, 

im looking for a Bot Config who does Gold Find Runs up to 2 Milion Gold at Travi and than goes to Gamble at Anya. 
I Want him to Gamble Talons and Claws. 
Mainly with 
2 Assa / 3 LS (with adds mainly doing this for the ias Claws)
3 Assa / 3 LS 
40 ias Fools Mod 
6 Fade Claws 

Can someone tell me if this is possible and how to Configure it. 
Can Help with some High Runes (Realm Doesnt Matter)

ty

**Comment by mf022** [comment]
Any bot can gamble during its runs, if he have  gold enough to start gambling
check <https://github.com/blizzhackers/documentation/blob/master/kolbot/CharacterConfig.md/#gambling-config>
and also during runs, the minishopbot can be set on <https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/config/_BaseConfigFile.js#L568-L569>

but for trading Anya's magic claws, you can set a shopbot <https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/config/_BaseConfigFile.js#L194-L201>. 
you should edit the <https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/pickit/shopbot.nip> and let uncommented only the lines according to your desires, but you can also write additional lines, like:
```
// claws
([type] == handtohand || [type] == assassinclaw || [type] == assassinitem) # [assassinskills]+[trapsskilltab]+[skilllightningsentry] >= 5
([type] == handtohand || [type] == assassinclaw || [type] == assassinitem) # [assassinskills]+[shadowdisciplinesskilltab]+[skillfade] >= 5

[name] >= katar && [name] <= scissorssuwayyah # [assassinskills]+[trapsskilltab]+[skilllightningsentry] >= 5

([name] > suwayyah || [name] == feralclaws || [name] == runictalons || [name] == scissorskatar || [name] == scissorsquhab || [name] == scissorssuwayyah  || [name] == wristsword || [name] == warfist || [name] == battlecestus || [name] == greatertalons || [name] == greaterclaws) # [assassinskills]+[trapsskilltab]+[skilllightningsentry] >= 5 
```
 edit those lines, like you wish
