### ISSUE TITLE
Rushee Bot commands

### ISSUE THREAD

**Issue by RickerMD** [blizzhackers/kolbot#262]
There is a List with the commands avaible?
can i commant to do Ancients?

**Comment by mf022** [comment]
<https://github.com/kolton/d2bot-with-kolbot/wiki/Rusher>, but you can also check the Rusher script:
- https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/bots/Rusher.js#L91-L135
- https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/bots/Rusher.js#L172-L223

Have you set LocalChat in mode 1 or 2?

> can i command to do Ancients?

check configuration file <https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/config/_BaseConfigFile.js#L179>
