### ISSUE TITLE
 “connecting to the fastest server”

### ISSUE THREAD

**Issue by EndzonEE** [blizzhackers/kolbot#264]
Hey party people,

i have a problem to start the kolbot.
First things first, i install the kolbot like the instructions.
i make a profile, keys and acc.
all done, first problem was the update problem.
i fixxed that problem by reading help lists.
Now the next problem whitout any usefull working answer.
If i start the bot, the game starts logg in and stuck at “connecting to the fastes server”.
Whitout the bot no problems to connect and play dia.
if you google that problem theres much answer about the firewall that i tryd, but doesnt fix that problems.

Any ideas for my problem`?

**Comment by mf022** [comment]
Did you see <https://github.com/blizzhackers/documentation/blob/master/kolbot/FAQ.md/#how-to-avoid-checking-versions-issue> ?

**Comment by EndzonEE** [comment]
sure i try them all out !

**Comment by mf022** [comment]
I added it separately in the FAQ
<https://github.com/blizzhackers/documentation/blob/master/kolbot/FAQ.md/#how-to-avoid-connecting-to-the-fastest-server>
