### ISSUE TITLE
D2BS is not injecting into D2..... Error: D2BS is not responding... starting profile

### ISSUE THREAD

**Issue by halfbak3dd** [blizzhackers/kolbot#267]
I've read so many threads.. Nothing is working.... Everything works fine on my PC, but my laptop is a different story.

When starting the profile, diablo window opens and sits for 5-10 seconds and I get the D2BS not responding error in the log and the window closes and retrys. D2BS version isn't showing in the bottom right hand of the D2 window like it should (So it isnt even getting injected). I am running 1.14d with all my github files updated and ready to go. All administrative rights set and compatibility mode windows 7 (I've tried xp service pack 3 and left it unchecked)

**Comment by mf022** [comment]
did you see <https://github.com/blizzhackers/documentation/blob/master/kolbot/FAQ.md/#d2bs-is-not-responding--starting-profile>?

**Comment by mf022** [comment]
you can try to move your Diablo II folder, and update the d2bs profile with that path.
make other minor things, and post the results if you get positive ones.

**Comment by Sufod** [comment]
Hi,

I had the same problem, just don't use the latest version but the previous one is fixing the issue -> https://github.com/blizzhackers/kolbot/tree/cd4b1638403df335e8d360e6c84ddce50c7da02e

**Comment by AIbot2020** [comment]
Hi Sufod,

Could you please show me how to get previous version? I checkout Kolbot via TortoiseSVN and it only has the latest version.

D2Bot# 20.6.7.100

**Comment by Sufod** [comment]
Sure, just click on the link I provided in my previous comment, click on the green button "Code" and download as Zip

**Comment by AIbot2020** [comment]
I follow the link in your previous command and downloaded the files in the green button "Code", but I still having same issue then I find out your version is the same with latest version I downloaded last 2 days in  https://github.com/blizzhackers/kolbot/  

version # 20.6.7.100

**Comment by Sufod** [comment]
OK, as I told I had the same issue until switching to this version, but now I had a look at the changes in the last version and they are indeed minor formatting fixes that should not change anything regarding the functionality...

I don't really know what happened here but is is working. Another change I did is copying the entire Diablo II folder in C:

**Comment by mf022** [comment]
> I don't really know what happened here but is is working. Another change I did is copying the entire Diablo II folder in C:


Some folders related to user account have by default some restrictions in windows. 

That's why I have recommended to change the location of Diablo II folder](https://github.com/blizzhackers/kolbot/issues/267#issuecomment-912795195), or even for D2BS, avoiding desktop. 
Usually on desktop you should have only the shortcuts to applications/programs.

I added that thing even in the [kolbot download guide](https://github.com/blizzhackers/documentation/blob/master/d2bot/Download.md#download)

**Comment by AIbot2020** [comment]
No matter how many times I changed my Diablo II folder around, it still having same issue. Thanks guys for your help, I'll mess around with to see if I can figured out the issue.

**Comment by mf022** [comment]
> No matter how many times I changed my Diablo II folder around, it still having same issue.


You should choose the root of a drive (C:\ , D:\ , ...)
Try it even for kolbot folder. Adjust the path in the manager profiles.
On desktop place only the shortcuts.

**Comment by halfbak3dd** [comment]
I've done that multiple times. Right now, i am trying to reinstall d2 and
remove all of kolbot. Redo the process for that... everything will be in
the C root.

**Comment by mf022** [comment]
can you run Diablo 2 directly from shortcut (with -w), on every location?

**Comment by halfbak3dd** [comment]
Yes. I can play D2 window'd from everywhere. it Just will not inject. I
also, went and looked at my PC setup, and I DO NOT have game.exe set to run
as admin, but the bot works just fine. No issues.

**Comment by MightyToSaveGod** [comment]
i know you're all dumb n stuff retarded n sh1t but help yourselves for once okay take my advice choke on these words as if you were gonna vomit and puke yourself afterwards i've successfully identified the problem. YOUR ANTI-VIRUS IS BLOCKING D2BS. LOL THATS RIGHT so allow it through that sum a b1tch. Problem should be resolved. Titties!!!!
