### ISSUE TITLE
Sorc Chickening Chaos A LOT

### ISSUE THREAD

**Issue by Deadwalker123** [blizzhackers/kolbot#269]
i'd say 4/5 runs my ligt sorc chickens.

I've tried telestomp on/off
i've tried recommended configs for "move to" position after seals, and even tried removing that itself.
My character dodges everything n stuff fine but with these seal packs it always jumps directly into the middle of them resulting in a chicken.  Only reason I live sometimes is because it dodges out without dying then it proceeds to kill everything just fine.

So it's not that my character is standing where they spawn, it's jumping into them after they spawn, no matter what.

I even tried a configure that supposedly made all the mobs be dead around the immuned target prior to telestomping.  Still just jumps in head first and rips.

Seems to mostly happen on Lord or Infector.  I know which are both usually light immune but I have infinity and setup dodge and don't even have telestomp on (although i've tried it with it on)

Also interesting it doesn't seem to jump into any of the Baal minons.  Even though sort of the same idea.

The only thing I haven't tried is enabling 0 for clear area instead of 0xF or 0x7.   0 Kill all seems like it would take a long time considering I also do Pit and Ancient Tunnels.

Anyways I've ran out of ideas

Sorc Stats:
60% FHR
2493 Life
900 Mana
11% Block
+17 Skills
Using hp/mp/rv/rv for pots

I don't really see it being a gear issue conisdering it would be quite pricey to even get slightly tankier so.

**Comment by gtoilet** [comment]
after seis and fector seal clicks i increased the delay that she would sit to help mine

**Comment by tamkaho** [comment]
> after seis and fector seal clicks i increased the delay that she would sit to help mine

which lines?

**Comment by gtoilet** [comment]
this.seisSeal = function () {  ......... in your script see below where to add the delay

	this.seisSeal = function () {
		print("Seis layout " + this.seisLayout);
		this.followPath(this.seisLayout === 1 ? this.starToSeisA : this.starToSeisB);

		if (!this.openSeal(394)) {
			//throw new Error("Failed to open de Seis seal.");
		}
				delay(1500);




this.infectorSeal = function () {  ......... in your script see below where to add the delay

	this.infectorSeal = function () {
		print("Inf layout " + this.infLayout);
		this.followPath(this.infLayout === 1 ? this.starToInfA : this.starToInfB);

		if (!this.openSeal(392)) {
			//throw new Error("Failed to open Infector seals.");
		}
				delay(1500);
