### ISSUE TITLE
Character moving very slowly

### ISSUE THREAD

**Issue by cddelGit** [blizzhackers/kolbot#271]
Seemingly at random my characters start running very slowly.
It seems to be related to cold monsters but never seen it happen when not using kolbot.

They are not using the walking feature.

**Comment by Phnmz** [comment]
same here, would love to have a solution..

**Comment by mf022** [comment]
could it be a server bug?
https://github.com/blizzhackers/kolbot/issues/274#issuecomment-935830900

**Comment by XternalFactor** [comment]
Mine was doing that in a particular area where i had modified scripts.
for example i was adding a partial script from baal.assistant.js to my cows.js

here is the code i ended up finalizing.

If you notice the "for(p=4; p>1" part, the p=4 i had changed to 6 not realizing i hadnt changed Pather.useWaypoint(4); to Pather.useWaypoint(6);

When the bot got to that portion of the script, it would move insanely slow, /fps went high and ping went high.

I decided not to use 6 and just stick with 4.

Consider what scripts you have modified and if you cant remember, "COPY" those to a "NEW" file and revert your original .js. (right click on file, select tortoise, select "revert" hit OK.

Should load that into default

if (!ShrineStatus && GetShrine && me.area !== 107 && me.area !==108) {
		if (!ShrineStatus) {
			Pather.useWaypoint(4);

			for (p = 4; p > 1; p -= 1) {
				if (Misc.getShrinesInArea(p, 15, true)) {
					break;
				}
			}
		}
		Town.goToTown(1);
		ShrineStatus = true;
	}

**Comment by theBGuy** [comment]
It's a d2bs bug, where the frozen state doesn't get released. A new game fixes the issue. However, poorly written code can also cause the engine to freeze up as well. Either way, closing this out as it's a repeat of another issue and not kolbot related anyway.
