### ISSUE TITLE
How to set auto pickit when i use D2BotMap config

### ISSUE THREAD

**Issue by ly19811105** [blizzhackers/kolbot#273]
I'm a newer on Kolbot. I just want to set the bot to auto pick it everything. How to set on this.thanks.

**Comment by gtoilet** [comment]
this thread should help you

https://github.com/kolton/d2bot-with-kolbot/issues/1445

**Comment by ly19811105** [comment]
https://github.com/kolton/d2bot-with-kolbot/issues/1445#issuecomment-739416138

i have found the problem:
blizzhackers/kolbot#158

i deleted "&& item.itemType !== 4" in Pickit.js and now it works. lol. - maybe my pickit worked all the time, but i always was looking at picking up gold to check if it works.

after this setting will pick the gold.thanks.
