### ISSUE TITLE
Slow character movement

### ISSUE THREAD

**Issue by Phnmz** [blizzhackers/kolbot#274]
After a few mins the character movement gets slower and slower... why?

**Comment by Phnmz** [comment]
This is not happening from an older version of kolbot, don't know what you guys did exactly but it would be the issue.

**Comment by Zolzen** [comment]
I have the same problem.
But after removing my "cd-key" setup in profile it seem to work for some reason.
makes it a little harder to use multiple cd keys tho.

**Comment by Zolzen** [comment]
> > But after removing my "cd-key" setup in profile it seem to work for some reason.
> 
> how did you set the profile keys, raw or loader(mpq files) ?

i set it Raw, but apparently only helped a couple of hours.

**Comment by jaenster** [comment]
Slow... Sorry i gonna need more information to go on. What do you actually mean. Its not running? It stucks on walking? The game is barely responsive and the game runs slowly cuz of it? You lag out of the game? What you actually mean.
