### ISSUE TITLE
Diablo Helper stuck at chaos

### ISSUE THREAD

**Issue by mato89** [blizzhackers/kolbot#278]
I'm having problems with running Diablo / Diablo helper from time to time:

Sometimes there will be seals my leader can't open:
[10/11/21 11:20:50] D2BS 45240: ÿc1Error in ÿc0Diablo ÿc1(default.dbj line ÿc198): ÿc1too much recursion

The leader would then head to baal and the diablo helpers would wait in chaos forever casting attacks, waiting for the main to come back and open seals. Is there anyway to check every few iterations if leader is at baal?

**Comment by theBGuy** [comment]
Config.DiabloHelper.SkipIfBaal = false; // End script if there are party members in a Baal run.

**Comment by theBGuy** [comment]
Config.DiabloHelper.SkipIfBaal = false; // End script if there are party members in a Baal run.
