### ISSUE TITLE
unit.getSkill levels wrong way round.

### ISSUE THREAD

**Issue by mato89** [blizzhackers/kolbot#279]
My sorc is not precast chilling armor because it has +2 in chilling armor (snowclash) with no hard points in either shiver/frozen/chilling armor.

Upon looking at Precast.js, I find that the skill checks are all written as `me.getSkill(60, 0)` for chilling armor. This seems to be true for other skills as well.

I find that me.getSkills(60,0) gives me the base level of chilling armor. getSkills(60,1) gives me the level including items.
This seems to be different way round from what the docs (commandRef.htm, below) say.

    unit.getSkill
     ...
     ** If you use getSkillLevel, use SkillID instead of the above mode list to get the getSkillLevel info
    
    getSkillLevel:
    Syntax:
    String OR int = unit.getSkill( int mode|skillId [, int getSkillLevel] );
    0 - will return the full skill level, all +skills calculated
    1 - will return only the base level of the skill (no bonus to skills added)

Did some update to this function break the original intention of all these precast skill checks? Or are there situations where you want to check by hardpoints only? I find that checking skills by the total level makes more sense to me hence I'm going to make a pull request.

**Comment by mf022** [comment]
feel free to complete a PR with precast add-on
