### ISSUE TITLE
Failed to include script: Battle Orders Err133, syntax Error

### ISSUE THREAD

**Issue by Grimelife1** [blizzhackers/kolbot#284]
Hi, I'm not sure what happened here. At first the barb would go wait in Cat2 and give BO. Now I get this error everytime I launch a game. The only thing I tried to edit in the battleorders.js script was deleting the overhead msg of "waiting for players. I'm running the Diablo script. The barb also use to wait in town for the cs tp but now he goes through RoF. I have a mess.

**Comment by mf022** [comment]
duplicate with forum post <https://blizzhackers.discourse.group/t/failed-to-include-script-battle-orders-err133-syntax-error/1434>
