### ISSUE TITLE
Error #222 - When Creating Open Battle.Net Game

### ISSUE THREAD

**Issue by kgcjr** [blizzhackers/kolbot#285]
Tried to search the web for a solution but couldn't find any helpful information about running a Single Player character with D2BS-Kolbot on Open BattleNet. When I start my character profile (using my single player character), the bot gets stuck trying to create a game. The D2BS Console displays [Error (222)] File(kolbot\d2botlead.dbj:532) TypeError: control is undefined...

I opened the entry script D2BotLead.dbj and went to Line #532 in NotePad++ to see if there was anything obvious or if there was something on my end. Looks like the issue may be related to the D2BotLead script code area of Create Game/Set character differences. I noticed on the D2 game screen that the Max. Number of Players and Character Difference options were "greyed" out. Usually they display 8 & 99 respectively when I create a Battle.Net game using one of my BNET characters. I also tried one of my BNET characters to see if that would work; no go.

I'm a novice Javascript programmer at best, so I'm stuck. Any suggestions?

![146066465-632021fd-e8a7-4fb0-8016-8ccab478e609](https://user-images.githubusercontent.com/95705249/146825790-58c549db-7e1e-4a36-856e-0f0a0b2b9cb9.png)

**Comment by jaenster** [comment]
As you can see in the [code](https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/D2BotLead.dbj#L531)(line 531). 


```javascript
		// Set character difference
		if (typeof StarterConfig.CharacterDifference === "number") {
			if (control.disabled === 4) {
				ControlAction.click(6, 431, 341, 15, 16);
			}

			ControlAction.setText(1, 657, 342, 27, 20, StarterConfig.CharacterDifference.toString());
		} else if (StarterConfig.CharacterDifference === false && control.disabled === 5) {
			ControlAction.click(6, 431, 341, 15, 16);
		}
```

it tries to set the character difference, which is impossible on open battle net

**Comment by kgcjr** [comment]
Can someone update or modify the D2BotLead script to bypass or ignore the "set character difference" code and simply open a game as it does in closed Battlenet? I'd do it if I knew how...

**Comment by kgcjr** [comment]
Can one of the maintainers modify the script to test for Open Battenet, and bypass the character difference code and go straight to the Make Game script?  If I was able to I would do it, but I do not possess the expertise to do this myself. Thank for your reply and quick response.
________________________________

**Comment by theBGuy** [comment]
Or instead of someone doing that why don't you read the starterconfig property descriptions. Specifically `CharacterDifference: 99, // Character level difference. Set to false to disable character difference.`

**Comment by theBGuy** [comment]
// Set character difference
		if (typeof StarterConfig.CharacterDifference === "number") {
			if (control.disabled === 4) {
				ControlAction.click(6, 431, 341, 15, 16);
			}

			ControlAction.setText(1, 657, 342, 27, 20, StarterConfig.CharacterDifference.toString());
		} else if (control && StarterConfig.CharacterDifference === false && control.disabled === 5) {
			ControlAction.click(6, 431, 341, 15, 16);
		}
		
Enjoy, replace yours with this.

**Comment by kgcjr** [comment]
Thank you BGuy!  You're the best!

**Comment by kgcjr** [comment]
That was one of first things I tried, but it didn't work for me.  I am using the latest Blizzhackers/kolbot release.

Also, I do my research and try to do as much as I can understand before I ask a question like this.  Unfortunately, my Javascript & C++ programming skills aren't high enough level to fully understand (and reverse engineer) the Kolbot script code I'm looking at (but I'm working on it by taking Javascript & C++ courses).

Specific statements like ControlAction.click(6, 264, 366, 272, 35) and ControlAction.setText... are somewhat confusing to me.  I suppose the function(s) are referring to screen positions? or some memory locations.  When forum comments say "just read the comments", I'm sure you'll agree with me that the Kolbot program-action scripts were not written with a lot of clear comment detail, and for a newbie to try and understand.

This is why I want to  get the Open BattleNet mode working, so I can experiment and modify the scripts without getting my account(s) banned.  I use the single-player mode for some things, but I need to be able to have multiple characters in the same game for Lead/Follower, Muleing, Mulelog testing and mods. I also tried TCP-IP and that's not working correctly for me either.  I can create a game with one character, but other subsequent characters can't join because they cannot find the IP to join the leader's game...

So I've tried, and I'm getting closer, and learning a lot.  That's all part of the process.

Thanks for your reply and response, every little bit it helps.

**Comment by theBGuy** [comment]
You need to also set the character difference to false in the starter config per the property description

**Comment by theBGuy** [comment]
If you're really trying to learn then read through
https://github.com/noah-/d2bs
this explains all those built in functions. The rest of kolbots library's are pretty well commented on what each thing is doing but absolutely experimenting is the best way to learn how everything functions together

**Comment by kgcjr** [comment]
"... set the character difference to false in the starter config per the property description" ... I do not understand what this means.  I looked for StarterConfig variable definition statements and could not find any property description fields or statements to change to "false".  Can you point me in the right direct or provide sample code? Thx.

**Comment by kgcjr** [comment]
NVM - I found it and it works!  I was able to get D2Bot to create a new game in Open BattleNet.  

var StarterConfig = {
	MinGameTime: 120, // Minimum game length in seconds. If a game is ended too soon, the rest of the time is waited in 
 the lobby
	PingQuitDelay: 30, // Time in seconds to wait in lobby after quitting due to high ping
	CreateGameDelay: 10, // Seconds to wait before creating a new game
	ResetCount: 999, // Reset game count back to 1 every X games.
	**CharacterDifference: false, // Character level difference. Set to false to disable character difference**


Next I want to try to see if I can get AutoMule and Mulelogger to work in OBNET just as I have it working in Closed BNET.  Also, I'll do some research to find out how I can create and code a pseudo-breakpoint function for Javascript, so I can short-step or single-step through the JS bot scripts to learn more about how the D2BS-Kolbot system works as a whole.

Thanks BGuy for your help and time!
