### ISSUE TITLE
AutoMule & MuleLogger for Open BattleNet

### ISSUE THREAD

**Issue by kgcjr** [blizzhackers/kolbot#286]
Set up a Single Player character to create an Open BattleNet game and "item find".  I also configured AutoMule.js and Mulelogger.js to mule and log this SP character (I have used AutoMule and Logger effectively before in Closed BattleNet characters, so I am familiar with how to use it).  When in a game and a manual mule request is activated (Numpad 5) in the Open BattleNet game, the mule character activates, but creates new game in Closed BattleNet only (instead of Open BattleNet).  Obviously, the Mule could not signal the SP character to join the mule game and thus times out.

I notice there is no option in AutoMule.js to select or specify an Open BattleNet game for the SP character being muled and logged (just options to select the realms).  I believe that the D2BotMule and D2BotMuleLog files may need to be modified or updated with an option to create Open Battlenet mule games (along with the Closed Battlenet mule games), or possibly this could be done automatically based on what mode is selected in the D2Bot Character Profile "Mode" configuration.

I've reviewed the AutoMule, Mulelogger, D2BotMule, and D2BotMuleLog script files to see if I could make any of the necessary changes, but this is way beyond my scripting capabilities.

Anyone have any helpful suggestions or recommendations, or can any of the active developers take a look at this and make these needed changes?

Thanks.

**Comment by kgcjr** [comment]
Can someone please take a look at this.  I'd like to use Kolbot on Open BNet to make some mods on the AutoMule, Mule Logger, Leader/Follower scripts without running the risk of getting my D2 Keys banned on closed BNET.  Since Open BNET uses the local single player characters and runs on the local computer, there shouldn't be any risk of getting my keys banned.  Thanks.

**Comment by theBGuy** [comment]
Pretty sure the risks are the same, you are still connecting to bnet when using open or closed.

**Comment by kgcjr** [comment]
If I’m on the BNet servers when using Open BNet, I agree.  But it’s my understanding that the servers aren’t used in Open BNet (of course I could be wrong).  I think I’ll post a question on the Blizzard forum about Open BNet only and see if I get a response…

BTW may I contact you on a PM to ask you a few specific questions about D2BS Kolbot? I’ll do my best I not to take too much of your time (as time is valuable to all of us).  I’d be appreciated.  Thanks in advance.
