### ISSUE TITLE
ReferenceError: Attack is not defined during manual play

### ISSUE THREAD

**Issue by scprotz** [blizzhackers/kolbot#287]
While playing, after a certain time (I'm not sure about the trigger causing it), I will get:
[Error (1) ] File(kolbot\libs\common\pather.js:420) ReferenceError: Attack is not defined

If tried changing my attacks from -1 to 0 and also to my class specific attacks (sorceress), but doesn't change.

I am using D2BotMap.dbj with pickit enabled in my character file.  I even also tried to check for 'Attack' on line 420:

if(Attack && Attack....), but still same error.  Any ideas?

**Comment by scprotz** [comment]
Here is a config for my blizzard sorceress.

[Sorceress.BlizzardSorc.js.txt](https://github.com/blizzhackers/kolbot/files/7927238/Sorceress.BlizzardSorc.js.txt)

**Comment by mf022** [comment]
> Sorceress.BlizzardSorc.js.txt

Have you try to set line 17 to ... ?
```
	Scripts.UserAddon = false;
```

only Config.AttackSkill[1] and Config.AttackSkill[3] have to be set

and in lines 514-515 let those lines like [default](https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/config/Sorceress.js#L513-L514).




> While playing, after a certain time (I'm not sure about the trigger causing it), I will get:
> [Error (1) ] File(kolbot\libs\common\pather.js:420) ReferenceError: Attack is not defined

Are you able to play it for a while?

**Comment by scprotz** [comment]
I tried the suggestions, but still same issues.

**Comment by scprotz** [comment]
One extra note is that once I receive the error, pickit seems to stop working.

**Comment by mf022** [comment]
maybe you should test <https://github.com/blizzhackers/documentation/blob/master/kolbot/ManualPlay.md/#manualjs> to see if you get the same error.

did you test other class heroes?

**Comment by scprotz** [comment]
Ok, so I reinstalled and went through all the steps again.  Testing as I made a change.  It appears that I get the failure if I have Config.ManualPickPlay = true and   Config.NoTele = false;

With these two both enabled, I get the error.

**Comment by mf022** [comment]
> Config.NoTele = true;

If you manually control the hero, this couldn't be like default **= false** ?

**Comment by scprotz** [comment]
> > Config.NoTele = true;
> 
> If you manually control the hero, this couldn't be like default **= false** ?

If I manually control the hero but have Config.NoTele = false, then with pickit enabled, my character will switch my alt (right click) to Tele and jump into a pack of mobs.  This is not ideal because on a blizz sorc, my alt needs to be blizz.  If the script were to switch to tele, jump, pickit, and then switch back to prior alt, that'd be ok, but right now, it makes it unplayable because you get dropped into a set of mobs with no alt at seemingly random times.

**Comment by mf022** [comment]
> maybe you should test https://github.com/blizzhackers/documentation/blob/master/kolbot/ManualPlay.md/#manualjs to see if you get the same error.

Did you test Manual.js with "Pick to inventory" option?

**Comment by scprotz** [comment]
I tried setting up Manual.js.  It never seems to load ( it's as if I'm running D2BotBlank all by itself).

I followed these instructions:

- copy the script Manual.js and save it as ...\libs\bots\Manual.js
- in your character's config add "Scripts.Manual = true;" (that can be near the line "Scripts.Follower = ...")
- use D2BotBlank.dbj as starter script(entry point) for the profile.
- in d2bs.ini (located in ...\kolbot\d2bs) you should set "UseGamePrint=true", otherwise you won't see anything useful in game.

But am not seeing anything in game.

**Comment by scprotz** [comment]
An extra comment.  It seems like this only happens when playing manually and when pickit is on, but also seems to trigger quite often when I'm holding down the shift key (i.e. Hammerdin with no tele).  It is definitely a pather problem when no tele is available, but seems to happen more often when shift is engaged (could just be coincidence due to timing though).

**Comment by theBGuy** [comment]
Can you update you files and tell me if this still happens? I re-worked manual mode, and so far haven't seen this error

**Comment by jaenster** [comment]
I think the problem is that it tries to pick an item, but monsters are in the way (which is less of an issue with teleporting), and it tries to clear the path, as kolbot tries to be smart and does things for you. Which it shouldn't in this case.

An easy fix is to add an include of Attack somewhere, but its a bit tricky as you need the proper init function as you can be say a wearwolf and need to load that
