### ISSUE TITLE
strict warning error misc.js line 2009 and loader.js line 54

### ISSUE THREAD

**Issue by JPL56** [blizzhackers/kolbot#288]
strict warning referenced from line 54 of loader.js
 				copy[i] = this.clone(obj[i]);
			}
strict warning referenced from line 2009 of misc.js
				copy[i] = this.clone(obj[i]);
			}

**Comment by jaenster** [comment]
Strict warnings are annoying because technically it's not incorrect and/or a big deal in modern javascript.

Its compiled with a too strict setting, which is not something we can change easily. 

Do you use custom configs somewhere for scripts?

**Comment by JPL56** [comment]
i think these are default files

**Comment by jaenster** [comment]
> i think these are default files

And its coping your config, so please share your config

**Comment by JPL56** [comment]
my paladin config file?
he is the one with those 2 strict warnings

**Comment by JPL56** [comment]
This text window didn't allow to drop the file so the colors and line numerals aren't present. Sorry

**Comment by jaenster** [comment]
You messed up the AttackSkill[6] on line 509, it suposed to be [5].

Its trying to write to an element that doesnt exists

**Comment by JPL56** [comment]
thanks

**Comment by JPL56** [comment]
I don't recall changing that number but both warnings discontinued 👍

**Comment by JPL56** [comment]
I did after I looked at my paladins past and found a line missing. I must have hit backspace after highlighting the line.
No more strict warning messages but it still wont follow as mfhelper. If I dig through past working configs I might find that issue.
