### ISSUE TITLE
D2BotGameAction and limedrop

### ISSUE THREAD

**Issue by Fa-b** [blizzhackers/kolbot#29]
Since this appears to be the new 'active' repo regarding kolbot I will from now post here when I find something.

[this](https://github.com/blizzhackers/kolbot/blob/a8f4904969533ce6fb4c3fb0aeecf681410505f3/d2bs/kolbot/D2BotGameAction.dbj#L583) line appears to be a copy paste bug.
I started testing limedrop and the first thing I tested was the behaviour of the script when the game to join does not exist. Unfortunately after failing to join the game, the bot created a game (according to the profile setup) and happily dropped the specified items there :). Of course I was clever enough to choose 'Key of Destruction' as my mules are full of those.
Anyways. Should be:
```js
    ControlAction.click(6, 652, 469, 120, 20);
```

instead.

**Comment by mf022** [comment]
in comparison with D2BotFollow, on the
```javascript
	case 28: // Lobby - Game Does Not Exist
```
we have there line [801](https://github.com/blizzhackers/kolbot/blob/a8f4904969533ce6fb4c3fb0aeecf681410505f3/d2bs/kolbot/D2BotFollow.dbj#L801) with a 30 seconds delay (not 5 seconds like in D2BotGameAction.dbj), and  line [804](https://github.com/blizzhackers/kolbot/blob/a8f4904969533ce6fb4c3fb0aeecf681410505f3/d2bs/kolbot/D2BotFollow.dbj#L804) with 
```javascript
		lastGameStatus = "ready";
```
maybe that line 804 should be there instead clicking join

If you don't wanna create games at all by limedrop profile, the [case 4 // Create Game](https://github.com/blizzhackers/kolbot/blob/a8f4904969533ce6fb4c3fb0aeecf681410505f3/d2bs/kolbot/D2BotFollow.dbj#L389-L390) from D2BotFollow should be used in [D2BotGameAction.dbj](https://github.com/blizzhackers/kolbot/blob/a8f4904969533ce6fb4c3fb0aeecf681410505f3/d2bs/kolbot/D2BotGameAction.dbj#L243-L270)

**Comment by Fa-b** [comment]
I was thinking of implementing a way the user can decide about that from the web GUI. Don‘t have access to the api server‘s api though :/

**Comment by mf022** [comment]
the changes for D2BotGameAction to not create games were added in https://github.com/blizzhackers/kolbot/pull/39
