### ISSUE TITLE
enabling new items

### ISSUE THREAD

**Issue by treeharl** [blizzhackers/kolbot#290]
Greetings,

I would like to add several new items in my kolbot config, but I am simpely stumped at this point. Such an item would be for example a Re Rune which I code with r34. Ofcourse r34 has been added to misc.txt treasueclassEX.txt and injected with a MPQ editor. Obvously I tested this by hand and it drops. Next is trying to configure it in kolbot. 

First step I made was directly enable it in a pickit directly with this line.

[name] == rerune 

Obviously this resulted in an error as this name is not defined.

Step two is creating an entry in NTItemalias.dbl
On line 764 I added the following
NTIPAliasClassID["r34"] = 659;  NTIPAliasClassID["rerune"] = 659;

I also added in config\libs.js on line 1329 whereas I defined r34 as High Rune to get it logged.

Next I added a string value to LocalestringID where I added on line 7794 the following:
"r34": 24122,

The program still doesn't seem to reconise r34 at this point and I am clueless what I am doing wrong. Whenever r34 drops I see it on screen but the bot doesn't pick it. When I take r34 and put it in to a character inventory it is being dropped at the start of a run. Funny enough it still qualifies in the eventlog as Re Rune appears being logged as dropped from the character.

Any Ideas?

**Comment by aim2kill** [comment]
Instead of [name] == rerune, try [name] == re rune
