### ISSUE TITLE
Error in Questing

### ISSUE THREAD

**Issue by changchangd2** [blizzhackers/kolbot#292]
I've been having this issue when trying to use the questing function and I have no idea what is going on. I've tried generating a new character config and tried starting from a fresh installation, but I'm not sure where to go from here. Here is the error I get:

"Error in Questing (questing.js #353) Packet.checkQuest is not a function "

**Comment by theBGuy** [comment]
I'll have this fixed in a couple minutes, it seems during my recent updates the checkQuest function didn't get added or got deleted because I could of sworn that I added it.

**Comment by changchangd2** [comment]
Thanks, just happy I didn't mess things up. Really, really great work on this project!

**Comment by theBGuy** [comment]
Alright just pushed the update for this and some other issues.
