### ISSUE TITLE
Gambling?

### ISSUE THREAD

**Issue by changchangd2** [blizzhackers/kolbot#293]
There used to be a gambling section in the character config that I can't seem to find anymore. I thought that maybe the gambling system was supposed to be used for that, but after reading the documentation it seems like that's another thing entirely. Is there a new way to have a character gamble like the old "Config.Gamble = true;"? I tried looking through past issues, but I can't find anything. Any help would be appreciated!

**Comment by theBGuy** [comment]
Oh, I'm so sorry looks like I deleted that section while rearranging the config files, the settings still work
```
	// Gambling config
	Config.Gamble = false;
	Config.GambleGoldStart = 1000000;
	Config.GambleGoldStop = 500000;

	// List of item names or classids for gambling. Check libs/NTItemAlias.dbl file for other item classids.
	Config.GambleItems.push("Amulet");
	Config.GambleItems.push("Ring");
	Config.GambleItems.push("Circlet");
	Config.GambleItems.push("Coronet");
```
I'll have the configs updated in a bit to add that back in.
