### ISSUE TITLE
Paladin "(paladin.js #114) timedSkill is not defined"

### ISSUE THREAD

**Issue by changchangd2** [blizzhackers/kolbot#295]
Hi, I noticed this error with the paladin attack file in the console and it seems to be angry that there isn't a timed skill section in the paladin character config, which just has an aura section instead. I'm not sure how to fix this for myself, so I thought I'd ask! The recent changes to this project and soloplay are incredible!

**Comment by theBGuy** [comment]
Thank you for posting this, it seems during the last update to class attacks I made a bade copy and paste over the paladins doCast function. I'll have this fixed and uploaded in a little bit
