### ISSUE TITLE
MaxQuantity

### ISSUE THREAD

**Issue by xWickedx420** [blizzhackers/kolbot#30]
Anyway to add MaxQuanity to pickit files for items? I can’t seem to figure it out, I write something, it gets accepted by pickit, then it doesn’t happen.

**Comment by mf022** [comment]
Did you [update you files](https://github.com/blizzhackers/documentation/blob/master/d2bot/Download.md#keep-bot-files-updated)? 
It was implemented a fix for MaxQuantity - https://github.com/blizzhackers/kolbot/pull/20

Is the [older repository](https://github.com/kolton/d2bot-with-kolbot/) working for ## [maxquantity] == x ?
Do you get these issues after you updated your files?

**Comment by xWickedx420** [comment]
Yes I updated, still having the same issues, but ignores quantity

**Comment by xWickedx420** [comment]
Currently pickit I’m using is the following

*Example

[Name] == KoRune
[MaxQuantity] == 2 && [Name] == KoRune

**Comment by jaenster** [comment]
The problem is, maxquantity is a setting for the third field of a pickit.

So, its,
[Whatever] # # [maxquantity] < 3

There are some great examples in the included kolton nips =)

**Comment by mf022** [comment]
@xWickedx420 
you should check https://github.com/blizzhackers/pickits/blob/master/NipGuide.md/#format-of-the-nip-lines
