### ISSUE TITLE
Necromancer not cursing

### ISSUE THREAD

**Issue by changchangd2** [blizzhackers/kolbot#300]
I'm having an issue where my summon necromancer is not using any curses on any kind of monster, boss or otherwise. My curses are specified in line 507 and 508, and I've set the attack skills to 500 on lines 454 and 456 according to Attacks.txt in the config>Templates folder. I've tried turning packet casting on and off just to see if i'm not noticing the animation, and in both cases there is still no cursing. Not sure where to go from here or what I'm doing wrong. I'm using the most recent config file for the necromancer. Everything else but cursing works.

**Comment by theBGuy** [comment]
Was missing a ! in the return statement for canCurse
