### ISSUE TITLE
(precast.js #106) Attack.weaponswitch is not a function

### ISSUE THREAD

**Issue by changchangd2** [blizzhackers/kolbot#303]
I've been getting this error with some of my characters for every single area.

For example, the full line is:
"Error in Diablo (precast.js #106) Attack.weaponswitch is not a function"

**Comment by Ricola3D** [comment]
For info, the error seems to come from commit "085e290c5f - Little bit of cleanup and typo fixes" 23 days ago.

There is a missing capital letter on the "S" of switch, it should be "Attack.weapon**S**witch"

**Comment by theBGuy** [comment]
Thank you, I'll have this fixed soon
