### ISSUE TITLE
How to solve this error please? 

### ISSUE THREAD

**Issue by wcg928** [blizzhackers/kolbot#306]
D2BS is not responding... starting profile
Crash Info: Script: Diablo Area: Chaos Sanctuary
Login Error - Battle.net is not responding. Please try connecting again in a few minutes.

thx!

**Comment by theBGuy** [comment]
Looks like you crashed during diablo, then failed to connect back to the servers. It's impossible to tell anything else with the absolute lack of information provided.

**Comment by wcg928** [comment]
> > D2BS is not responding... starting profile
> 
> did you checked the FAQ ... https://github.com/blizzhackers/documentation/blob/master/kolbot/FAQ.md/#d2bs-is-not-responding--starting-profile?

thank you very much
