### ISSUE TITLE
wind druid precast error

### ISSUE THREAD

**Issue by saleen275** [blizzhackers/kolbot#310]
fresh wind druid made..throwing out error (206)] File(Kolbot\libs\common\precast.js:216) delay(0) called. argument must be >= 1 constantly.....and also swapping back and fourth between hoto/cta constantly

**Comment by theBGuy** [comment]
You've got all updated files? The line in question causing the error shouldn't be possible to be less than zero. I wrote it this way specifically for that. 
`delay(1 + seconds(me.castingDuration(skillId)));`

**Comment by saleen275** [comment]
yea i downloaded all of em..every other char works fine except wind druid..my pally is working perfect

**Comment by saleen275** [comment]
also just noticed windy is not casting BO eaither

**Comment by theBGuy** [comment]
Update I just pushed should fix this

**Comment by saleen275** [comment]
yep..works like a charm now...appreciate man thanks

**Comment by saleen275** [comment]
well that fixed that but now im having an issue with its constantly swapping back and fourth from hoto to cta and BOing but only the druid is doing it

**Comment by theBGuy** [comment]
Is this all in the same game? If its actually casting bo but still continually swapping that sounds like its failing to update its state.

**Comment by saleen275** [comment]
yea i restarted and it it worked fine after u updated that...now it goes in game...goes to wp and BO and stuff then teles to the pit like i want it to then once in the pit its starts to teleport and then it swaps to CTA and BO then back to cta and teleports and casts a tornado..then swaps back to cta and does samething agian constantly

**Comment by theBGuy** [comment]
I can't seem to replicate, I just hero edited a druid and had him run some scripts. He casts once during then casts again after summons but then runs fine. Only thing I noticed is it actually gets into the the precastCTA function way more than I realized so I need to improve the pre check

**Comment by saleen275** [comment]
seems like after its made a new game its not doing it now
