### ISSUE TITLE
Ctrl + Click to move to inventory

### ISSUE THREAD

**Issue by hutber** [blizzhackers/kolbot#313]
A feature request, it would be easily possible to write a script for some quality of life improvements?

**Comment by theBGuy** [comment]
this is already done in map mode

**Comment by hutber** [comment]
:O! I'll need to start loading in map mode then! lol Sorry and thank you

**Comment by theBGuy** [comment]
Just to note though, in map mode you just hover over the item and press Ctrl. No mouse click

**Comment by hutber** [comment]
Ahh even better tbf lol
