### ISSUE TITLE
BattleOrders only casts shout

### ISSUE THREAD

**Issue by micr0Mo** [blizzhackers/kolbot#315]
I forked it completly fresh and only tried a barb as MFLeader and a sorc as follower. But battleorders did not work, barb only casts shout serveral times until failtimer. After that, he runs casts shout runs casts shout. If I look at my sorc, the barb seems to do nothing, no shouts at all. Anyone faced problems like that?

I used an older bot version where everything works fine. 
Charconfig is new, BO settings as explained here. 

Barb:

	// Battle orders script - Use this for 2+ characters (for example BO barb + sorc)
	Scripts.BattleOrders = true;
		Config.BattleOrders.Mode = 0; // 0 = give BO, 1 = get BO
		Config.BattleOrders.Idle = false; // Idle until the player that received BO leaves.
		Config.BattleOrders.Getters = ["SorcIngameName"]; // List of players to wait for before casting Battle Orders (mode 0). All players must be in the same area as the BOer.
		Config.BattleOrders.QuitOnFailure = false; // Quit the game if BO fails
		Config.BattleOrders.SkipIfTardy = true; // Proceed with scripts if other players already moved on from BO spot
		Config.BattleOrders.Wait = 20; // Duration to wait for players to join game in seconds (default: 10)

Sorc:

	// Battle orders script - Use this for 2+ characters (for example BO barb + sorc)
	Scripts.BattleOrders = true;
		Config.BattleOrders.Mode = 1; // 0 = give BO, 1 = get BO
		Config.BattleOrders.Idle = false; // Idle until the player that received BO leaves.
		Config.BattleOrders.Getters = ["SorcIngameName"]; // List of players to wait for before casting Battle Orders (mode 0). All players must be in the same area as the BOer.
		Config.BattleOrders.QuitOnFailure = false; // Quit the game if BO fails
		Config.BattleOrders.SkipIfTardy = true; // Proceed with scripts if other players already moved on from BO spot
		Config.BattleOrders.Wait = 20; // Duration to wait for players to join game in seconds (default: 10)

**Comment by micr0Mo** [comment]
Hey. Yes he has got hard points and Config.PacketCasting is = 0;

**Comment by theBGuy** [comment]
Alright found the issue, thank you for bringing this to my attention. There was a typo in Misc.js
