### ISSUE TITLE
[allres] ?

### ISSUE THREAD

**Issue by tlwh163** [blizzhackers/kolbot#34]
let allres = [1, 1, 1, 1];
	let min = Math.min.apply(null, allres);
	allres = allres.map(res => res > min ? min : res);
	let [fire, cold, light, psn] = allres;
	//return fire === cold === light === psn ? min : 0;
	me.overhead(fire === cold === light === psn);  //false

**Comment by jaenster** [comment]
Solved it, thanks

**Comment by tlwh163** [comment]
Maybe it can be:

case 555:
return Math.min.apply(null, allres);
case xxx:
