### ISSUE TITLE
Some things i noticed

### ISSUE THREAD

**Issue by tyson-dev** [blizzhackers/kolbot#341]
#1 The Superold problem with slow walking speed / slowing down walking speed over time.
Please gieb link to anything helpful on that ( ports to open? tcp 4000, 6112 open here i think).
It appears to be better with packet casting disabled, but w/o packet casting a little rubberbanding now and then seems to occur.
I used to eliminate the rubberbanding issues with port forwarding though in the past.

Maybe related to some lag-spikes which are noticeable after leaving harrogath or after getting a wp ( short stuttering / framedrops )
I can try to help out but i have to get into debugging first.

#2 Hammerdin : incosistent use of charge while moving around w/o eni, sometimes he does use it after opening a door itself or clicking a waypoint manually or pausing the bot for a while. Most of the time he's not using charge (e.g. in script "trying to get waypoint")

#3 Hammerdin Position on barricaded door (e.g. Frozen Tundra, no eni). Hammering the walls here for a while before moving closer to doors (happens e.g when getting wp for anci script).

#4 Hammerdin w/o eni not attacking while movement is blocked by enemies ( anywhere ). Basically jsut trying to move when surrounded by enemies, could use primary and secondary instead i think. I guess this is applies to all chars / pathing w/o tele.

**Comment by theBGuy** [comment]
1) d2bs problem that isn't going to be fixed
2) Charge is used when the distance to spot is > 8
3) 🤷‍♂️ Positioning does still need work
4) Walking characters will first try to move to location, if it fails then they attack to clear path.
