### ISSUE TITLE
Chickens and Death's with expired BO

### ISSUE THREAD

**Issue by tyson-dev** [blizzhackers/kolbot#344]
Still a lot of Chickens and Death's with expired BO ( bo-time should be calculateable and could be reapllied in between fights like 10 secs before expiring? like a rebo flag which executes before the next move-section?, bots gotta know when enemies are around so probably don't weaponswitch or bo then )

Edit: Probably .healStatus related. Seen her gamble with poison so life may go down to chicken before reentering tp. Turned .healstatus to true, i'll check n report back.

editedit: still happens, 2 sorcs same game both unbo'd soulkiller death @ throne, so it looks like they didn't apply bo, cause they should easily still have bo when reaching dolls in baal script, death script says CS though????

run goes - WS>DIA>BAAL, 5 sorcs all self bo'ing

16:11:55 (runner1) Life Chicken (0/1268) to Undead Soul Killer in Throne Of Destruction. Ping: 47
16:11:55 (runner2) Life Chicken (0/1314) to Undead Soul Killer in Throne Of Destruction. Ping: 63
16:14:06 (runner1) You died in last game. | Area :: Chaos Sanctuary | Script :: undefined
16:14:06 (runner1) Experience decreased by 24318557
16:14:06 (runner2) You died in last game. | Area :: Chaos Sanctuary | Script :: undefined

**Comment by theBGuy** [comment]
Precast checks bo 30 seconds before it should expire. It is checked every time node action is called while pathing. Death message uses last recorded location an item was picked up so sometimes it's inaccurate.

**Comment by tyson-dev** [comment]
So will they skip precast if 30+ bo still and then eventually bo in the middle of fights?
Maybe enemy check before reboing/weapon switching in field.

Or can i force precast for each script regardless of remaining bo?

thanks alot m8

**Comment by theBGuy** [comment]
I can conceivably see adding a force precast config option.

**Comment by theBGuy** [comment]
Looking at the scripts, force precast is already part of them
