### ISSUE TITLE
no more dropping items with fieldId?

### ISSUE THREAD

**Issue by ajniles2012** [blizzhackers/kolbot#346]
just wondering if the newest version is able to drop items with using fieldid. i just fresh dl'd all the files set up a profile and char config and i would like to just identify and drop as im killing but it seems to be  identifying then filling inventory (skipping items it wants to pick up but is full) going to town to sell. everything.

iv tried adding config.lowgold to char config

why would it identify but not drop items?
[Sorceress.PropoFol.txt](https://github.com/blizzhackers/kolbot/files/10162801/Sorceress.PropoFol.txt)

**Comment by theBGuy** [comment]
I looked at Pickit.checkItem, my guess is the junk item check is causing it. If an item isn't wanted but it's already in the inventory it's kept to sell. Changing
```javascript
&& (unit.isInInventory || (me.gold < Config.LowGold || (me.gold < 500000 && Config.PickitFiles.length === 0)))) {
```
to
```javascript
&& ((unit.isInInventory && (me.inTown || !Config.FieldID.Enabled)) || (me.gold < Config.LowGold || (me.gold < 500000 && Config.PickitFiles.length === 0)))) {
```
Should fix it

**Comment by ajniles2012** [comment]
ahh yes, this did in fact fix the problem. thanks for your time!
