### ISSUE TITLE
coords to txt file

### ISSUE THREAD

**Issue by BartoszJedynak** [blizzhackers/kolbot#347]
Hi, after bot update i'v got error with  logging coords by numpad slash to text file(bot wont make txt file, can anyone check is that string is correct:

	     case sdk.keys.NumpadSlash: // - print coords
	     var dateString
             date = new Date(),
             h = date.getHours(),
             m = date.getMinutes(),
             s = date.getSeconds(),
             yyyy = date.getFullYear(),
             mm = (date.getMonth() +1),
             dd = date.getDate(),
             dateString = "[" + yyyy + (mm < 10 ? "0" + mm : mm) + (dd < 10 ? "0" + dd : dd) + "-" + (h < 10 ? "0" + h : h) + ":" + (m < 10 ? "0" + m : m) + ":" + (s < 10 ? "0" + s : s) +"]";
             me.overhead("Coords Succesfully Logged");
             FileTools.appendText("logs/Coords/" + me.charname + "-coords.txt","New Coord:([" + dateString + "][" + Pather.getAreaName(me.area) + "][" + me.x + ", " + me.y + "])" + "\n");
         

Thanks

**Comment by theBGuy** [comment]
```js
case sdk.keys.NumpadSlash: // - print coords
     var dateString <--- Missing comma
         date = new Date(),
         h = date.getHours(),
 ```
