### ISSUE TITLE
(Home made) PindleGarden script does not work anymore in current kolbot version

### ISSUE THREAD

**Issue by Machoclown** [blizzhackers/kolbot#348]
Hi,

Thanks for your efforts to continuing the development of kolbot.

In a previous version of kolbot I used a home made script (not by me btw) called pindle garden.
In the latest versions of kolbot that script doesnt work anymore.
The necro walks in and right out the Pindle Garden and don't raise the skellies what it suppose to do.
Hopefully you can help me with a hint or something because scripting skills are (very) limited.
The script is attached in a .txt version instead of .js.

Thanks in regard,

Machoclown
[PindleGarden.txt](https://github.com/blizzhackers/kolbot/files/10298370/PindleGarden.txt)

The Netherlands

**Comment by aim2kill** [comment]
Since is a custom script, did u add whatever is set in the old config to the new necro config?

**Comment by Machoclown** [comment]
Hi thanks for answering,


**This is the old script config:**
	Config.ExplodeCorpses = 74; // Explode corpses. Use skill number or 0 to disable. 74 = Corpse Explosion, 83 = Poison Explosion
	Config.Golem = 1; // Golem. 0 or "None" = don't summon, 1 or "Clay" = Clay Golem, 2 or "Blood" = Blood Golem, 3 or "Fire" = Fire Golem
	Config.Skeletons = "max"; // Number of skeletons to raise. Set to "max" to auto detect, set to 0 to disable.
	Config.SkeletonMages = 0; // Number of skeleton mages to raise. Set to "max" to auto detect, set to 0 to disable.
	Config.Revives = "max"; // Number of revives to raise. Set to "max" to auto detect, set to 0 to disable.
	Config.PoisonNovaDelay = 2; // Delay between two Poison Novas in seconds.
	Config.ActiveSummon = true; // Raise dead between each attack. If false, it will raise after clearing a spot.
	Config.ReviveUnstackable = true; // Revive monsters that can move freely after you teleport.
	Config.IronGolemChicken = 50; // Exit game if Iron Golem's life is less or equal to designated percent.

**This is the new one:**
	Config.ExplodeCorpses = 74; // Explode corpses. Use skill number or 0 to disable. 74 = Corpse Explosion, 83 = Poison Explosion
	Config.Golem = "Clay"; // Golem. 0 or "None" = don't summon, 1 or "Clay" = Clay Golem, 2 or "Blood" = Blood Golem, 3 or "Fire" = Fire Golem
	Config.Skeletons = "max"; // Number of skeletons to raise. Set to "max" to auto detect, set to 0 to disable.
	Config.SkeletonMages = 0; // Number of skeleton mages to raise. Set to "max" to auto detect, set to 0 to disable.
	Config.Revives = 0; // Number of revives to raise. Set to "max" to auto detect, set to 0 to disable.
	Config.PoisonNovaDelay = 2; // Delay between two Poison Novas in seconds.
	Config.ActiveSummon = true; // Raise dead between each attack. If false, it will raise after clearing a spot.
	Config.ReviveUnstackable = true; // Revive monsters that can move freely after you teleport.
	Config.IronGolemChicken = 50; // Exit game if Iron Golem's life is less or equal to designated percent.

Still the necro is not reviving any skellies.

**Comment by theBGuy** [comment]
Everything looks fine as far as I can tell, so your issue is you want it to make skellies from the prowling dead before they revive the first time?

**Comment by Machoclown** [comment]
> Everything looks fine as far as I can tell, so your issue is you want it to make skellies from the prowling dead before they revive the first time?

Correct, but instead of reviving the prowling dead to skellies the Necro runs in and out of the Pindle Garden, without reviving.
In previous version of Kolbot the Necro summons till max amount of skellies was reached.

**Comment by theBGuy** [comment]
Do you have attack skills set?

**Comment by Machoclown** [comment]
Yep, number 500 as adviced in the attact textfile.
But I will close this issue, because I will use the older version of kolbot where the pindlegarden script worked.

Thanks for you support.

Machoclown

**Comment by theBGuy** [comment]
Was just waiting to hear back, I know what the issue is. Since no attacks are performed, ClassAttack.afterAttack isn't run which is where the summons are raised outside of precast calls.
