### ISSUE TITLE
bot skips over everything but gold

### ISSUE THREAD

**Issue by LoonaWolf** [blizzhackers/kolbot#349]
I need a lil help, i have my bot programmed to pick up items and runes and i watched as it skipped over the runes i have it set to pick up. how do i fix this issue. ihave it set as:
[name] == FalRune # # [MaxQuantity] == 2
[name] == LemRune # # [MaxQuantity] == 2
[name] == PulRune # # [MaxQuantity] == 2
[name] == UmRune # # [MaxQuantity] == 2
Ive tried tweaking it in every which way possible and it still continues to skip over everything as if it never dropped. i also dont want it to sell runes.. i took a test rune and placed it in my inventory and it sold it.

**Comment by aim2kill** [comment]
Did u add the nip into that character config?

**Comment by LoonaWolf** [comment]
how would i do that?

**Comment by LoonaWolf** [comment]
> Did u add the nip into that character config?
how would i add the nip into character config and how do i keep the bot from selling stuff i want to keep such as runes?
