### ISSUE TITLE
Autoequip stashes item instead of equipping

### ISSUE THREAD

**Issue by ozkazuo** [blizzhackers/kolbot#35]
https://pastebin.com/NvGq5zyU - char config
https://pastebin.com/HVg39NCk - pickit

I have a druid using the follower script with the above pickit set up (druid.xpac.nip). Instead of equipping the items he finds, he instead just stashes them. He's level 5 with a plain quilted armor equipped and I have a +3 life magic leather armor in my inventory that I've been testing with. I have Config.AutoEquip set to true. 

After throwing some print statements around, I found that the `tier = NTIP.GetTier(items[0]);` line in Misc.js is returning -1. I'm still digging into the problem, but if someone could double check my config and make sure there isn't some syntax error or type, I'd appreciate it. Thanks!

**Comment by ozkazuo** [comment]
The problem seems to be in NTItemParser.dbl. NTIP_CheckList[i] is being mapped to typeFunc, statFunc, and wanted. However, those are not being used to check against the item in the below if statements. I replaced wanted with typeFunc and stat with statFunc. My druid now equips his armor.

`/** @return {function({Unit} item)} */
NTIP.generateTierFunc = function (type) {
	return function (item) {
		var i, tier = -1;
		// Go through ALL lines that describe the item
		for (i = 0; i < NTIP_CheckList.length; i += 1) {
			if (NTIP_CheckList[i].length !== 3) {
				continue;
			}
			let [typeFunc,statFunc,wanted] = NTIP_CheckList[i];
			if (wanted.hasOwnProperty(type) && wanted[type]) {
				try {
					if (typeof wanted === 'function') {
						if (wanted(item)) {
							if (typeof stat === 'function') {
								if (stat(item)) {
									if (wanted[type] > tier) {
										tier = wanted[type];
									}
								}
							} else {
								if (wanted[type] > tier) {
									tier = wanted[type];
								}
							}
						}
					} else if (typeof stat === 'function') {
						if (stat(item)) {
							if (wanted[type] > tier) {
								tier = wanted[type];
							}
						}
					}
				} catch (e) {
				}
			}
		}
		return tier;
	};
};`

**Comment by jaenster** [comment]
#40 

wrote a merge request to solve several issues.
