### ISSUE TITLE
My bot don't pick items and don't identification items

### ISSUE THREAD

**Issue by minolight** [blizzhackers/kolbot#352]
My bot don't pick items and don't identification items before sell
don't pick runs and pick keys like terror etc.
i don't now what happend. settings look normal
only picking money

**Comment by minolight** [comment]
Someone wanna help me ? Please

**Comment by theBGuy** [comment]
https://github.com/blizzhackers/pickits
https://github.com/blizzhackers/documentation/blob/master/kolbot/CharacterConfig.md/#character-configuration
