### ISSUE TITLE
Too high cpu usage when using continuous mule

### ISSUE THREAD

**Issue by diafree** [blizzhackers/kolbot#353]
I'm trying to use continuous mule because of the queue, but even if I use only one mule profile, the cpu usage goes up too much.
please suggest a solution

**Comment by theBGuy** [comment]
Not sure what to tell you, cpu usage of the mule profile I just started isn't any higher than normal

**Comment by diafree** [comment]
My AutoMule.js file configuration is as below and Diablo 2 running with that profile, CPU usage exceeds 40%


			// Trigger muling at the end of a game if used space in stash and inventory is equal to or more than given percent.
			usedStashTrigger: 90,
			usedInventoryTrigger: 80,

			// Mule items that have been stashed at some point but are no longer in pickit.
			muleOrphans: true,
			// Continuous Mule settings
			continuousMule:	true, // Mule stays in game for continuous muling. muleProfile must be dedicated and started manually.
			skipMuleResponse: false, // Skip mule response check and attempt to join mule game. Useful if mule is shared and/or ran on different system.
			onlyLogWhenFull: false // Only log character when full, solves an issue with droppers attempting to use characters who are already in game

**Comment by theBGuy** [comment]
https://github.com/blizzhackers/kolbot/tree/mule-fixes try this branch and let me know if it lowers it

**Comment by diafree** [comment]
I tested it, but the cpu usage is still high.

**Comment by theBGuy** [comment]
The current version for the mule-fixes branch should fix this.
