### ISSUE TITLE
D2BS not responding

### ISSUE THREAD

**Issue by fabznn** [blizzhackers/kolbot#362]
Hello!

Somehow, my bots stopped working and idk why.
They won't even start, its always typing:

04:30:20 (Barb) D2BS is not responding... starting profile
04:30:31 (Barb) D2BS is not responding... starting profile
04:30:43 (Barb) D2BS is not responding... starting profile
04:30:54 (Barb) D2BS is not responding... starting profile
04:31:06 (Barb) D2BS is not responding... starting profile

Can any1 help?

**Comment by maelstrm30** [comment]
Typical steps on remediation -
Reboot the system hosting/running Kolbot.
For me i double check and reinstall the pre-reqs (.net and c++ 2010 x86 it is mandatory required it must be c++ 2010 x86)
antivirus can cause issues, block certain files, or change/corrupt files
lastly, try making a new profile (dont clone) for the (Barb) and try again

**Comment by fabznn** [comment]
I really did read alot about it before i posted this.
I tried rebooting, i reinstalled those .net frameworks, a disabled my antivirus and i also made new profiles, i even tried a fresh install of the bot and copied my d2 folder onto my C platform.

nothing works. it still gets the same error on all my profiles.

**Comment by fabznn** [comment]
Ok, i
- deleted all my d2 copies
- cleaned my registry with ccleaner
- rebooted my pc
- deleted my whole kolbot folder
- cleaned my registry again
- reinstalled d2, logged onto bnet manually to get the update
- reinstalled kolbot
- renew'ed everything

now its working. i hope it stays stable. i dont know why this happened and all those steps were necessary. out of nothing
it worked fine before.
well, anyways - thanks for helping
