### ISSUE TITLE
Activate teleport skill animation when using bot

### ISSUE THREAD

**Issue by diafree** [blizzhackers/kolbot#366]
I want to turn on/off the animation as an option when using a skill like teleport

But other than precast, I can't find the option to activate the animation of the teleport skill.

Please tell me how to activate teleport skill animation

**Comment by theBGuy** [comment]
It's hardcoded to use packet casting as it is more stable that way. There isn't an option

**Comment by diafree** [comment]
Ok. I have no choice but to use the old version together to activate the teleport skill animation. Thank you for answer
