### ISSUE TITLE
No precast after getting the corpse

### ISSUE THREAD

**Issue by FxKrystal** [blizzhackers/kolbot#368]
Hi there, I've noticed a problem recently:
1. the char chickens out (it actually died)
2. in next game it will get the corpse => OK
3. since then no precast will be made (BO/HS) => NOK  I don't see any errors in the console

The char is a smiter with enigma, there shouldn't be any str bug and it can always successfully get the corpse.

**Comment by theBGuy** [comment]
[kolbot\restructure](https://github.com/blizzhackers/kolbot/commit/04e61f6080279e8af0921bd7563d7e27797851e3)

Should be fixed now in this branch

**Comment by theBGuy** [comment]
I meant to use that branch but I had also missed rechecking for cta after getting corpse. Which I just uploaded.
