### ISSUE TITLE
Correct installation guide is missing for Windows 11

### ISSUE THREAD

**Issue by tapakahxp** [blizzhackers/kolbot#371]
Hello, correct installation guide is missing for Windows 11.
Current guide is only leading to "D2BS is not responding... starting profile" message loop on Windows 11.

Is it possible to update guide ?
Or Kolbot only works inside Virtual Machine with Windows XP/7 OS Installed ?

**Comment by mf022** [comment]
Did you check compatibility tab for previous versions of Windows? And also set for all users to run it as admin?
