### ISSUE TITLE
Follower: Bots quit when dead

### ISSUE THREAD

**Issue by tapakahxp** [blizzhackers/kolbot#373]
My LifeChicken setting is set to 0 with follower bot, so bots wont leave boss fight and get a credit.
However, i set TownChicken to 30 and if they die, they leave game.
Conosole log: Failed to go to town.

![Screenshot002](https://github.com/blizzhackers/kolbot/assets/66036789/a9dc0527-2eec-412b-b212-8bea7f4aef55)

**Comment by theBGuy** [comment]
Yeah that makes sense, I have a saftey check for townchicken so bots don't die trying to townchicken. It just needs an additional check for lifechicken %

**Comment by theBGuy** [comment]
This is fixed now <https://github.com/blizzhackers/kolbot/commit/c14ca4c849e9252ad6f02db048dac6acf80f0f24>
