### ISSUE TITLE
Follower : Bots constantly going to town

### ISSUE THREAD

**Issue by tapakahxp** [blizzhackers/kolbot#374]
Bots constantly going to town to sell items, like as they had low gold option.
But Config.LowGold is not present in Config.

**Comment by theBGuy** [comment]
If you have less than 500k gold and have not loaded a pickit file. Items will be picked to prevent the bot from breaking due to gold

**Comment by tapakahxp** [comment]
If you start new game from scratch, all bots(followers and leader) will have 0 gold.
By the end of act 5 hell, they still have about 50k
So they spent most of time by selling items in city.

**Comment by tapakahxp** [comment]
Pickit.nip is commented out by default now. Dont realy understand what was point of doing this.

**Comment by theBGuy** [comment]
Point of it was not forcing everyone to always load a pickit. I always got annoyed having to go and comment it out.

**Comment by tapakahxp** [comment]
It was totally confusing for me.
I couldnt even imagine what kolton.nip is commented by default.

**Comment by theBGuy** [comment]
🤷‍♂️ nonetheless it makes sense for it to not be enabled by default. I think a majority of people don't even use the kolton.nip, preferring some custom one instead
