### ISSUE TITLE
Countness : Bot dont collect low Runes (sell)

### ISSUE THREAD

**Issue by tapakahxp** [blizzhackers/kolbot#376]
Low level runes properly listed in Kolton.nip:
[name] == tirrune # # [MaxQuantity] == 1
[name] == ethrune # # [MaxQuantity] == 1
[name] == talrune # # [MaxQuantity] == 2
[name] == ralrune # # [MaxQuantity] == 1
[name] == ortrune # # [MaxQuantity] == 2
[name] == thulrune # # [MaxQuantity] == 2
[name] == amnrune # # [MaxQuantity] == 1
[name] == solrune # # [MaxQuantity] == 2

Those runes are dropped from nightmare countness, but bot only picks them to sell.

**Comment by theBGuy** [comment]
Are you sure the kolton.nip is being loaded

**Comment by tapakahxp** [comment]
Oh, its looks like kolton.nip is no longer loaded by default.
https://github.com/blizzhackers/kolbot/blob/mainline/d2bs/kolbot/libs/config/Sorceress.js
