### ISSUE TITLE
Follower : add few new commands ?

### ISSUE THREAD

**Issue by tapakahxp** [blizzhackers/kolbot#377]
Is it possible to add few new commands for follower bot ?

"Chug": Get and drink some Thawing and Antidote potions from nearest merchant.
"ShareGold": Divide equal amount of gold among all members. Since some have 200k, some have 1k
"Talk Cain": After killing councils in act 3.

**Comment by theBGuy** [comment]
Can you just join the discord? Half of these issues you've been opening up are just spam that could of been answered easily in chat. Short answer is yes, besides the gold. It could be done but it'd be annoying to do as it would require communication between all of them.

**Comment by theBGuy** [comment]
talking is fixed now I had broken it in a previous commit, also added the chug command
