### ISSUE TITLE
Telestomp not working on e.g. de seis/ infector

### ISSUE THREAD

**Issue by tyson-dev** [blizzhackers/kolbot#381]
Looks to me like <s>dodging interferes</s> with Telestomp.

crap i wrote about dodging is wrong, they just skip with error.

Console says e.g.: "clear: failed to clear infector".

Setup Dodge/Telestomp:

Config.PacketCasting = 2; // 0 = disable, 1 = packet teleport, 2 = full packet casting. (disables casting animation for increased d2bs stability)
	Config.NoTele = false; // Restrict char from teleporting. Useful for low level/low mana chars
	Config.Dodge = true; // Move away from monsters that get too close. Don't use with short-ranged attacks like Poison Dagger.
	Config.DodgeRange = 15; // Distance to keep from monsters.
	Config.DodgeHP = 84; // Dodge only if HP percent is less than or equal to Config.DodgeHP. 100 = always dodge.
	Config.TeleStomp = true; // Use merc to attack bosses if they're immune to attacks, but not to physical damage

also skip immunes is set for the element (1 runner "cold", 1 runner "cold and fire").
If that's the cause could you make telestomp ( if set ) override skip immunes for bosses?

Cheers

**Comment by theBGuy** [comment]
There already is an option for that, `Config.SkipException` has existed for awhile
