### ISSUE TITLE
Shopbot Delay after taking waypoint

### ISSUE THREAD

**Issue by tyson-dev** [blizzhackers/kolbot#397]
it seems like there is a delay 1 - 1.5 secs each time after a waypoint has been taken before going back / walking to vendor.

While the interaction with the vendor is nearly instant this eats 3+ secs each cycle.

Is this a safety-feature? can this be configured for testing purposes?

**Comment by theBGuy** [comment]
<https://github.com/blizzhackers/kolbot/blob/0f1aefd495d76456419dbf67fff30b6fdb7ddd78/d2bs/kolbot/libs/core/Pather.js#L1421>

It's a safety delay to prevent crashing when the area is taking awhile to load.

**Comment by tyson-dev** [comment]
TY M8,

changed this delay to 100, nearly doubles cycles at charsi and no issues since 3days on shopbot or runners.

Might be a problem with slower/unstable ISP's though.

cheers
