### ISSUE TITLE
Need help w/ Setup

### ISSUE THREAD

**Issue by Greatly123** [blizzhackers/kolbot#399]
Running into issues with setup. I downloaded the .net and other program as requested, DL'd Tortoise, below is what happens when I attempt "SVN Checkout..."
https://gyazo.com/7ef67c957118376f6859d44d3b4dfbb0
https://gyazo.com/300e72217cf609061202879b2e6f765d
https://gyazo.com/12eff06a158be8d06459d0a295aff1fa

**Comment by magace** [comment]
https://github.com/magace/documentation/blob/master/d2bot/Download.md

Try using guthub desktop.  

It looks like your using the wrong url by the way.

**Comment by Greatly123** [comment]
> https://github.com/magace/documentation/blob/master/d2bot/Download.md
> 
> Try using guthub desktop.
> 
> It looks like your using the wrong url by the way.

Hey there, so I downloaded that, i've gotten it to where it will load up D2, Login to account, select char, make game..

Just not sure how to make it initiate the script when it enters the game. 
https://gyazo.com/0092ef5988deb1be918f1c767ad49035

**Comment by theBGuy** [comment]
Perhaps you should exercise the abilty to read. First the console you took an screenshot of, then the documentation repo that magace already linked

**Comment by Greatly123** [comment]
> Perhaps you should exercise the abilty to read. First the console you took an screenshot of, then the documentation repo that magace already linked

I went ahead and downloaded the desktop version, I'm having troubles configuring apparently, or just getting the script to run once the character enters the game. https://gyazo.com/0092ef5988deb1be918f1c767ad49035

Any insight as to what I should do to fix that would be greatly appreciated.

**Comment by theBGuy** [comment]
I gave you insight on what you should do to fix it. But alas another day another person refusing to read the available resources.

Step 1) follow the instructions on screen to make a copy of the character config.
Step 2) open that new file in any code editor, recommended to use vscode
Step 3) fill out the character config, this includes setting the scripts you want to run to `true`
Step 4) now start the bot again
Step 5) learn to read so you can do this without your hand being held

https://github.com/magace/documentation/blob/master/kolbot%2FCharacterConfig.md
