### ISSUE TITLE
New Kolbot Follower issue

### ISSUE THREAD

**Issue by Zaidore** [blizzhackers/kolbot#407]
Hi everyone, so i started D2 Classic again and set up kolbot. now i have a leader running smooth, but my follower will not join the game, i have set it to join the Characters name and use the D2botfollow.js for the follower, i saw online to edit the d2botfollow.dbj and edit the line where the character name stand, but this line is not present in my code, am i missing out on something or doing something wrong if anyone could point me in the right direction or know whats up please help.

also i tried setting the game name and password in the d2botfollow.dbj but this does not change anything, bot wil go to join menu and do nothing, please help.

**Comment by heavyburnin** [comment]
My guy I suggest you read the documentation. You need to edit, systems/follow/FollowConfig.js
  const JoinSettings = {
    "heavysorc": ["all"],
  };
https://github.com/blizzhackers/documentation

**Comment by Zaidore** [comment]
Hey, thanks for your reply, i actually already figured it out, i am not a star in scrips and coding, and i think that english not being my native lagueage has something to do with it to, but it is indeed those lines, but for me it was not clearly enough explained, indeed you need to set your names there but in reference i have:

  const JoinSettings = {
    "Leader": ["Leecher"],
	"BlizzBall": ["all"],

now it works, now i am looking into having the follower rejoin after chicken quit
