### ISSUE TITLE
d2bs is not responding ...starting profile (win 11, with d2legacy via installer)

### ISSUE THREAD

**Issue by miketheman222** [blizzhackers/kolbot#412]
hi there,

been runing kolbot for years, and actually still am on a different computer without any problems. just tried to set up a new notebook with win 11 and cant seem to wrap my head around this one.

d2 crashes with the line "D2BS is not responding... starting profile" in kolbot. i can run d2 (outside of kolbot) just fine (only in window mode, but whatever). 

However, there are a few differences compared to my other machine that might be the cause of the problem.

on this machine...
1.  i downloaded d2 with the official installer provided outside of battle.net. theres a link on the battle.net/blizzard site, ever since d2 resurrected got released. on my other machine, i either did a bnet-download or installed from cd (i do not remember for sure). 

2 .. i run microsoft NET SDK 8.0.204 (as .net framework was discontinued as a standalone download)

Some hard facts for reference

- win11 home 23h2
- intel iris xe graphics
- running Kolbot 20.6.7.100
- visual c++ 2010 10.0.40219
- character configs are the same on the other machine, so the error is not there. 

If this is not the place to ask for support, i'd appreciate directions.
thanks for any fixes or ideas

**Comment by ejt1** [comment]
This is a common issue which has already been answered multiple times, see #338
