### ISSUE TITLE
D2BotGameAction 

### ISSUE THREAD

**Issue by jacksealboy** [blizzhackers/kolbot#49]
Hello, after executing D2BotGameAction to automatically lose the equipment, when the task is completed, the waiting time of the character in the game can be shortened? How can I modify it? Thank you.

**Comment by jaenster** [comment]
i honestly have no idea what you mean

**Comment by jmichelsen** [comment]
I think what you're looking for is here in `D2BotGameAction.js`, at the top:
```
var StarterConfig = {
	MinGameTime: 240, // Minimum game length in seconds. If a game is ended too soon, the rest of the time is waited in the lobby
	CreateGameDelay: 5, // Seconds to wait before creating a new game
	SwitchKeyDelay: 0, // Seconds to wait before switching a used/banned key or after realm down
	CrashDelay: 120, // Seconds to wait after a d2 window crash
	RealmDownDelay: 2, // Minutes to wait after getting Realm Down message
	UnableToConnectDelay: 5, // Minutes to wait after Unable To Connect message
	CDKeyInUseDelay: 5, // Minutes to wait before connecting again if CD-Key is in use. SwitchKeys overrides this!
	ConnectingTimeout: 20, // Seconds to wait before cancelling the 'Connecting...' screen
	PleaseWaitTimeout: 10, // Seconds to wait before cancelling the 'Please Wait...' screen
	WaitInLineTimeout: 60 // Seconds to wait before cancelling the 'Waiting in Line...' screen
};
```
The `MinGameTime` is how long the char will stay in game after dropping an item.

**Comment by Fa-b** [comment]
it's actually in GameAction.js [here](https://github.com/blizzhackers/kolbot/blob/93171e96df4ddc9552910b14a5d36085e7f304a2/d2bs/kolbot/libs/GameAction.js#L13).
The comment is a bit confusing but this is the 'countdown' used before leaving the game after drop and log (see [here](https://github.com/blizzhackers/kolbot/blob/93171e96df4ddc9552910b14a5d36085e7f304a2/d2bs/kolbot/libs/GameAction.js#L175)).

**Comment by Fa-b** [comment]
I think the question has been answered therefore I'm closing this.
