### ISSUE TITLE
Cows - initnpc = undefined, doesnt buy tome

### ISSUE THREAD

**Issue by DarkHorseDre** [blizzhackers/kolbot#53]
Anyone have any ideas on this?

Just doing some SP testing (had an issue with cows I wanted to check) and had this scenario:

1. Stash was full and didnt pickup wirts leg
2. went to town and didnt id scepter to sell and make space
3. went to town (as if it had leg) and tried to buy tome, but no space
4. dialogue from akara 'you do not have space' was not clicked - bot ignored it 
5. cows.js failed because no tome (but no error relating to leg
6. saw the "initNPC: undefined" message (cows does this: 'akara = Town.initNPC("Shop");')

[ignore line numbers as Ive added a few lines to set players x in SP and a few other minor changes]

![image](https://user-images.githubusercontent.com/41862641/76145196-32f12900-607f-11ea-8e48-6399956e4ffe.png)

**Comment by jmichelsen** [comment]
This could be an easy fix, just have the bot do chores a couple times in between cow steps, to make sure space is made.

**Comment by DarkHorseDre** [comment]
> This could be an easy fix, just have the bot do chores a couple times in between cow steps, to make sure space is made.

indeed! altho it happened with rejuvs and other non-sellables.. #54 seems to be related too as it wont fail when it cant pick leg or when body already interacted

**Comment by macohan** [comment]
ooo something i have actually fixed in messing around with cows :D
i can actually provide some lines for once 
`	Town.goToTown(1);
	Town.doChores();
	leg = this.getLeg();
	Town.doChores();
	tome = this.getTome();`
this order has yet to failed me

**Comment by DarkHorseDre** [comment]
oh yeah for sure dochores should occur at the start of a script in most if not all cases and it clears standard stuff but not stuff you picked or intend to keep (like juvs) - which is fine, as thats standard (and I've only seen sonic rejig items) but the issue is the code doesnt work as intended (as written and referenced in #54) as it wont error on not collecting the leg and behaves strangely from that point on (trying to cube the tome with no leg etc)

**Comment by DarkHorseDre** [comment]
ok - one of the problems is if you use clearpath - it will kill champs and uniques (hopefully!) on the way, even within tristram, so you need to clearinventory before trying to interact with body

```js
		Pather.moveTo(25048, 5177);
		Town.goToTown(); //dhd added - 
		Town.doChores(); //dhd added - leg is not picked if inv full, plus no fail error if so..
		Pather.usePortal(null, me.name); //dhd added
```

Like I said, this is not needed with the static happy-path (dochores in town, assume have space, goto trist, kill nothing else and get leg, assuming body hasnt been interacted with either), and clearpath adds to the complexity - greater chance of picking items en-route and filling stash.

the code still does not error if the leg is not picked, which seems to be the intention..

**Comment by Fa-b** [comment]
I think the proposed workarounds are really just this.. 'workarounds'. In my eyes the actual problem is more general and has to be addressed deeper down. I have looked at Pickit.js and at first glance it appears, the function `pickItems` performs checks if a single item can fit after selling recursively before calling `pickItem`.
I have the feeling, rather than trying to do the same thing again for every occurance of `pickItem`, it would be wise to make a function for questItems within Pickit.js and use that instead. Because thats what the leg basically is. Alternatively, pass a array of units to pick like `pickItems([leg])` and replace the `pickItems` internal `pickList` if the parameter exists.

**Comment by DarkHorseDre** [comment]
Oh for sure @Fa-b - I'm no dev :) I purposely avoid modifying the core as I don't understand it enough/could make things worse.
I bring investigate and log these things so the more knowledgeable people can run with it, as you guys have ;)

The problem I highlighted was the ungraceful manner of failure. you said it: canfit is used and yet if it cannot fit leg there is no meaningful failure. infact, there is no failure, the bot continues as if it has the leg and fails more in town.  as we know from town.js, some failures can end in death!

a consistent example is in boss scripts, the bot will fail if it cannot find the boss, goto town and continue with the next function.
here, the cows function tries to cube a leg it didnt pick!

My workaround now includes a `Storage.Inventory.FindSpot` (compensates for the failures you mention) and a check to see if the body has been interacted with (no point trying if its gonna fail), and force fail if pickleg fails, as it continues to town causing the aforementioned failures
