### ISSUE TITLE
MFLeader / MF Helper issue

### ISSUE THREAD

**Issue by fatboi615** [blizzhackers/kolbot#55]
**I am running a Hammer Pally (MFLeader) and a Sorc (MFHelper) and everything works great but when in Act 5 only the helper wont help with worldstone it will only do scripts i have it set to and baal. everything else it should mfhelp with it does not in act 5, all other acts work fine.**

**Comment by jmichelsen** [comment]
Trying to understand this. So when your MFHelper team gets to Worldstone, the sorc stops helping?

**Comment by fatboi615** [comment]
> Trying to understand this. So when your MFHelper team gets to Worldstone, the sorc stops helping?

correct, it will only do baal with leader in act 5

**Comment by 5noop** [comment]
MFHelper will stop if your leader is in chaos or throne of destruction. Are you running diablo before act 5 ?

**Comment by fatboi615** [comment]
well yea the leader does chaos then worldstone then baal

**Comment by 5noop** [comment]
Change the order to finish with chaos and baal.

**Comment by fatboi615** [comment]
> Change the order to finish with chaos and baal.

Thank you that worked!
