### ISSUE TITLE
AutoEquip issue: clearInventory() is before stash() in Town.doChores()

### ISSUE THREAD

**Issue by S4KANA** [blizzhackers/kolbot#56]
In Town.doChores() the call to clearInventory() comes with before stash(). This is an issue with AutoEquip enabled, because items that cannot be equipped (runes, charms, etc.) will be dropped or sold instead of stashed due to this ordering since they always fail this check in clearInventory() 
`
if (!Item.autoEquipCheck(items[i])) {
    result = 0;
}`

I suppose the current ordering should be kept so lower tiered items are not stashed, but there should be some guard statements preventing stuff with no tier from being dropped

**Comment by Fa-b** [comment]
Hmm I just looked at autoEquipCheck and it appears to do that already:
```js
// Sell/ignore low tier items, keep high tier
if (tier > 0 && tier < 100) {
	return false;
}

return true;
```

`tier = NTIP.GetTier(item)` should return `-1` if a item has no tier at all.. Are you sure this is the exact issue you are having?
