### ISSUE TITLE
Window has unexpectedly exited... starting profile

### ISSUE THREAD

**Issue by Moik48** [blizzhackers/kolbot#62]
Hi all,

I am a bit new to this. I am trying to set up the bot but it doesn't run as expected :)

10:10:22 (Melissandre) Window has unexpectedly exited... starting profile
10:10:23 (Melissandre) Window has unexpectedly exited... starting profile
10:10:24 (Melissandre) Window has unexpectedly exited... starting profile
10:10:25 (Melissandre) Window has unexpectedly exited... starting profile

FYI: 
- Using windows 10
- Running the D2Bot as Admin. 
- Profile created (cf. img).
- Keys created (Real ones)
- Downloaded the latest D2 file for blizzard
- Downloaded this kolbot update

Would you have any idea? 

![Img](https://user-images.githubusercontent.com/62465284/77224489-1b756e00-6b5e-11ea-8fbd-033cad1b24dc.PNG)

**Comment by mf022** [comment]
Did you check the logs?
https://github.com/blizzhackers/documentation/blob/master/kolbot/FAQ.md/#window-has-unexpectedly-exited-starting-profile
