### ISSUE TITLE
Kolbot only logs 1 character items, not second character? 

### ISSUE THREAD

**Issue by Smeltet** [blizzhackers/kolbot#65]
So I have 2 profiles running in parallel in the same game, however, itemlog.txt only logs items from first character and not second? Is this a read/write issue or known bug in the bot?

**Comment by Smeltet** [comment]
So noone knows???

**Comment by jogohnwer** [comment]
when i run 3 toons at same time (2 together mf team, and 1 by itself) it
loggs every item that the characters stash defined by picket it also tells
you which file and what line the pickit item.... (idk a good word to
describe it) code? description? rule?
i havent checket the item log text but i know it surely tells you in
profile manager (program u use to start bots)
i couldnt find out how to get to this post and im kinda in rush so i have
no idea what the original question was at any rate i hope this was helpful.

**Comment by Smeltet** [comment]
Thx jogohnwer, I see all items kept/cubed etc., fine in the bot window, but once I close it, that dissappears and I have no "history". The file kolbot/logs/itemLog.txt should list all dropped, gambled, kept etc., but it only lists for the first profile, not the rest? So how do I get whatever is happening in the bot window, to also be printed in a file? And if it already is, then what am I missing and where is that log file located? I hope this was a bit more specific?

**Comment by Smeltet** [comment]
Does the above further explanation help anyone solve my issue?

**Comment by Fa-b** [comment]
Tbh I never really inspected the itemlog.txt because it is not very readable anyways. I think your issue could have been caused by multiple proccesses attempting to access the same file at the same time. Maybe the first profile never closed the file.

The latest D2BS should solve this issue by splitting logs into single files per profile.
