### ISSUE TITLE
Potentially wrong area?

### ISSUE THREAD

**Issue by david1602** [blizzhackers/kolbot#69]
@jaenster I just checked the most recent commit and noticed this: https://github.com/blizzhackers/kolbot/commit/c8600d9142b34be108f8e8f480adb2ef8f05f484#diff-45b33fc71cc4ec8609661aadd6aa7ac8R160

Shouldn't that be `KurastDocktown`, to line up with the other blocks?

**Comment by jaenster** [comment]
Thank you =)
