### ISSUE TITLE
repos update error

### ISSUE THREAD

**Issue by xWickedx420** [blizzhackers/kolbot#72]
C:\Users\xwick\Desktop\My Files\kolbot from https://github.com/blizzhackers/kolbot
The node 'C:\Users\xwick\Desktop\My Files\kolbot\jaenster-patch-2' was not found.

**Comment by jaenster** [comment]
Eh...

I removed this branch ealier today, yet you switch your branch to the master version, as that is the "current" version =) I dont know how you ended up at that branch😅

**Comment by xWickedx420** [comment]
whats the right repo?

**Comment by jaenster** [comment]
This is the right repo, but you need to be on the master branch,

**Comment by xWickedx420** [comment]
how do i accomplish that? sorry lol

**Comment by jaenster** [comment]
https://confluence.atlassian.com/bitbucket/checkout-a-branch-into-a-local-repository-313466957.html

I think this will help ya

**Comment by xWickedx420** [comment]
it doesn't im not very computer savvy, guess im screwed.

**Comment by xWickedx420** [comment]
thanks for the fun bot. it's been a blast. best of luck

**Comment by macohan** [comment]
yes
in 2020 computer illiteracy does make one screwed

**Comment by xWickedx420** [comment]
glad you understand it all, works for you. shit worked for me too for months until today

**Comment by xWickedx420** [comment]
Funny the guy asks for help, and you guys are too busy to help him. 

You guys say you're here for the people and working on this for everyone, yet give bad support. 

Why even work on this when their is already a working copy from Kolton himself if you aren;'t going to help people who have issues?

What a wasteful toxic community. I won't be apart of this anymore.

**Comment by macohan** [comment]
oops forgot to log in to your other account to make that comment huh?
literally everything you need is in that link above

**Comment by jaenster** [comment]
Feel free to play the game your self instead 🙃 goodluck
