### ISSUE TITLE
static baal wave

### ISSUE THREAD

**Issue by problemseverywhere** [blizzhackers/kolbot#82]
anyone knows how to put in config to cast static in last wave?

**Comment by moodew** [comment]
yes, use this section in your character config: /* Advanced Attack config. Allows custom skills to be used on custom monsters.
	 *	Format: "Monster Name": [timed skill id, untimed skill id]
	 *	Multiple entries are separated by commas
	 */
	Config.CustomAttack = {
		//"Monster Name": [-1, -1]
	};

**Comment by Fa-b** [comment]
there is also:
```js
Config.StaticList = []; // List of monster NAMES or CLASSIDS to static. Example: Config.StaticList = ["Andariel", 243];
```
In character config. You can configure it for `Lister the Tormentor`.

Closing this as solved for now.
