### ISSUE TITLE
Error: module d2bs/kolbot/libs/modules/sdk not found

### ISSUE THREAD

**Issue by Innova133** [blizzhackers/kolbot#91]
Just checked out the code clean and am getting this error:

[Error (o)] File(threadtools:32) Error: module d2bs/kolbot/libs/modules/sdk not found

Offending line of code:  https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/tools/ToolsThread.js#L32

I do have the sdk.js file locally, not sure why it isn't being found?
https://github.com/blizzhackers/kolbot/tree/master/d2bs/kolbot/libs/modules

**Comment by mikemeerschaert** [comment]
I have the same issue. clean install.

**Comment by Amob13** [comment]
same issue when helping a friend. any fix to this found?

**Comment by mf022** [comment]
> I do have the sdk.js file locally, not sure why it isn't being found?

where did you install kolbot? directly on desktop, or on other place?
maybe you should try to put it into a folder created into the root of a drive, like C:\kolbot , or D:\kolbot, ... (like in the [guide](https://github.com/blizzhackers/documentation/blob/master/d2bot/Download.md#download-with-tortoisesvn))
(desktop location contains the user name of the PC, and maybe the path is too long, or it has different charsets included)
