### ISSUE TITLE
How to help with Dev

### ISSUE THREAD

**Issue by daniel-butler** [blizzhackers/kolbot#93]
Where do I start to help? It’s not obvious to me how d2bs.exe is created and how I could even start to look at the code to help. 

Thank you!

**Comment by david1602** [comment]
https://github.com/blizzhackers/d2bs I believe this is what you build the executable (the actual script hook) from

https://github.com/blizzhackers/d2bot and this is what you build the bot manager from

but I guess most of the things you can do to support and improve are individual scripts
