### ISSUE TITLE
Chaos Map Coordinates

### ISSUE THREAD

**Issue by Fishome80** [blizzhackers/kolbot#95]
Hi, I try to find the map or similar information i can figure out the Chaos Map Coordinates as below.

Example: this.starToSeisA = [7781, 5259, 7805, 5258, 7802, 5237, 7776, 5228, 7775, 5205, 7804, 5193, 7814, 5169, 7788, 5153];

what I want is let my Hammerdin precast BHs at some point before leader open the seal. also i don't know how to let hammerdin precast same as Baalrun

I will be preciated if someone can help me to figure it out

**Comment by Fa-b** [comment]
[here](https://github.com/blizzhackers/kolbot/blob/744947891dd968e9a8e3d32b2009f524594b196f/d2bs/kolbot/libs/bots/DiabloHelper.js#L143), [here](https://github.com/blizzhackers/kolbot/blob/744947891dd968e9a8e3d32b2009f524594b196f/d2bs/kolbot/libs/bots/DiabloHelper.js#L166) and [here](https://github.com/blizzhackers/kolbot/blob/744947891dd968e9a8e3d32b2009f524594b196f/d2bs/kolbot/libs/bots/DiabloHelper.js#L192) are the places where the seals will be prepared and opened. As you can see for the infectorSeal, there is a `doPrecast` call before actually moving direction infector(`followPath`). Using default seal order this should lead to your helpers precasting after `de Seis` is killed.
If you want it to precast after seal preparation but before the seal should be opened, you can add such a doPrecast call between `followPath` and `openSeal` instead like so:
```js
this.seisSeal = function () {
	this.followPath(this.seisLayout === 1 ? this.starToSeisA : this.starToSeisB, this.sort);

	Precast.doPrecast(true);

	if (Config.DiabloHelper.OpenSeals) {
		if (!this.openSeal(394)) {
			throw new Error("Failed to open de Seis seal.");
		}
	}

	if (this.seisLayout === 1) {
```
Be aware that the Leader will not wait for your helpers precast before opening the seals though.
