### ISSUE TITLE
config lowgold glitched

### ISSUE THREAD

**Issue by tunz347** [blizzhackers/kolbot#97]
Hello guys, i've noticed that bot is stashing and muling junk crafts and whites while trying to do some gold. Anyone able to edit this chapter ? It already stashed tons of trash, please someone advanced get this done, tyvm in advance!

**Comment by tunz347** [comment]
> can anyone confirm this behaviour?

not sure many people are involved with this config, but i surely confirm it.
while having your lowgold enabled, bot will consider trash item as(gold) and will mule it.

**Comment by 5noop** [comment]
This should be fixed by replacing `Pickit.checkItem(item).result > 0` by `Pickit.checkItem(item).result === 1` in this file https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/AutoMule.js#L470

Please test it and tell us if it's working properly.

**Comment by tunz347** [comment]
> This should be fixed by replacing `Pickit.checkItem(item).result > 0` by `Pickit.checkItem(item).result === 1` in this file https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/AutoMule.js#L470
> 
> Please test it and tell us if it's working properly.

Didn't work out unfortunately, been testing it the whole day.. it still keeps all crafts right after crafting (even though rubbish), seems to be clean from whites though but not confirmed yet, will update tomorrow.. i srsly had my finger's crossed on this
Pickit.checkItem(item).result === 1, this option worked only for the whites seems like but gotta edit tomorrow.

**Comment by 5noop** [comment]
It should only mule what's in your pickit, except if it's already in your stash.
Which crafted item were kept ? (gloves, amu, rings.. ?)
Could you post your pickit files on https://pastebin.com/ and link them here ?

**Comment by tunz347** [comment]
> It should only mule what's in your pickit, except if it's already in your stash.
> Which crafted item were kept ? (gloves, amu, rings.. ?)
> Could you post your pickit files on https://pastebin.com/ and link them here ?

When lowgold disabled none of these crafts are being kept and muled, yes i currently craft variety of stuff like boots,gloves, ammys, rings, bot stashes them after crafting and muling afterwards
Only way to prevent this is disable crafting and do only golddigging

**Comment by Sylvm** [comment]
Check your .nip files for something like :
`# #`
or 
`[quality] == normal # #`
