### ISSUE TITLE
auto smurf or sonic script configured for HC ?

### ISSUE THREAD

**Issue by jompy1926** [blizzhackers/kolbot#98]
Hello everyone,

I am interested to configure sonic or auto smurf scrip for Hardcore.  Already tried to do it bymyself but without success - too many chickens or other minor bugs like not buying potions( even having gold) or not selling items , when full inventory....

So does someone have configured/amended sonic or auto smurf script for HC ? Can you share it so i can try it and enjoy it ? Also any kind of tips are welcome..

If the scrip is working properly I am willing to donate

cheers and thanks in advance!

**Comment by mf022** [comment]
I guess that solo sorceress (... sonic) isn't a good idea for HC mode.
A well chosen team should be ok on autosmurf, after barbarian char get level 24+, and paladin get concentration aura, ...
Maybe you should add the mercenaries for each bot, and also you should increase the default levels <https://github.com/blizzhackers/autosmurf/blob/master/d2bs/kolbot/libs/bots/AutoSmurf.js#L11-L26>.
